README.md
gen-raw-logs.py
generic-subgraph-generator/src/main.rs
graph-descriptions/Cargo.toml
graph-descriptions/build.rs
graph-descriptions/proto/graph_description.proto
graph-service/src/graph_merger/server.rs
grapl-cdk/cdk.json
grapl-cdk/deploy_all.sh
grapl-cdk/index.ts
grapl-cdk/package-lock.json
grapl-cdk/package.json
node-identifier/Cargo.lock
node-identifier/Cargo.toml
node-identifier/src/cache.rs
node-identifier/src/lib.rs
node-identifier/src/session.rs
node-identifier/src/session_history.rs
sqs-microservice/src/lib.rs

This PR adds:
* Caching to node-identifier, in the form of an in memory LRU cache
* A `Service` class to Grapl's CDK

Node identifier perf

---

Grapl Provision.ipynb
docker-compose.yml
engagement_ux/engagement_edge/requirements.txt
graph-descriptions/src/lib.rs
graph-generator-lib/Cargo.lock
graph-merger/Cargo.lock
local_grapl/grapl_provision.py

This is a minor change to make some methods for NodeProperty public.

Make some more methods public

---

.github/workflows/docker-engagement-view.yaml

This image should set up npm/yarn.

Install yarn in action

---

src/rust/sysmon-subgraph-generator/src/main.rs

Minor change to use environment loglevel

Use env loglevel

---

.github/workflows/grapl-release.yml

Internal 9 fix workflow

---

.github/ISSUE_TEMPLATE/blank_issue.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation_request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/plugin_request.md
.github/SECURITY.md
.github/pull_request_template.md
.gitignore
CONTRIBUTING.md

This PR is an initial attempt at some community documentation to help contributors navigate Grapl.
- `CONTRIBUTING.md`
- Security policy
- Issue templates
- Pull request template

Community docs

---

.github/workflows/grapl-release.yml

Hopefully this is the last one >_<

Fix release workflow

---

.github/workflows/grapl-release.yml

Need to specify python3 in grapl-release workflow

---

.github/workflows/grapl-release.yml

There are some prerequisites to getting Python installed in the workflow execution environment, this accomplishes that.

Configure python correctly

---

docker-compose.yml
src/rust/Cargo.lock
src/rust/analyzer-dispatcher/src/main.rs
src/rust/graph-descriptions/Cargo.toml
src/rust/graph-generator-lib/Cargo.toml
src/rust/graph-merger/src/main.rs
src/rust/grapl-config/Cargo.toml
src/rust/node-identifier/src/bin/node-identifier-retry-handler.rs
src/rust/node-identifier/src/bin/node-identifier.rs
src/rust/sysmon-subgraph-generator/src/main.rs

Bump graph generator lib

---

src/js/graphql_endpoint/server.js
src/js/grapl-cdk/lib/engagement.ts
src/js/grapl-cdk/lib/graphql.ts
src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/package-lock.json

This was pretty simple. We didn't pass in the env var for the origin, now we do.

Fix cors error in graphql-endpoint

---

src/rust/graph-merger/src/main.rs

Instead of creating a new grpc client for every invocation of "handle_event", which there can be many of in a single service (hundreds, thousands even?) this reuses the client for each service.

Only use one client per service

---

src/js/grapl-cdk/.prettierrc.toml
src/js/grapl-cdk/README.md
src/js/grapl-cdk/bin/grapl-cdk.ts
src/js/grapl-cdk/cdk.context.json
src/js/grapl-cdk/cdk.json
src/js/grapl-cdk/jest.config.js
src/js/grapl-cdk/lib/dgraph.ts
src/js/grapl-cdk/lib/engagement.ts
src/js/grapl-cdk/lib/event_emitters.ts
src/js/grapl-cdk/lib/graphql.ts
src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/lib/historydb.ts
src/js/grapl-cdk/lib/redis.ts
src/js/grapl-cdk/lib/service.ts
src/js/grapl-cdk/lib/userauthdb.ts
src/js/grapl-cdk/test/grapl-cdk.test.ts
src/js/grapl-cdk/tsconfig.json

First commit is a format run.
The meat of this PR is in the second, which cleans up AWS policies in the CDK. There's a few issues it resolves:
1. `s3:ActionGetObject` isn't a thing
2. resources for s3:GebObject action need path wildcard
3. remove extra perms granted in a TODO

CDK - Cleaning up AWS policies 

---

src/python/analyzer_executor/Dockerfile

Simple change to fix zip files.

Update Dockerfile to cd before zip

---

.github/workflows/grapl-release.yml
dobi.yaml
src/js/graphql_endpoint/Dockerfile
src/python/grapl-dgraph-ttl/Dockerfile

some fixes

---

.github/workflows/grapl-release.yml

another release workflow fix

---

.github/workflows/grapl-release.yml

Internal 37 moar workflow fixes

---

.github/workflows/grapl-release.yml

fix release flow

---

.github/workflows/grapl-build.yml

Make sure Python artifact versions are up to date.

add check-pypi job to build workflow

---

.github/workflows/grapl-build.yml
.github/workflows/grapl-lint.yml
CONTRIBUTING.md
README.md
dobi.yaml

Docs updates in preparation for v0.2.0 release.

V0.2.0 docs update

---

BUILDING.md
CONTRIBUTING.md

NA
This PR adds a `BUILDING.md` document to describe the build system.
NA

add BUILDING.md

---

CONTRIBUTING.md
README.md
docs/setup/local.md
src/python/grapl_analyzerlib/README.md

#214
Change the docs urls.
I visited the doc urls.

Update doc urls to grapl.readthedocs

---

src/js/engagement_view/src/Login.tsx
src/js/engagement_view/src/modules/GraphViz/engagement_edge/getApiURLs.tsx

There were two issues observed in the Engagement in UX in AWS:
1. Login button was pointing to incorrect URL, due to regex hack mismatch.
2. Redirect after login pointed to incorrect URL per new routing.
This resolves the two problems listed above.
These fixes were tested in my AWS sandbox.

Engagement UX fixes

---

src/python/analyzer_executor/src/analyzer-executor.py
src/python/engagement-creator/src/engagement-creator.py
src/python/grapl_analyzerlib/grapl_analyzerlib/execution.py

None
Adds an optional field to ExecutionHit that, if specified, says which node_keys (among the nodes/edges, also in the message) are high-signal and should be attached to the Risk node.
that's why this is WIP lol

[wip] Added risky_nodes to ExecutionHit

---

dobi.yaml
src/js/grapl-cdk/Dockerfile

None
This adds a CDK build step to `dobi js`. It does not run tests yet.
`dobi js` + mucking with the CDK code to cause a typecheck error

Add a half-baked CDK Build to Docker/Dobi

---

src/python/engagement-creator/src/engagement-creator.py

`dobi python-typecheck` works now

Fixed python typecheck

---

src/js/engagement_view/src/components/GraphViz.tsx

https://github.com/grapl-security/grapl/issues/247
This is a simple change. It reverts some aspects of the interval management.
I've tested locally.

Switch interval method

---

src/rust/metric-forwarder/src/cloudwatch_send.rs

#232
This was a TODO - the statsd message passes along tags, and we weren't storing them in Cloudwatch.
i added tests :O :O

Metric Forwarder will also pass along tags (as Dimensions)

---

src/rust/grapl-observe/src/lib.rs
src/rust/grapl-observe/src/metric_error.rs
src/rust/grapl-observe/src/metric_reporter.rs
src/rust/grapl-observe/src/writer_wrapper.rs
src/rust/sysmon-subgraph-generator/src/main.rs
src/rust/sysmon-subgraph-generator/src/metrics.rs

#232 metrics
modify the MetricReporter so we can inject stuff and test it
unit tests baybeeee

better testing around MetricReporter - dependency inject utcnow, Write

---

src/python/grapl-common/grapl_common/metrics/metric_reporter.py
src/python/grapl-common/grapl_common/metrics/statsd_formatter.py
src/python/grapl-common/tests/metrics/test_metric_reporter.py
src/python/grapl-common/tests/test_time_utils.py

#232
Adds the MetricReporter abstraction to our python services. My next diff will actually integrate it into a python service, if possible.
i wrote tests wowza

Port MetricReporter to python

---

src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/python/engagement-creator/mypy.ini
src/python/engagement-creator/requirements.txt
src/python/engagement-creator/src/engagement-creator.py
src/python/engagement-creator/src/metrics.py
src/python/grapl-common/grapl_common/metrics/metric_reporter.py
src/python/grapl-common/grapl_common/metrics/statsd_formatter.py
src/python/grapl-common/grapl_common/time_utils.py
src/python/grapl-common/mypy.ini
src/python/grapl-common/setup.py
src/python/grapl-common/tests/metrics/test_metric_reporter.py
src/python/grapl-common/tests/metrics/test_statsd_formatter.py
src/python/grapl-common/tests/test_time_utils.py

#232 
Adds rudimentary metrics to one of our service, engagement creator.
...also:
- fixed up grapl_common a bit (the setup.py was slightly wrong)
- more strict mypy in grapl_common and engagement-creator
- introduced `histogram_ctx()`
added some tests

added EngagementCreatorMetrics as a sample of metrics in a Python service

---

.github/workflows/grapl-release.yml

Add Metric Forwarder steps to grapl-release.yml

---

.github/workflows/grapl-build.yml
dobi.yaml
docs/setup/local.md
src/python/grapl_e2e_tests/main.py
src/python/grapl_e2e_tests/resources.py
src/python/grapl_e2e_tests/tests.py

#231
Adds a test that asserts dgraph is populated with a Lens node pointing at 3 things after consuming the Sysmon logs.
its tests

Flesh out the "does dgraph get populated" e2e test

---

src/python/grapl-model-plugin-deployer/src/grapl_model_plugin_deployer.py
src/python/grapl_analyzerlib/grapl_analyzerlib/node_types.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/network_connection.py
src/python/grapl_analyzerlib/grapl_provision.py
src/python/grapl_e2e_tests/tests.py

#299 
We add an extra column in dynamodb, which stores the relationship type of an edge, which can then be queried elsewhere to better determine how to provision the graph.
I've tested my changes locally by deploying a test plugin.

Store more information in schema_table

---

.github/workflows/grapl-release.yml
.github/workflows/grapl-staging-release.yml
dobi.yaml
docker-compose.yml
etc/build_scripts/extract_rust_artifacts.sh
etc/build_scripts/push_py_to_docker.sh
etc/build_scripts/push_rust_to_docker.sh

#231 - this is something I want to get done on the way to "E2E testing for the AWS Plugins repo"
- Adds a new workflow that spits out Docker images to Dockerhub (whenever pushed to staging) with a stable tag: "-staging". 
- Pulls lots of copied code out into etc/build_scripts.
crossing fingers

Push 'staging' to docker every time it gets a new push

---

docker-compose.yml

#231 
comment out a service in docker-compose.yml, since we don't release it anywhere yet
run-e2e-integration-tests

Remove analyzer-deployer from docker compose yml

---

.github/workflows/grapl-release.yml

just look at the changed files section and have a nice cry with me

Fix the 'export tag' step

---

.github/workflows/grapl-release.yml

- versus _ will be the end of me
(I copy pasted these new commands locally and they worked)

Fix grapl-common release

---

dobi.yaml
src/python/grapl-model-plugin-deployer/mypy.ini
src/python/grapl-model-plugin-deployer/setup.py
src/python/grapl-model-plugin-deployer/src/grapl_model_plugin_deployer.py

none in particular
instead of a 400
return a 401 for "must log in"
good one, good joke guys

Grapl model plugin deployer: return a 401 Unauthorized if must log in

---

etc/local_grapl/unique_cmd_parent/main.py

A similar change was needed in suspicious_svchost.
I saw this while watching the logs for e2e tests.
e2e tests

Fix a potential race condition in unique_cmd_parent

---

.github/workflows/grapl-build.yml

#231 
its pretty self explanatory
since we save log artifacts now, this will be useful 👍

e2e tests run with DEBUG log level

---

src/python/analyzer_executor/src/analyzer_executor_lib/analyzer_executor.py
src/python/engagement-creator/src/engagement-creator.py
src/python/grapl-model-plugin-deployer/src/grapl_model_plugin_deployer.py
src/python/grapl_analyzerlib/grapl_analyzerlib/grapl_client.py

none
I don't actually know if analyzer-executor ever goes into an analyzer's `on_response()`. It makes sense to LOGGER.debug() when that happens. 
Aaaaand I also cleaned up the disparate GraphClient stuff because it annoyed me :) 
our beautiful and wonderful test infrastructure

Add some additional logging to Analyzer Executor. And remove copied `mg_alphas()` code.

---

dobi.yaml
src/python/grapl_analyzerlib/grapl_analyzerlib/comparators.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/asset.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/base.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/engagement.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/entity.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/file.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/ip_address.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/ip_connection.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/ip_port.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/lens.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/network_connection.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/process.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/process_inbound_connection.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/process_outbound_connection.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/risk.py
src/python/grapl_analyzerlib/grapl_analyzerlib/queryable.py
src/python/grapl_analyzerlib/grapl_analyzerlib/retry.py
src/python/grapl_analyzerlib/grapl_analyzerlib/schema.py
src/python/grapl_analyzerlib/grapl_analyzerlib/subgraph_view.py
src/python/grapl_analyzerlib/grapl_analyzerlib/view_from_proto.py
src/python/grapl_analyzerlib/grapl_analyzerlib/viewable.py
src/python/grapl_analyzerlib/pytype.cfg
src/python/grapl_analyzerlib/setup.py
src/python/grapl_analyzerlib/test2.py
src/python/grapl_analyzerlib/test_utils/view_assertions.py
src/python/grapl_analyzerlib/tests/test_comparators.py
src/python/grapl_analyzerlib/tests/test_process_node.py

None
We currently have Absolutely No Automated Typechecking on analyzerlib. This change:
- adds `pytype`ing it to dobi
- does NOT include it in `dobi python-typecheck`
- as such, does NOT include it in our CI
- but also, I renamed all our typecheck jobs so they stop duplicating the genuinely useless 'run' in 'run-x-unit-tests'
So, why add this? 
Well - you gotta start somewhere, right?
TAG=latest dobi typecheck-grapl-analyzerlib
```
Successfully installed coverage-5.3 decorator-4.4.2 grapl-analyzerlib-0.2.72 importlab-0.5.1 networkx-2.5 ninja-1.10.0.post2 pytest-cov-2.10.1 pytype-2020.10.8 typed-ast-1.4.1
ninja: Entering directory `/home/grapl/grapl_analyzerlib/.pytype'
[1/101] check grapl_analyzerlib.extendable
[2/101] check grapl_analyzerlib.retry
[3/101] check …
```

Add a typecheck-grapl-analyzerlib to dobi. grapl-analyzerlib now passes pytype (!!)

---

src/python/grapl-model-plugin-deployer/src/grapl_model_plugin_deployer.py

This is a hotfix for a service that is still MVP.
This runs part of the deployment process in a background thread. This is really an awful workaround for the fact that the deployment isn't transactional.
Tested locally and in AWS.

Model plugin deployer fix

---

.github/workflows/grapl-build.yml
docker-compose.yml
etc/ci_scripts/dump_compose_artifacts.py
src/python/grapl-common/grapl_common/debugger/vsc_debugger.py
src/python/grapl-tests-common/grapl_tests_common/setup.py
src/python/grapl-tests-common/grapl_tests_common/wait.py

#231 
checking artifacts on this very diff

draft - Record contents of dgraph when running e2e tests

---

etc/ci_scripts/dump_compose_artifacts.py

Oops, uncomment a line

---

dobi.yaml
src/python/engagement_edge/mypy.ini
src/python/engagement_edge/setup.py
src/python/engagement_edge/src/engagement_edge.py

My next task ( https://github.com/grapl-security/issue-tracker/issues/115 ) has me editing Engagement Edge.
I like static types. 
I also discovered many unused functions in here.

Typecheck engagement_edge

---

docs/setup/aws.md
etc/Grapl Provision.ipynb
etc/aws/upload_analyzer_prod.sh
etc/build_scripts/extract_rust_artifacts.sh
etc/build_scripts/push_py_to_docker.sh
etc/build_scripts/push_rust_to_docker.sh
etc/local_grapl/bin/gen-raw-logs.py
etc/local_grapl/bin/upload-sysmon-logs.py
etc/local_grapl/bin/upload_analyzer_local.sh
etc/local_grapl/suspicious_svchost/main.py
src/js/grapl-cdk/README.md
src/js/grapl-cdk/bin/deployment_parameters.ts
src/js/grapl-cdk/bin/grapl-cdk.ts
src/js/grapl-cdk/lib/alarms.ts
src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/lib/pipeline_dashboard.ts
src/js/grapl-cdk/lib/service.ts
src/python/engagement-creator/src/engagement-creator.py

#414 
- Emit `risk_node` metrics in Engagement Creator.
- Listen for (and alert on) these metrics in CDK.
- Also, I added a dashboard for our core pipeline to CDK. Makes it easy to look at-a-glance 
- Finally, I updated some documentation and scripts to make it easier to upload analyzers/testdata to an AWS instance.
On my aws sandbox

Rudimentary, hacky alerts for any risk node.

---

.github/workflows/grapl-lint.yml
etc/ci_scripts/py_lint.sh

none in particular
make isort/black bone simple and not a thin you need to devote any neurons to
locally

Easy py linter command 

---

src/js/grapl-cdk/fetch_zips_by_tag.py

https://github.com/grapl-security/issue-tracker/issues/118
see the attached issue - everything with an [x] has been done.
on my machine with 
```
wimax@penguin:~/src/grapl/src/js/grapl-cdk$ python3 fetch_zips_by_tag.py --version latest --tag v0.2.5
Downloading https://github.com/grapl-security/grapl/releases/download/v0.2.5/metric-forwarder-v0.2.5-latest.zip
Downloading https://github.com/grapl-security/grapl/releases/download/v0.2.5/analyzer-dispatcher-v0.2.5-latest.zip
Downloading https://github.com/grapl-security/grapl/releases/download/v0.2.5/generic-subgraph-generator-v0.2.5-latest.zip
Downloading https://github.com/grapl-security/grapl/releases/download/v0.2.5/sysmon-subgraph-generator-v0.2.5-latest.zip
Downloading https://github.com/grapl-security/grapl/releases/download/v0.2.5/node …
```

Freshen up the fetch zips script - we found some misses during nov23 testing

---

src/js/grapl-cdk/README.md
src/js/grapl-cdk/swarm/swarm_setup.py

Resolves two issues with grapl-cdk/swarm/swarm_setup.py:
1. Fixes broken variable expansions
2. lowercase upon variable expansion
Also, this updates the README accordingly per these changes, and other recent changes to bin/deployment_parameters.ts.
Tested in AWS deployment.

Swarm setup fix

---

src/js/grapl-cdk/README.md

None
This PR updates the CDK README to fix a deficiency in the DGraph setup documentation.
NA

cdk README fix

---

etc/githooks/README.md
etc/githooks/pre-commit

none
you can now opt into automatically linting by following these instructions
by committing this very commit :O and it worked
as for timing, pretty quick:
```
time git commit --allow-empty -m "just triggering a lint"
>> Running isort
Skipped 14 files
pick 3cde9069 Add instructions for pre-commit hooks
>> Running black
All done! ✨ 🍰 ✨
143 files left unchanged.
[pchook a5065e5a] just triggering a lint
real    0m0.678s
user    0m0.539s
sys     0m0.141s
```

Add instructions for pre-commit hooks

---

src/js/graphql_endpoint/package.json
src/js/graphql_endpoint/server.js
src/js/grapl-cdk/lib/swarm.ts
src/python/engagement_edge/src/engagement_edge.py
src/python/engagement_edge/tests/test_engagement_edge.py
src/python/grapl-model-plugin-deployer/src/grapl_model_plugin_deployer.py

https://github.com/grapl-security/issue-tracker/issues/121
Patches issues in our origin validation logic and failure cases which could allow reading from other origins.
Local validation

Fixes for CORS vulnerabilities

---

src/js/grapl-cdk/lib/swarm.ts

This PR updates an issue with string escapes in the CDK
AWS sandbox

Internal 126 bugfix

---

.github/workflows/grapl-build.yml
dobi.yaml
src/js/grapl-cdk/.dockerignore
src/js/grapl-cdk/Dockerfile

none
- makes CDK its own task in CI as opposed to lumped in to integration tests and build and stuff
- optimized CDK dockerfile to cache dependencies
locally (✿◕‿◕)

Github Actions / Dobi / Docker: Change when CDK build happens at CI time. Optimize CDK dockerfile.

---

src/js/engagement_view/src/components/EngagementViewContent.tsx
src/js/engagement_view/src/components/GraphViz.tsx
src/js/engagement_view/src/components/SagemakerNotebook.tsx
src/js/engagement_view/src/modules/GraphViz/graph/mergeGraphs.tsx
src/js/engagement_view/src/modules/GraphViz/graphQL/expandScope.tsx
src/js/graphql_endpoint/modules/schema.js
src/js/graphql_endpoint/server.js
src/js/grapl-cdk/lib/engagement.ts

Changed `graphql` endpoints in `server.js` to accommodate needs for local development + API gateway.
Locally + Manually.

Internal 126 lens failing

---

src/js/graphql_endpoint/server.js

Change endpoint in server js to remove `{proxy+}`, using `/graphQlEndpoint/graphql`. 
We are calling the wrong endpoint in AWS. 
Locally & Manually

save the server.js change

---

src/rust/Cargo.lock
src/rust/metric-forwarder/Cargo.toml

blocks andrea's thing unfortunately

fix cargo audit

---

src/js/graphql_endpoint/modules/schema.js
src/js/graphql_endpoint/server.js

No changes, additional debugging in AWS - tested manually & locally.

additional debugging

---

src/js/graphql_endpoint/modules/schema.js

Internal-126
Handle condition for nodes with no risk score. 
Tested manually + locally

handle nodes without risks

---

dobi.yaml
etc/Grapl Provision.ipynb
src/python/grapl-notebook/Demo_Engagement.ipynb
src/python/grapl-notebook/Dockerfile
src/python/grapl-notebook/tests.Dockerfile

https://github.com/grapl-security/grapl/issues/398
- add mypy checks to demo engagement.ipynb and grapl provision.ipynb
- change those files a bit to make them typecheck compliant
`nbqa` is the magic tool that lets you run regular python tooling against ipynb, its really cool
its all testing dude

Add typechecking/CI to both of our Jupyter notebooks to ensure they don't break in future

---

dobi.yaml
src/python/engagement_edge/Dockerfile
src/python/engagement_edge/src/engagement_edge.py
src/python/engagement_edge/src/lib/sagemaker.py
src/python/engagement_edge/tests.Dockerfile
src/python/engagement_edge/tests/test_engagement_edge.py
src/python/grapl-tests-common/grapl_tests_common/clients/engagement_edge_client.py
src/python/grapl_e2e_tests/tests.py

https://github.com/grapl-security/issue-tracker/issues/117
make andrea's life easier when testing locally
previously this would just fail if you were local
now we just send you to :8888
i should write an integration-env test with jwt stuff; in the mean time i wrote a unit test

Engagement Edge getNotebook actually returns something when IS_LOCAL; added integration test

---

src/rust/generators/graph-generator-lib/src/local.rs
src/rust/generators/graph-generator-lib/src/serialization.rs
src/rust/generators/sysmon-subgraph-generator/src/main.rs
src/rust/sqs-lambda/src/local_sqs_service.rs
src/rust/sqs-lambda/src/sqs_consumer.rs

None, this is a hotfix related to the sqs metrics issue.
Some sanity checks and default-sane behavior improvements in sqs-lambda around how it processes data.
Locally, since this is fixing a bug only present in localgrapl.

Fix issues around consumer policy

---

src/js/grapl-cdk/deploy_all.sh

https://github.com/grapl-security/issue-tracker/issues/25
deploy_all now respects a PROFILE= arg.
I tested it with
no PROFILE
PROFILE=default
PROFILE=abcde (didnt exist) 
worked as expected.

deploy_all now supports specifying CDK profile

---

etc/local_grapl/bin/upload-osquery-logs.py
etc/local_grapl/bin/upload-sysmon-logs.py

https://grapl-internal.slack.com/archives/C0176MS6LBY/p1611021238033700
Minor fixes to these scripts to get them serviceable
actually ran the scripts this time

Fix upload logs scripts

---

.github/CODEOWNERS

See
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
for further information.
(I've started it off with code that I personally care about, but
others can claim code as they choose.)

[Chore] Add a CODEOWNERS file

---

.github/CODEOWNERS
EDITOR_SETUP.md

Since this is a complex project with lots of moving parts, it would be nice to document how a contributor could get their editor or IDE set up in the most useful and efficient manner.
This isn't complete yet, but it gives us a place to gather such information.

Begin to document editor / IDE configurations

---

dobi.yaml
docker-compose.yml
etc/local_grapl/bin/upload-osquery-logs.py
etc/local_grapl/bin/upload-sysmon-logs.py
src/python/grapl-common/grapl_common/env_helpers.py

Fixes this bug: https://grapl-internal.slack.com/archives/C0176MS6LBY/p1611585771021500

Upload sysmon logs: actually works now, I tested it

---

Makefile

Discussion:
https://grapl-internal.slack.com/archives/C017DKYF55H/p1611788828079600
Make `make down`/stop aware of more services
CI! and locally.

Add docker-compose files to make down/stop; add remove-orphans as well

---

docker-compose.yml
src/js/engagement_view/Dockerfile
src/js/engagement_view/upload_local.sh
src/python/analyzer_executor/src/analyzer_executor_lib/analyzer_executor.py
test/cypress.json
test/cypress/integration/sample_spec.js
test/docker-compose.integration-tests.yml

For some reason the cypress container cannot resolve `nginx:1234` and i cannto figure out why
easy way to debug: change that container to
entrypoint: /bin/bash
command: ""

Sqs fargate final touches -  cypress broken but whyyy

---

Makefile
docker-compose.yml
src/rust/graph-merger/src/main.rs

https://github.com/grapl-security/grapl/pull/538 jgrillo already approved most of this; branches just got screwed up and it auto-closed the PR. 
Functionally, nothing. Just reduces reused variables in docker-compose.
CI

Reduce duplicated variables in docker-compose.yml

---

docker-compose.yml
src/python/engagement-creator/src/engagement-creator.py
src/python/engagement_edge/src/engagement_edge.py
src/python/grapl-common/grapl_common/env_helpers.py
src/python/grapl-common/grapl_common/grapl_logger.py
src/python/grapl-model-plugin-deployer/requirements.txt
src/python/grapl-model-plugin-deployer/src/grapl_model_plugin_deployer.py
src/python/grapl_analyzerlib/grapl_analyzerlib/schema.py
src/python/grapl_analyzerlib/grapl_analyzerlib/viewable.py
src/python/grapl_provision/grapl_provision.py
src/python/grapl_provision/provision_local_identity_table.py

none
Replace a bunch of manually defined loggers with `grapl_logger`.
Replace a bunch of copy pasted boto3 clients with our Client/ResourceFactory stuff.
Remove some things that made no sense (ever wonder why random code mentioned 'Initializing Chalice Server'?)
CI

Reduce duplicated code in Python codebase - primarily with env_helpers, grapl_logger

---

src/js/grapl-cdk/lib/fargate_service.ts

None
Previously these were all autogenerated garbage; this is perhaps overly verbose but much nicer.
see that above image? :')

Okay, fargate [cluster, tasks, services] are all named correctly

---

.gitignore

None, quick fix
Adds `.hypothesis` and `.log` to `.gitignore`. `.hypothesis` is generated by hypothesis tests and `.log` seems to be generated by some typescript tooling.
NA

add .hypothesis and .log to .gitignore

---

Makefile
docs/index.rst
docs/queryable.md
etc/local_grapl/unique_cmd_parent/main.py
src/python/engagement-creator/src/engagement-creator.py
src/python/grapl-dgraph-ttl/app.py
src/python/grapl-tests-common/grapl_tests_common/wait.py
src/python/grapl_analyzerlib/grapl_analyzerlib/analyzer.py
src/python/grapl_analyzerlib/grapl_analyzerlib/counters.py
src/python/grapl_analyzerlib/grapl_analyzerlib/grapl_client.py
src/python/grapl_analyzerlib/grapl_analyzerlib/prelude.py
src/python/grapl_analyzerlib/grapl_analyzerlib/subgraph_view.py
src/python/grapl_analyzerlib/test_utils/strategies/asset_view_strategy.py
src/python/grapl_analyzerlib/test_utils/strategies/process_view_strategy.py
src/python/grapl_analyzerlib/tests/test_file_node.py
src/python/grapl_analyzerlib/tests/test_process_node.py
src/python/grapl_provision/grapl_provision.py

https://github.com/grapl-security/issue-tracker/issues/85
Replace most `DgraphClient` / `Local/MasterGraphClient`s in python with `GraphClient`
Not all, because theres one case (Jupyter ipynb) where we can't inject the environment variables required.
e2e tests

Replace most `DgraphClient` / `Local/MasterGraphClient`s in python with `GraphClient`

---

src/js/grapl-cdk/destroy_all.sh

This took a total of 10 minutes, so I didn't make a ticket.
This folder previously took up 38GB on my machine 😱 
Upon destroy_all.sh, also clean up assets in cdk.out
i ran the new lines locally

Minor nicety: clean up cdk.out assets upon destroy

---

src/python/engagement-creator/src/engagement-creator.py

https://github.com/grapl-security/issue-tracker/issues/229
Sets the score for a lens after calculating it
Tested locally.

Fix lens scores

---

Makefile
test/docker-compose-with-error.sh

None
At integration test time you can specify one specific target to test
locally, with TARGET= specified and also not

make test-integration lets you specify a specific target to test

---

Makefile
src/python/grapl_analyzerlib/grapl_analyzerlib/comparators.py
src/python/grapl_analyzerlib/grapl_analyzerlib/grapl_client.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/engagement.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/lens.py
src/python/grapl_analyzerlib/grapl_analyzerlib/query_gen.py
src/python/grapl_analyzerlib/grapl_analyzerlib/queryable.py
src/python/grapl_analyzerlib/grapl_analyzerlib/view_from_proto.py
src/python/grapl_analyzerlib/tests/test_engagement.py
src/python/grapl_analyzerlib/tests/test_query_gen.py

https://github.com/grapl-security/issue-tracker/issues/168
- Add a test that exercises the "get a lens with a name" codepath
- Fix up a bunch of Analyzerlib code to make queries static + use variables, reducing injection vulnerabilities
- make VarAllocator a little easier to follow
test driven development - previously failed on lens names '' and ':'

Fix up Analyzerlib querying: reduce injection vulns, able to query for special characters

---

src/js/grapl-cdk/bin/create_edge_ux_package.ts
src/js/grapl-cdk/bin/deployment_parameters.ts
src/js/grapl-cdk/bin/grapl-cdk.ts
src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/lib/services/analyzer_dispatcher.ts
src/js/grapl-cdk/lib/services/analyzer_executor.ts
src/js/grapl-cdk/lib/services/dgraph_ttl.ts
src/js/grapl-cdk/lib/services/engagement_creator.ts
src/js/grapl-cdk/lib/services/graph_merger.ts
src/js/grapl-cdk/lib/services/model_plugin_deployer.ts
src/js/grapl-cdk/lib/services/node_identifier.ts
src/js/grapl-cdk/lib/services/osquery_graph_generator.ts
src/js/grapl-cdk/lib/services/sysmon_graph_generator.ts
src/js/grapl-cdk/test/grapl-cdk.test.ts

https://github.com/grapl-security/issue-tracker/issues/318
- Deployment names need to be normalized. No caps, no unicode, just lowercase and numbers and - and _ 
- but for people with existing deployments, we do have a legacy flag
- In testing this, I decided to refactor the crap out of log levels and Deployment Parameters (because, at test time, it expects a process.env.STUFF)
added tests

Refactor log levels in CDK; introduce a Deployment Name regex

---

.github/workflows/cargo-audit.yml
.github/workflows/grapl-build.yml
.github/workflows/grapl-docs.yml
.github/workflows/grapl-lint.yml
.github/workflows/grapl-main-release.yml
.github/workflows/grapl-release.yml
BUILDING.md
CONTRIBUTING.md
docs/setup/aws.md
docs/setup/dgraph_provision.md

https://github.com/grapl-security/issue-tracker/issues/224
Renamed every reasonable 'master' I could find to 'main', our new default branch.
Merging staging into main ASAP.
this CI

Rename every master to main; migrate a few staging references over too

---

src/js/grapl-cdk/bin/deployment_parameters.ts

We don't have test coverage on this because it uses process.env, woops.
Tested it manually
None
fix `make deploy`
manually

Fix a bug in deployment parameters

---

src/python/graplctl/graplctl/cli.py
src/python/graplctl/graplctl/common.py
src/python/graplctl/graplctl/queues/commands.py
src/python/graplctl/tests/test_graplctl.py

https://github.com/grapl-security/issue-tracker/issues/331
Add an sqsclient to graplctlstate
Add tests around `queues ls` - mostly to set a good example and get the ball rolling on doing more of it
its tests

Add graplctl tests using Jesse's PR as a base

---

src/js/graphql_endpoint/modules/schema.js
src/js/graphql_endpoint/package.json
src/js/graphql_endpoint/server.js

https://github.com/grapl-security/issue-tracker/issues/287
The graphql endpoint wasn't handling predicates for dynamic nodes, so we added a control flow to ensure data for non-builtin types are reflected in the graph.
Note: I'm aware of the formatting issues and will be resolving in a separate branch. 
AWS + Locally

Internal 287 lens from dynamic nodes bug

---

.github/workflows/grapl-lint.yml
.github/workflows/grapl-release.yml
src/js/grapl-cdk/fetch_zips_by_tag.py

https://github.com/grapl-security/issue-tracker/issues/224
Remove `channel` from our tags; tags are == version now.
The previous latest-beta stuff didn't gel with the new release system described in 224.
Discussion at https://grapl-internal.slack.com/archives/C01QQKLU6F6/p1615826057008800
Unfortunately, as is usually the case with Github Actions changes around releases - we usually have to just test-in-prod.

Remove the concept of 'channel' from our releases

---

.github/workflows/grapl-build.yml
.github/workflows/grapl-docs.yml
.github/workflows/grapl-lint.yml
.github/workflows/grapl-release.yml

https://github.com/grapl-security/issue-tracker/issues/325
`releases` workflow still looked at graph descriptions; basically just copy pasted from grapl-lint instead
release workflows are nearly untestable so thats cool and fun

0.3.0 release: Remove reference to graph-descriptions; fix python version stuff

---

src/python/engagement-creator/src/engagement-creator.py

None, I just noticed it
`in_score` is wrong, we want `in_scope`
CI

engagement creator has a one-character bug around attaching things to scopes

---

docs/setup/aws.md
src/js/grapl-cdk/bin/deployment_parameters.ts

None
Since graplctl (py) ad cdk (ts) both depend on these, we're standardizing on just using env vars.
I'm doing a cdk deploy as we speak...

Remove hardcoded deployment parameters

---

src/python/analyzer_executor/src/analyzer_executor_lib/analyzer_executor.py
src/python/analyzer_executor/tests/test_cache_integration.py

None, I just found it
- Fix AE bugs where we pass a Search Strategy into a str
- which required Lots Of Other Changes
- - introduced a cache delete, only used for test cleanliness
its all about tests

Fix Analyzer Executor tests 

---

src/js/graphql_endpoint/modules/dgraph_client.ts
src/js/graphql_endpoint/modules/jwt.ts
src/js/graphql_endpoint/modules/root_query.ts
src/js/graphql_endpoint/modules/schema.ts
src/js/graphql_endpoint/server.ts
src/js/graphql_endpoint/tsconfig.json

None
- Most `console.log`s in graphql_endpoint are much more acurately `.debug`s, so I made that change.
- I slightly refactored the RootQuery so it's dynamic (more on that soon)
`make build` - typescript should catch most of these problems. And of course, I now have graphql integration tests!

Graphql endpoint: change console.log level of most things to debug/error

---

docs/setup/aws.md

I went through our AWS instructions, and tried to be a slightly dumb and malicious user, to see what I could break.
Here are my suggested updates, based on my experience.  I added a few more resources about AWS constraints, simplified the forward- and backward-reference about environmental variables, and edited accordingly.

AWS setup docs, update

---

docs/setup/aws.md

Update formatting aws.md

---

docs/setup/aws.md
etc/aws/upload_analyzer_prod.sh
src/js/grapl-cdk/bin/create_edge_ux_package.ts
src/js/grapl-cdk/bin/deployment_parameters.ts
src/js/grapl-cdk/lib/services/provisioner.ts
src/python/graplctl/graplctl/cli.py
src/python/provisioner/src/app.py

https://github.com/grapl-security/issue-tracker/issues/380
This PR normalizes `GRAPL_DEPLOYMENT_NAME` to `DEPLOYMENT_NAME` everywhere
They haven't been yet.

normalize GRAPL_DEPLOYMENT_NAME to DEPLOYMENT_NAME

---

src/js/graphql_endpoint/Dockerfile

none
change how node modules is copied in
add a `test` check for that 
ran make zip

Dockerfile fixed for graphql zip

---

src/js/graphql_endpoint/modules/dgraph_client.ts
src/js/graphql_endpoint/modules/root_query.ts
src/python/graphql_endpoint_tests/tests.py

https://github.com/grapl-security/issue-tracker/issues/357
i have no freaking clue how graphql endpoint works, adding better types has been helping me.
graphql endpoint tests

graphql endpoint: clean up some mutating functions; get stronger types

---

src/js/engagement_view/src/components/engagementView/sidebar/tables/toggleLensTable.tsx
src/js/graphql_endpoint/modules/dgraph_client.ts
src/js/graphql_endpoint/modules/root_query.ts
src/js/graphql_endpoint/server.ts
src/python/graphql_endpoint_tests/tests.py
src/python/grapl-tests-common/grapl_tests_common/clients/graphql_endpoint_client.py
src/python/grapl_e2e_tests/tests.py

None. Andrea reported a bug.
- I discovered a bug where I was setting stuff to `dgraph_type: undefined` and then we were checking *if that key existed* not its value
- added a smoke test to prevent this in the future
added tests

Fix (and test!) graphql endpoint lens_scope. Add a smoke test to e2e tests.

---

pulumi/infra/dynamodb.py

Rather than using free functions to create our DynamoDB tables, we now
represent them as subclasses of Pulumi's `pulumi_aws.dynamodb.Table`.
In addition to providing a more conventional interface, it also allows
us to add additional functionality around permission granting, which
will become important as we migrate more parts of our infrastructure
to Pulumi.

Refactor DynamoDB tables in Pulumi

---

src/js/graphql_endpoint/Dockerfile
src/js/graphql_endpoint/jest.config.js
src/js/graphql_endpoint/modules/schema_client.ts
src/js/graphql_endpoint/package-lock.json
src/js/graphql_endpoint/package.json
src/js/graphql_endpoint/tests/schema_to_graphql.test.ts
src/js/graphql_endpoint/tests/schemas_fixture.ts
test/docker-compose.unit-tests-js.yml

its hack week baby!
read the title dude....
it IS tests!!!!

Add some very basic Graphql-endpoint JS unit test framework

---

Makefile

NA
This adds sections to formatting our `make help` output and reorganizes a few targets to group them a little better with the new sections.
Also added ascii art due to peer pressure.
Just running `make help` to see the changes.

Add sections to our Makefile help output. Also ascii art.

---

src/python/analyzer_executor/src/analyzer_executor_lib/analyzer_executor.py
src/python/analyzer_executor/src/analyzer_executor_lib/redis_cache.py
src/python/analyzer_executor/src/run.py
src/python/analyzer_executor/tests/test_cache_integration.py
src/python/analyzer_executor/tests/test_default.py
src/python/grapl_analyzerlib/grapl_analyzerlib/test_utils/strategies/misc.py

none i just always  wanted to nuke this stuff
- Redis cache stuff is deduplicated into a single function
- Singleton pattern replaced with a `.from_env()`
- Tests had this singleton monkeypatch pattern; replaced with a `.from_env(environment_map)
- 
typecheck and integration tests

Analyzer Executor: deduplicate some copy-pasted code; remove singleton pattern and associated testing complexity

---

.github/workflows/grapl-build.yml
.github/workflows/grapl-lint.yml
.github/workflows/grapl-release.yml
Makefile
build-support/retry.sh

none
- add a new bash retry script to build-support
- use it in makefile with pants
I did it locally with a failing typecheck, and it worked as expected

Retry some Pants commands that usually fail in CI

---

src/js/grapl-cdk/lib/redis.ts
src/rust/grapl-config/src/lib.rs

none
ian recently changed the redis logic, but we need to prepend `redis://` to the address
good joke

Add redis:// to redis cache address

---

.github/workflows/grapl-build.yml
src/python/engagement_edge/src/engagement_edge.py
src/python/grapl-model-plugin-deployer/src/grapl_model_plugin_deployer.py

…
none, but this reported bug
https://grapl-internal.slack.com/archives/C0176MS6LBY/p1619043750131600
- Fix a lot of typechecking
- fix a lot of `respond()` calls so they actually return non-200s
CI on this PR, and checking the logs

Fix a bunch of typechecking in Model Plugin Deployer, and actually propagate-up errors as 500s

---

.gitignore
Makefile
pants.toml
src/python/analyzer_executor/tests/test_cache_integration.py
src/python/repl/BUILD

Adds an interactive ipython repl that can import from our libs :)

Added a REPL target

---

docs/setup/aws.md
src/python/grapl-common/grapl_common/utils/BUILD
src/python/grapl-common/grapl_common/utils/find_grapl_root.py
src/python/graplctl/graplctl/BUILD
src/python/graplctl/graplctl/aws/commands.py

None
Automates finding `GRAPL_ROOT` if you are currently inside the grapl source tree
Proof:
- first executed in ~/src/grapl
- then executed in ~/src/
- not pictured: also doing it in ~/src/grapl/src/python

Graplctl: add automatic grapl-root detection

---

Makefile

Add some fun emojis to makefile

---

etc/local_grapl/bin/upload-osquery-logs.py
etc/local_grapl/bin/upload-sysmon-logs.py
etc/sample_data/BUILD
pants.toml
src/python/grapl-tests-common/grapl_tests_common/upload_logs.py
src/python/grapl-tests-common/grapl_tests_common/upload_test_data.py
src/python/grapl_e2e_tests/main.py
src/python/graplctl/graplctl/upload/commands.py
src/python/graplctl/graplctl/upload/lib.py
src/python/graplctl/tests/BUILD
src/python/graplctl/tests/fake_uploads/BUILD
src/python/graplctl/tests/shared.py
src/python/graplctl/tests/test_upload.py

https://github.com/grapl-security/issue-tracker/issues/393
Adds `graplctl upload sysmon --logfile thing.txt`
i wrote test cases!!!!!

Added `graplctl upload sysmon/osquery`

---

README.md

I'm just rebasing https://github.com/grapl-security/grapl/pull/773 and adding a logo. 
- Add logo to readme
- Update RtD link in readme
- give users a one-line "oh, that's what grapl is"
- potpourri of changes (i.e. mention osquery)

Update readme to contain a logo, and the right link to Read the Docs

---

src/js/grapl-cdk/lib/fargate_service.ts
src/js/grapl-cdk/lib/service.ts
src/js/grapl-cdk/lib/service_common.ts
src/js/grapl-cdk/lib/services/dgraph_swarm_cluster.ts
src/js/grapl-cdk/lib/swarm.ts

https://github.com/grapl-security/issue-tracker/issues/427
Set log retention on lambda services, fargate services, and dgraph.
I'm doing a deploy right now

Services' log retention is 1 month. Dgraph is 1 week.

---

src/python/grapl-ux-router/src/grapl_ux_router.py

Fixes https://github.com/grapl-security/issue-tracker/issues/425

Ensure that we're using the S3ResourceFactory in the UX router

---

pulumi/infra/config.py
pulumi/infra/lambda_.py
pulumi/infra/service_shared.py

grapl-security/issue-tracker#427
Make our service log retention 1 month.
CI

Specify Pulumi lambda log retention (still needs dgraph, fargate)

---

.buildkite/pipeline.yml
.rustfmt.toml
CHORES.md
src/rust/bin/format
src/rust/derive-dynamic-node/src/lib.rs
src/rust/generators/osquery-subgraph-generator/src/parsers/grapl_pack/files.rs
src/rust/generators/osquery-subgraph-generator/src/parsers/grapl_pack/process_files.rs
src/rust/generators/osquery-subgraph-generator/src/parsers/mod.rs
src/rust/generators/sysmon-subgraph-generator/src/models/process/create.rs
src/rust/generators/sysmon-subgraph-generator/src/serialization.rs
src/rust/graph-merger/src/upserter.rs
src/rust/graph-merger/tests/test_merging.rs
src/rust/rust-toolchain
src/rust/sqs-executor/src/redis_cache.rs
src/rust/sqs-executor/src/rusoto_helpers.rs
src/rust/sysmon/src/lib.rs

https://github.com/grapl-security/issue-tracker/issues/432
Update to 1.52.1 due to a bug introduced in 1.24 that can cause code to compile improperly.
I'll let our automated tests handle this.

Update to rust 1.52.1

---

.dockerignore
docker-compose.build.yml
src/python/Dockerfile

Removes some unused Docker container definitions, as well as tightens up our root `.dockerignore` file.

Docker cleanup

---

Makefile
pulumi/infra/api.py
pulumi/infra/graphql.py

For some reason, this does not appear to work in LocalStack. As we're
moving away from LocalStack, we'll just preserve the existing
functionality we have in Local Grapl.

Add GraphQL endpoint to Pulumi

---

pulumi/__main__.py
pulumi/infra/cache.py

Not doing this in Local Grapl, as this requires Localstack Pro.

Add Elasticache to Pulumi

---

pulumi/infra/network.py
src/python/graplctl/graplctl/swarm/lib.py

None
Some things had repeated names, like "grapl-network", that show up in the Name column in ec2.
I've added deployment name there to make it easier to reason about these.
Did a pulumi up against aws

Better tagged Name stuff in Pulumi

---

src/python/grapl-dgraph-ttl/BUILD
src/python/grapl-dgraph-ttl/grapl_dgraph_ttl.py
src/python/grapl-dgraph-ttl/tests/BUILD
src/python/grapl-dgraph-ttl/tests/test_dgraph_ttl.py

Enables MyPy checking of the dgraph-ttl code, and fixes up some typing violations.

Type grapl-dgraph-ttl code

---

src/python/grapl-ux-router/BUILD
src/python/grapl-ux-router/grapl_ux_router.py

Enables MyPy checking of the ux-router code, and fixes up some typing violations.

Type ux-router code 

---

src/python/provisioner/src/BUILD
src/python/provisioner/src/app.py

Enable MyPy on provisioner lambda

---

src/python/analyzer-deployer/analyzer_deployer/BUILD
src/python/analyzer-deployer/analyzer_deployer/app.py

Enable MyPy on analyzer-deployer

---

src/python/analyzer-deployer/tests/BUILD
src/python/analyzer-deployer/tests/test_app.py

Type analyzer-deployer tests with MyPy

---

pulumi/infra/analyzer_dispatcher.py
pulumi/infra/analyzer_executor.py
pulumi/infra/fargate_service.py
pulumi/infra/graph_merger.py
pulumi/infra/node_identifier.py
pulumi/infra/osquery_generator.py
pulumi/infra/sysmon_generator.py

none
Functionally nothing.
It provides a one-true-place for all our Docker builds. 
pulumi up

Create a GraplDockerBuild in pulumi. Goal was to quiet builds, but that's currently impossible.

---

src/python/grapl-ux-router/grapl_ux_router.py

This lambda is deployed as a lambda in Local Grapl and not as a
special local-only "service", and thus does not need any
special-casing anymore.

Remove IS_LOCAL code from ux-router

---

src/python/engagement_edge/engagement_edge/engagement_edge.py
src/python/engagement_edge/engagement_edge/env_vars.py
test/docker-compose.integration-tests.yml

This lambda is deployed as a lambda in Local Grapl and not as a
special local-only "service", and thus does not need any
special-casing anymore.

Remove IS_LOCAL code from engagement_edge

---

pulumi/infra/api.py

Previously this information was only available as a stack output, but
we now have need of it within the Pulumi run, so it needs to be
exposed as a property.

Expose the API invocation URL as a property on the Api class

---

docker-compose.yml
src/python/analyzer_executor/src/analyzer_executor_lib/analyzer_executor.py
test/docker-compose.integration-tests.yml

Turns out this is no longer required!

Remove IS_LOCAL from analyzer-executor

---

pulumi/Pulumi.local-grapl.yaml
pulumi/__main__.py
pulumi/infra/alarms.py
pulumi/infra/config.py
pulumi/infra/swarm.py
src/js/grapl-cdk/lib/alarms.ts
src/python/graplctl/graplctl/dgraph/lib.py

grapl-security/issue-tracker#441
- Lots of tagging stuff with a Name that makes it easier to reason about.
- Nesting with resource options
against my pulumi aws stack with graplctl!

Provision pulumi's dgraph with graplctl. Doesn't work completely but gets up to making disk alarms.

---

docker-compose.yml
pulumi/__main__.py
src/rust/analyzer-dispatcher/src/main.rs
src/rust/generators/generic-subgraph-generator/src/main.rs
src/rust/generators/graph-generator-lib/src/lib.rs
src/rust/generators/osquery-subgraph-generator/src/main.rs
src/rust/graph-merger/src/main.rs
src/rust/graph-merger/src/service.rs
src/rust/grapl-config/src/env_helpers.rs
src/rust/grapl-config/src/lib.rs
src/rust/node-identifier/src/lib.rs
src/rust/sqs-executor/src/event_emitter.rs
src/rust/sqs-executor/src/lib.rs
src/rust/sqs-executor/src/s3_event_emitter.rs
test/docker-compose.integration-tests.yml

Does what it says on the tin 🎉

Remove is_local from Rust services

---

pulumi/.gitignore

none
Change pulumi gitignore to only allow `Pulumi.local-grapl.yaml`
git status

Change pulumi gitignore to only allow `Pulumi.local-grapl.yaml`

---

etc/local_grapl/nginx_templates/default.conf.template
src/js/graphql_endpoint/modules/query_generator.ts
src/python/grapl-tests-common/grapl_tests_common/clients/graphql_endpoint_client.py

internal-350-graplctl-aws-test
- Decrease the size of the graphql query, by removing extraneous whitespace chars (the TABBING =)
- Increase the size of nginx's large request buffers - default is 8k
- slightly more idiomatic assertion in graphql endpoint client
make test-integration TARGETS=graphql-endpoint

Fix the 414 in Jesse's PR

---

Makefile
pulumi/__main__.py

Does what it says.
Also provides a Makefile target to ensure that UX assets have been built first. Read individual commits for further details.

Upload UX assets in Pulumi run

---

pulumi/infra/bucket.py
pulumi/infra/emitter.py

Just some cleanup and consolidation of bucket-related code. Check the individual commits for further details.

A bit of Pulumi bucket consolidation

---

pulumi/__main__.py
pulumi/infra/bucket.py
pulumi/infra/dgraph_cluster.py
pulumi/infra/ec2.py
pulumi/infra/provision_lambda.py
pulumi/infra/swarm.py

none
Steal two useful fixes/refactors from #800
colin said s3 behavior was better after this

Copy over colin's S3 fix; pull Ec2port out to its own file

---

pulumi/__main__.py
pulumi/infra/bucket.py

throw exception if pulumi prep is needed

---

pulumi/infra/queue_policy.py
pulumi/infra/service_queue.py

We needed to tweak the policies of this queue to allow SendMessage from SNS

Fix SNS/SQS policy stuff to allow for S3 -> SNS -> SQS

---

pulumi/infra/dgraph_ttl.py
pulumi/infra/engagement_edge.py
pulumi/infra/graphql.py
pulumi/infra/model_plugin_deployer.py
pulumi/infra/ux_router.py
src/python/engagement_edge/engagement_edge/engagement_edge.py

These changes open port 443 on the lambdas s.t. they can talk to AWS services, and set 5s connect and read timeouts in the engagement-edge lambda.
sandbox account in AWS

Internal 576 fix e2e tests

---

pulumi/infra/pipeline_dashboard.py

Cloudwatch Pipeline dashboard now displays sum(MsgsVisible, MsgsNotVisible)

---

src/rust/Cargo.lock
src/rust/node-identifier/Cargo.toml
src/rust/node-identifier/src/dynamic_sessiondb.rs
src/rust/node-identifier/src/lib.rs
src/rust/node-identifier/src/sessiondb.rs
src/rust/sqs-executor/src/lib.rs
src/rust/sqs-executor/src/retriever/s3_event_retriever.rs

This moves the node-identifier to tracing entirely, and adds a bit more context to spans.

Fix up some logging

---

pulumi/infra/pipeline_dashboard.py

apparently it doesn't like capital labels

okay i fixed the pipeline dashboard lol

---

pulumi/infra/api.py
pulumi/infra/graphql.py

grant access to schema_properties_table and schema_table
NA

grant graphql endpoint access to dynamodb tables

---

src/python/graplctl/graplctl/aws/commands.py
src/python/graplctl/graplctl/aws/lib.py
src/python/graplctl/graplctl/cli.py
src/python/graplctl/graplctl/common.py
src/python/graplctl/graplctl/dgraph/commands.py
src/python/graplctl/graplctl/upload/commands.py

None.
Adds a new graplctl command to wipe state from an aws grapl deployment.
Useful for re-testing things e2e tests without doing a brand new deployment.
I haven't been able to fully test _that_ yet, but I have been able to confirm that this does in fact delete everything in the 3 specified tables.
```
this will wipe your grapl state. realistically, only for devs. that okay? [y/N]: y
really wanna make sure, this will wipe your dgraph and dynamodb [y/N]: y
Wiping dynamodb
Wiping dynamodb.Table(name='jun10-dynamic_session_table')
INFO:graplctl.aws.lib:Wiping dynamodb.Table(name='jun10-dynamic_session_table')
Wiped dynamodb.Table(name='jun10-dynamic_session_table')
INFO:graplctl.aws.lib:Wiped dynamodb.Table(name='jun10-dynamic_session_table')
Wiping …
```

graplctl aws wipe-state: clears out the 3 useful dynamodb tables + deletes your dgraph cluster

---

pulumi/infra/pipeline_dashboard.py

Pipeline dashboard has a new section for messages-processed

---

src/python/e2e-test-runner/e2e_test_runner/main.py
src/python/grapl-common/grapl_common/grapl_logger.py
src/python/grapl-tests-common/grapl_tests_common/setup_tests.py

some updates to make the e2e-test-runner work, fix some logging issues, make `graplctl aws test` exit 0 upon success
`graplctl aws test`, `make test-e2e`

Internal 576 fix graphql test client

---

docker-compose.yml
local-grapl.env
src/rust/kafka-metrics-exporter/tests/integration_tests.rs

https://github.com/grapl-security/issue-tracker/issues/561
This PR cleans up the kafka configs we have in `docker-compose.yml`
`make test-e2e` and grepping the broker logs to check that the `test-topic` was created.

clean up local kafka configs

---

pants.toml

Updates Toolchain plugin to 0.13.0, too.

Update Pants to 2.5.1rc3

---

Dockerfile.pulumi

Update Pulumi to 3.5.1

---

docker-compose.yml
src/js/engagement_view/upload_local.sh
src/js/engagement_view/upload_localhost.sh

I slightly screwed this up in https://github.com/grapl-security/grapl/pull/944
Potential relation to https://github.com/grapl-security/issue-tracker/issues/425
make engagement-view-uploader work again, and prevent non-0 exit codes in the future
make up

Fix engagement-view-uploader

---

docker-compose.yml
src/python/e2e-test-runner/e2e_test_runner/BUILD
src/python/e2e-test-runner/e2e_test_runner/test_engagement_view_reachable.py

https://github.com/grapl-security/issue-tracker/issues/425
- bump localstack to `latest`, which is the only available image that has my fix right now.
- add a smoke test
added a test

engagement ux works locally again

---

pulumi/infra/e2e_test_runner.py
src/python/e2e-test-runner/e2e_test_runner/test_engagement_view_reachable.py
src/python/grapl-common/grapl_common/dev_assertions.py
src/python/grapl-common/grapl_common/utils/primitive_convertors.py
src/python/grapl-model-plugin-deployer/grapl_model_plugin_deployer.py
src/python/grapl-tests-common/grapl_tests_common/clients/common.py
test/docker-compose.e2e-tests.yml

None
I recently introduced an IS_LOCAL into the e2e tests. 
Now, as it turns out, didn't even need that! 
BUT!It turns out that all our bool(os.environment) stuff is completely wrong, so this fixes that.
against aws!!

Fix e2e tests in aws

---

.buildkite/pipeline.verify.yml
Makefile
docs/setup/aws.md

Removes some unused targets, and cleans up the lambda-related targets.

Update the Makefile

---

.buildkite/pipeline.merge.yml

Wait between RC creation and tagging a successful run

---

docker-compose.yml

Stab in the dark at https://github.com/grapl-security/issue-tracker/issues/617

Re-Pin Localstack

---

pulumi/README.md

Add additional documentation around Pulumi projects and stacks

---

.buildkite/pipeline.merge.yml

i'm not going to give this PR the honor of a well thought out description

Fix pipeline merge yaml which was missing a "

---

.buildkite/pipeline.merge.yml

Discussion here:
https://grapl-internal.slack.com/archives/C017DKYF55H/p1626206029401800

Missing wait in merge pipeline added in

---

.buildkite/pipeline.merge.yml
.buildkite/pipeline.verify.yml
src/js/bin/format.sh

Lack of this caused https://github.com/grapl-security/grapl/pull/1000
Lint/format more files
i screwed up a buildkite yaml and it correctly detected it with this change

Yaml lint `.buildkite, .github` files

---

.buildkite/pipeline.merge.yml

Partially addressing https://github.com/grapl-security/issue-tracker/issues/618.

Use new "rc" queue to create release candidates

---

.buildkite/shared/lib/json_tools.sh
.buildkite/shared/lib/rc.sh
.buildkite/shared/lib/rc_test.sh
.buildkite/shared/pants.toml

pull in `json_tools` so i can use it in https://github.com/grapl-security/grapl/pull/1011

Update buildkite-common for grapl

---

pulumi/bin/BUILD
pulumi/bin/copy_artifacts_from_rc.sh
pulumi/bin/subset_of_artifacts.jq

Copy artifacts from origin/rc to your local pulumi config

---

.buildkite/pipeline.merge.yml

This is just to unblock the pipeline, pending a few upcoming fixes.

Temporarily stop building UX artifacts

---

.buildkite/scripts/tests_in_ci/packer_integration_test.sh
packer/nomad-server-client/configs/osquery-config/osquery.conf
packer/nomad-server-client/image.pkr.hcl
packer/nomad-server-client/osquery-config/osquery.conf
packer/nomad-server-client/setup_osquery.sh
packer/nomad-server-client/setup_vector.sh

https://github.com/grapl-security/issue-tracker/issues/604
Add `osquery` and a dummy-config-ready-to-be-edited to our AMIs. 
wishful thinking

Install OSQuery in our AMIs

---

pulumi/grapl/Pulumi.local-grapl.yaml
pulumi/grapl/Pulumi.testing.yaml
pulumi/grapl/__main__.py
pulumi/infra/config.py

This is to get the provisioning pipeline flowing.

Fix up some environment variables for a CI deploy

---

src/python/e2e-test-runner/e2e_test_runner/conftest.py
src/python/e2e-test-runner/e2e_test_runner/test_engagement_edge.py
src/python/e2e-test-runner/e2e_test_runner/test_main.py
src/python/e2e-test-runner/e2e_test_runner/test_model_plugin_deployer.py

https://github.com/grapl-security/issue-tracker/issues/395
- Make everything use `jwt` fixture
- Add some logic to the `upload plugin node` test to make sure that `graphql` picks up newly uploaded plugin nodes
make test-e2e

Test to check graphql schema contains uploaded plugin node

---

docker-compose.yml
pulumi/infra/api.py
pulumi/infra/model_plugin_deployer.py
src/python/grapl-model-plugin-deployer/grapl_model_plugin_deployer.py

Same principle as https://github.com/grapl-security/grapl/pull/1044

Pass bucket to model-plugin-deployer directly

---

docker-compose.yml
pulumi/grapl/__main__.py
src/js/engagement_view/Dockerfile
src/js/engagement_view/upload_local.sh

Pass ux-bucket directly to upload_local.sh script

---

src/python/e2e-test-runner/e2e_test_runner/test_model_plugin_deployer.py

https://github.com/grapl-security/issue-tracker/issues/625
Disable a test that has been failing, possibly due to a race condition
CI here and now

xfail the Model Plugin Deployer e2e test

---

docker-compose.yml
src/aws-provision/dgraph/dgraph_deploy.sh
src/aws-provision/dgraph/docker-compose-dgraph.yml

None.
Update dgraph to latest stable.
(Why? Doesn't hurt to do, and I'm kind of in "try every damn thing possible to fix that dgraph alter issue" mode)
Ran e2e locally and it succeeded; also will fire off an aws one

Upgrade Dgraph to 21.03.1

---

BUILDING.md
CONTRIBUTING.md
README.md
docs/setup/index.rst

None, but it became clear due to https://github.com/grapl-security/grapl/pull/1071 that we need to make this more obvious!
- Remove a big chunk of CONTRIBUTING.md that's kind of useless
- Direct all of our setup documentation to docs/setup on RtD
- Write a short blurb in docs/setup/index.rst that we don't support local right now.
make build-docs

Make clearer in our documentation that Local Grapl is not supported

---

Makefile

This reverts commit e341b92c11a3939d998aad5f64dd7fe4ce075947.
Context: https://grapl-internal.slack.com/archives/C017DKYF55H/p1628128732092100?thread_ts=1628101703.057700&cid=C017DKYF55H

Revert "Simplify makefile (#1086)"

---

.buildkite/pipeline.verify.yml
.buildkite/scripts/e2e.sh
.buildkite/scripts/integration.sh

Just an assortment of minor tweaks to our Buildkite pipeline.

Buildkite tweaks

---

src/python/graplctl/graplctl/aws/lib.py

Always print logs when executing tests by graplctl

---

pulumi/infra/service_queue.py

Use correct SID format

---

.buildkite/scripts/e2e_in_aws.sh

Sleep for a bit longer in e2e-in-AWS tests

---

src/python/engagement_edge/engagement_edge/engagement_edge.py
src/python/engagement_edge/tests/BUILD
src/python/engagement_edge/tests/test_engagement_edge.py

https://github.com/grapl-security/issue-tracker/issues/244
Resurrect an old test that was removed due to Pantsification (and add a similar test). 
more. testing. more. testing.
CI

Fix an old issue around engagement-edge testing.

---

.github/CODEOWNERS

NA
This PR tags the @grapl-security/wg-data-infra working group on the relevant parts of the codebase.
NA

tag @wg-data-infra on relevant code

---

.buildkite/pipeline.testing.yml

Automatically retry e2e tests in AWS

---

3rdparty/python/requirements.txt

#1132 
Just reorganizes an existing file. No actual code changes
N/A

Organize requirements.txt alphabetically into one list

---

BUILDING.md
nomad/local/start_development_environment.sh

https://github.com/grapl-security/issue-tracker/issues/652
1. Add a section for running Nomad locally
2. Overhaul the CI section to reflect the move to BuildKite
3. Minor documentation updates to BUILDING.md
4. Add dependency checks to nomad/start_development_environment.sh
The nomad and consul checks were tested prior to installing nomad and consul and then afterward.
The Nomad documentation was updated as I went through step by step to get Nomad to run grapl locally. They were originally based on the testing instructions in https://github.com/grapl-security/grapl/pull/1059

Overhaul BUILDING.md and add section on using Nomad locally

---

etc/ci_scripts/dump_artifacts/nomad_artifacts.py
nomad/local/integration-tests.nomad
nomad/local/nomad_cli_tools.sh
nomad/local/run_integration_tests.sh
pulumi/grapl/Pulumi.local-grapl.yaml
pulumi/grapl/__main__.py
pulumi/infra/config.py
src/rust/Dockerfile
src/rust/kafka-metrics-exporter/src/lib.rs
src/rust/kafka-metrics-exporter/tests/integration_tests.rs

grapl-security/issue-tracker#659

Make the Nomad rust integ tests actually talk kafka

---

nomad/grapl-core.nomad
pulumi/grapl/__main__.py

Added sysmon and osquery generators to nomad.
`make up-detach` spawned the tasks properly and logs show that the generators are ready for work!

Sysmon and OSQuery generators

---

docs/development/ratel.md
nomad/grapl-core.nomad

Please ensure that my exposing-8080-to-host-OS is security-acceptable.

Enable ratel in local grapl, add instructions.

---

.buildkite/scripts/build_and_upload_containers.sh
Makefile
pants.toml

NA
This PR makes some changes to the Makefile and the buildkite tooling to try to fix the merge pipeline. It's currently broken due to a missing link in the Makefile dependency graph.
They will be once this PR is merged 🤣

remove some unused makefile targets, try to make the merge pipeline work

---

Makefile
docker-compose.yml
nomad/local/.gitignore
nomad/local/integration-tests.nomad
nomad/local/start_detach.sh
pulumi/grapl/__main__.py
src/python/Dockerfile
test/docker-compose.integration-tests.build.yml

This will be merged into the (otherwise hard-to-review, because it's mostly just a revert) https://github.com/grapl-security/grapl/pull/1195
which will be merged into Nomad
which will be merged into Main

Nomad py integration tests dockerized

---

.buildkite/pipeline.merge.yml
.buildkite/pipeline.provision.yml
.buildkite/pipeline.testing.yml
.buildkite/pipeline.verify.yml

Use Vault to retrieve CI/CD secrets

---

.buildkite/pipeline.provision.yml
.buildkite/pipeline.verify.yml

Update Pulumi Buildkite plugin to v0.1.1

---

.buildkite/pipeline.provision.yml
.buildkite/pipeline.verify.yml

upgrade to https://github.com/grapl-security/pulumi-buildkite-plugin/pull/8
unblocks https://github.com/grapl-security/grapl/pull/1241

Use new version of pulumi buildkite plugin, which now supports --refresh

---

pulumi/infra/api_gateway.py

add an f to an fstring

---

.buildkite/scripts/build_and_upload_containers.sh

very simple PR that changes a build from
docker buildx bake img1
docker buildx bake img2
docker buildx bake img3
to
docker buildx bake img1 img2 img3

grapl merge pipeline will build images in parallel

---

.buildkite/pipeline.merge.yml
.buildkite/pipeline.provision.yml
.buildkite/pipeline.verify.yml

Moving us steadily away from copy/pasted code!

Use Grapl Release Buildkite plugin for several operations

---

pulumi/infra/bucket.py

Use `pulumi.ResourceOptions` consistently

---

.buildkite/pipeline.verify.yml
.buildkite/scripts/ensure_regenerated_constraints.sh

I see people miss this step relatively commonly, so I cooked up a quick Buildkite script to detect this case.

Buildkite step to detect "updated requirements.txt but not constraints.txt"

---

.buildkite/scripts/grapl_testing_stack/destroy_stateful_resources.sh

For reasons I'm not quite sure of myself, 
https://github.com/grapl-security/grapl/pull/1329
failed. After 1 failed destroy it bailed out. Don't know why.
This is a second attempt. I hate bash.

Attempt 2 at stateful destroy stuff piece-by-piece

---

.buildkite/pipeline.merge.yml

Bump grapl-rc plugin to v0.1.3

---

.buildkite/scripts/build_and_upload_containers.sh
docker-compose.build.yml

728
Introduces the plugin-work-queue image ahead of  https://github.com/grapl-security/grapl/pull/1325
Tests are in https://github.com/grapl-security/grapl/pull/1325

Introduce the plugin-work-queue image

---

.buildkite/pipeline.provision.yml

https://github.com/grapl-security/issue-tracker/issues/835
This moves the preview integration-test until after we pulumi up the grapl project.
We're moving this instead of temporarily skipping the step, because we're going to run into similar problems in the future

Move the preview integration-test step after the grapl project has been run

---

src/python/graplctl/graplctl/aws/lib.py
src/python/graplctl/graplctl/common.py
src/rust/analyzer-dispatcher/src/dispatch_event.rs
src/rust/bin/format
src/rust/derive-dynamic-node/examples/ex.rs
src/rust/graph-merger/src/main.rs
src/rust/graph-merger/src/service.rs
src/rust/grapl-web-ui/src/authn/user.rs
src/rust/node-identifier/src/dynamic_sessiondb.rs
src/rust/node-identifier/src/lib.rs
src/rust/rust-toolchain.toml

Update Rust Version

---

src/rust/plugin-registry/src/nomad/client.rs
src/rust/plugin-registry/src/server/deploy_plugin.rs
src/rust/plugin-registry/tests/test_nomad_client.rs

Another followup on https://github.com/grapl-security/issue-tracker/issues/722

DeployPlugin test - what if namespace already exists?

---

.buildkite/pipeline.merge.yml
.buildkite/pipeline.provision.yml

Update grapl-security/cloudsmith Buildkite plugin version to v0.1.4
---

Update Buildkite Plugin

---

etc/chromeos/lib/installs.sh

Just to standardize on one tool.

Replace `wget` usage with `curl`

---

etc/chromeos/lib/installs.sh
etc/chromeos/setup_chromeos.sh

Found this miss during a recent chromeos setup

Install tree during setup_chromeos

---

.buildkite/pipeline.verify.yml

Use TLS for curl invocation to validate codecov.yml

---

.buildkite/pipeline.deploy.yml
.buildkite/pipeline.merge.promote.yml
.buildkite/pipeline.merge.yml
.buildkite/pipeline.provision.yml
.buildkite/pipeline.testing.yml
.buildkite/pipeline.verify.yml

Update grapl-security/vault-login Buildkite plugin version to v0.1.2
---

Update grapl-security/vault-login Buildkite Plugin to v0.1.2

---

.buildkite/pipeline.npm-audit.sh
.buildkite/pipeline.verify.yml
.buildkite/pipeline.yarn-audit.sh
.buildkite/pipeline.yarn-npm-audit.sh

https://github.com/grapl-security/issue-tracker/issues/817
Add audit capabilities for js/ts.
This adds two pipelines one which runs npm audit, the other runs yarn audit.
Resurrecting this branch now that compliance is finished.
https://buildkite.com/grapl/grapl-yarn-audit
https://buildkite.com/grapl/grapl-npm-audit
The results should match up roughly with the dependabot alerts: https://github.com/grapl-security/grapl/security/dependabot?page=2&q=is%3Aopen

Nodejs audit

---

.buildkite/pipeline.verify.yml

Update grapl-security/codecov Buildkite plugin version to v0.1.3
---

Update grapl-security/codecov Buildkite Plugin to v0.1.3

---

.buildkite/pipeline.merge.yml

Update grapl-security/grapl-rc Buildkite plugin version to v0.1.6
---

Update grapl-security/grapl-rc Buildkite Plugin to v0.1.6

---

nomad/e2e-tests.nomad
nomad/grapl-provision.nomad
nomad/local/integration-tests.nomad
pulumi/grapl/__main__.py
pulumi/infra/secret.py
pulumi/integration_tests/__main__.py
src/python/graphql_endpoint_tests/BUILD
src/python/grapl-common/grapl_common/test_user_creds.py
src/python/grapl-tests-common/grapl_tests_common/clients/grapl_web_client.py
src/python/provisioner/provisioner/app.py

Eliminate some of the last places that consume STACK_NAME. Instead, pass in the TestUserPassword secretid verbatim.
https://github.com/grapl-security/issue-tracker/issues/865

Less stackname interpolation

---

docker-compose.check.yml

Update bufbuild/buf container image to 1.1.0

---

.buildkite/pipeline.verify.yml
pants.toml
src/python/grapl_analyzerlib/tests/test_file_node.py
src/python/grapl_analyzerlib/tests/test_process_node.py
src/rust/bin/BUILD

This makes sure that any new files are properly covered by Pants.

Add `pants tailor --check` to CI runs

---

pulumi/grapl/__main__.py

Change Parameter group naming to use _ instead of -
N/A

change org management to use - instead of _

---

nomad/local/grapl-local-infra.nomad
nomad/local/nomad_run_local_infra.sh

This is a bit of a grab-bag of cleanups I saw for our local Nomad file in the course of consolidating our "Local Grapl" / "AWS Grapl" split (to the extent that's possible).
Reviewing commit-by-commit is the best way to go here.

Assorted local Nomad cleanups

---

.buildkite/pipeline.verify.yml
src/rust/Makefile
src/rust/bin/run_in_container.sh

Run Clippy in a container

---

src/rust/Cargo.lock
src/rust/grapl-web-ui/Cargo.toml
src/rust/grapl-web-ui/src/authn/dynamodb.rs
src/rust/grapl-web-ui/src/authn/user.rs
src/rust/grapl-web-ui/src/config.rs
src/rust/grapl-web-ui/src/main.rs
src/rust/grapl-web-ui/src/routes/login.rs

This improves upon error messages and handling of them in the grapl-web-ui project.
- Intentionally triggered some errors locally and observed the effects.
- CI tests to ensure things didn't break

Improve error handling and messaging in grapl-web-ui

---

.buildkite/pipeline.verify.yml

Update grapl-security/codecov Buildkite plugin version to v0.1.4
---

Update Codecov Buildkite Plugin to v0.1.4

---

.buildkite/pipeline.provision.yml

Update grapl-security/pulumi Buildkite plugin version to v0.1.3
This picks up improved logging
---

Update grapl-security/pulumi Buildkite Plugin to v0.1.3

---

firecracker/kernel/build.sh
firecracker/rootfs/scripts/create_rootfs_image.sh
pulumi/infra/firecracker_assets.py
pulumi/infra/s3_url.py
src/rust/grapl-config/src/env_helpers.rs
src/rust/plugin-registry/src/server/deploy_plugin.rs
src/rust/plugin-registry/src/server/mod.rs
src/rust/plugin-registry/src/server/s3_url.rs
src/rust/plugin-registry/src/static_files/plugin.nomad

there's a lot of changes I made (especially re: .gz and filenames) that I changed tack on later.
---
https://github.com/grapl-security/issue-tracker/issues/891
Fix up how we do artifacts in plugin.nomad.
Now we get up to Firecracker failing due to CNI networking - the error described in https://github.com/grapl-security/issue-tracker/issues/890 - but fixing that is *not* covered in this PR.

Get the artifacts in plugin.nomad closer to actually working

---

nomad/local/nomad_run_local_infra.sh

This is just a dev loop niceness upgrade - instead of deploying these two jobs serially, we deploy them in parallel and then monitor their success serially. 
After 3 runs, averages of `make down && time make start-nomad-detach`
Before: 1m1s
After: 43s

Nomad Local Infra - deploy grapl-local-infra and observability simultaneously - saves 18s for make up 

---

localstack/Dockerfile
nomad/local/grapl-local-infra.nomad

Doesn't hurt to upgrade.
Also, I finally made a ticket against localstack for the previously-exposed elasticmq issue:
https://github.com/localstack/localstack/issues/5821

Upgrade Localstack from 0.12.15 to 0.14.2

---

.buildkite/pipeline.merge.promote.yml
.buildkite/pipeline.merge.yml
.buildkite/pipeline.provision.yml

Update artifacts Buildkite plugin version to v1.5.0
---

Update artifacts Buildkite Plugin to v1.5.0

---

.buildkite/pipeline.verify.yml

Update docker Buildkite plugin version to v3.12.0
---

Update docker Buildkite Plugin to v3.12.0

---

devbox/README.md
devbox/provision/provision.sh

add lots of flavor to devbox/README.md so people know how to set it up and use it

devbox readme so people know how to actually use it

---

.gitattributes
src/js/engagement_view/Makefile
src/js/engagement_view/yarn.lock

I found `yarn build` was changing my yarn.lock - gross.

Prevent `yarn.lock` from mutating when we `yarn build`

---

devbox/provision/provision.sh

Previously:
```
wimax@penguin:~/src/repos/grapl$ time ./devbox/devbox-do.sh ls
0   0%    0.00kB/s    0:00:00 (xfr#0, to-chk=0/1691)
Devbox sync complete
3rdparty     CODE_OF_CONDUCT.md  LICENSE               bin            debugger         docker-compose.check.yml  firecracker  pants-plugins  pulumi          test_artifacts
BUILD        CONTRIBUTING.md     LOCAL_UI_WORKFLOW.md  buf.yaml       devbox           docker-compose.yml        localstack   pants.ci.toml  pyproject.toml
BUILDING.md  Dockerfile.pulumi   Makefile              build-support  dist             docs                      nomad        pants.toml     src
CHORES.md    EDITOR_SETUP.md     README.md             codecov.yml    docker-bake.hcl  etc                       pants        postgres       test
Connection to …
```

Improve devbox-do speed from 4.8s to 1s by reusing SSH connections

---

src/js/engagement_view/src/components/analyzers/analyzers.tsx
src/js/engagement_view/src/components/engagementView/EngagementView.tsx
src/js/engagement_view/src/components/engagementView/sidebar/tables/nodeTable/NodeTable.tsx
src/js/engagement_view/src/components/engagementView/sidebar/tables/nodeTable/nodeTableHeader.tsx
src/js/engagement_view/src/components/generators/generators.tsx
src/js/engagement_view/src/components/graphDisplay/GraphDisplay.tsx
src/js/engagement_view/src/components/graphDisplay/GraphDisplayStyles.tsx
src/js/engagement_view/src/components/graphDisplay/graphVizualization/graphColors.tsx
src/js/engagement_view/src/components/graphDisplay/graphVizualization/nodeColoring.tsx
src/js/engagement_view/src/components/reusableComponents/collapsibleDrawer.tsx
src/js/engagement_view/src/components/reusableComponents/drawer.tsx
src/js/engagement_view/src/components/styles/analyzersAndGeneratorsStyles.tsx
src/js/engagement_view/src/tests/engagementView/testData/mergeGraphData.tsx
src/js/engagement_view/src/tests/graphDisplay.test.tsx
src/js/engagement_view/src/tests/linkCalcs.test.tsx
src/js/engagement_view/src/theme.tsx

https://github.com/grapl-security/issue-tracker/issues/903
Address UI concerns 
Manually - these are mostly styling changes.

UI styling fixes

---

devbox/forward_common_ports.sh

forward_common_ports won't open an interactive bash session

---

Makefile
docker-bake.hcl

NA
Adds `"rust-integration-tests-new"` to the `"cloudsmith-images"` group s.t. the testing image gets uploaded to Cloudsmith.

add rust-integration-tests-new to cloudsmith-images

---

.github/CODEOWNERS
docker-bake.hcl
src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/Dockerfile
src/rust/consul-connect/src/resolver.rs
src/rust/plugin-executor/Cargo.toml
src/rust/plugin-executor/README.md
src/rust/plugin-executor/analyzer-executor.rs
src/rust/plugin-executor/generator-executor.rs
src/rust/plugin-executor/src/lib.rs
src/rust/plugin-executor/src/upstreams.rs
src/rust/plugin-registry/src/client.rs
src/rust/plugin-sdk/generator-sdk/src/client.rs
src/rust/plugin-sdk/generator-sdk/src/client_config.rs
src/rust/plugin-sdk/generator-sdk/src/lib.rs
src/rust/plugin-work-queue/src/client.rs

Satisfies the first 2 checkboxes of 
https://github.com/grapl-security/issue-tracker/issues/733
https://app.zenhub.com/workspaces/grapl-6036cbd36bacff000ef314f2/issues/grapl-security/issue-tracker/733
My next steps are to do a couple of the blockers on this. 
(If it seems like I've been doing things out-of-order: I have been!) 
Implement the Graph Generator Executor as described in the Plugins RFC.
https://github.com/grapl-security/grapl-rfcs/blob/main/text/0000-plugins.md#-executor-apis-graph-generator-executor-analyzer-executor
Still has quite a bit TODO.
So, here's the thing - this service is basically a one-file glue service. I'm not convinced it's worth unit testing, though I absolutely am obviously convinced it's worth integration testing.
However! 
As we've seen from previously …

Generator executor

---

devbox/provision/provision.sh

Yeah, idk how I didn't catch this earlier. Never bothered messing with the defaults.

Fix defaults in devbox provision

---

.buildkite/pipeline.verify.yml
src/rust/bin/format
src/rust/grapl-graphql-codegen/src/field_type.rs
src/rust/rust-toolchain.toml

Update Rust to 1.61.0

---

.github/ISSUE_TEMPLATE/bug_report.md
BUILDING.md
CONTRIBUTING.md
Makefile
docs/development/integration_tests.rst
etc/chromeos/lib/installs.sh
etc/ci_scripts/dump_artifacts/cli.py
etc/ci_scripts/dump_artifacts/docker_artifacts.py
src/python/grapl-tests-common/grapl_tests_common/setup_tests.py
test/docker-compose-with-error.sh

Fixes https://github.com/grapl-security/issue-tracker/issues/942
This consolidates our use of docker compose to the v2 version. This means we can get rid of one dependency and use the more supported version
Regression tests

Switch everything to docker compose v2

---

.github/CODEOWNERS
devbox/lib.sh
nomad/local/start_detach.sh
src/rust/bin/run_in_container.sh
src/sh/dependencies.sh
src/sh/log.sh

We were running into some bugs in some of our shell scripts, so this adds some helpful function libraries that can make it easier to see what's going on.
Please read the individual commit messages for further details.

Add some common shell libraries

---

.github/CODEOWNERS
Makefile
docker-bake.hcl
nomad/grapl-core.nomad
pulumi/grapl/__main__.py
src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/Dockerfile
src/rust/generator-dispatcher/Cargo.toml
src/rust/generator-dispatcher/README.md
src/rust/generator-dispatcher/src/config.rs
src/rust/generator-dispatcher/src/lib.rs
src/rust/generator-dispatcher/src/main.rs

https://app.zenhub.com/workspaces/grapl-6036cbd36bacff000ef314f2/issues/grapl-security/issue-tracker/714
https://github.com/grapl-security/issue-tracker/issues/714
Adds a new service that reads from raw_logs and writes them as Plugin Work Queue jobs.

Generator dispatcher - reads from Kafka raw_logs topic, writes to Plugin Work Queue

---

docker-compose.yml

Fix a minor shellcheck bug in e2e test up

---

.buildkite/pipeline.merge.promote.yml
.buildkite/pipeline.merge.yml
.buildkite/pipeline.provision.yml
.buildkite/pipeline.testing.yml
.buildkite/pipeline.verify.yml

Update grapl-security/vault-login Buildkite plugin version to v0.1.3
Picks up additional logging features, specifically https://github.com/grapl-security/vault-login-buildkite-plugin/pull/26
---

Update `vault-login` Buildkite plugin to `v0.1.3`

---

nomad/grapl-core.nomad
nomad/local/grapl-local-infra.nomad
pulumi/grapl/__main__.py
pulumi/infra/local/scylla.py
pulumi/infra/nomad_job.py
src/rust/graph-mutation-service/src/config.rs
src/rust/graph-mutation-service/src/main.rs

This does the Nomad hookup for graph-mutation service
make up

Twunderlich/product apis/nomad hookup

---

.buildkite/pipeline.provision.yml

Update grapl-security/pulumi Buildkite plugin version to v0.1.5
---

Update `pulumi` Buildkite plugin to `v0.1.5`

---

nomad/grapl-core.nomad
src/rust/Cargo.lock
src/rust/grapl-tracing/Cargo.toml
src/rust/grapl-tracing/src/setup_tracing.rs

NA
fixes an error in grapl-tracing, updates some tracing deps
automated tests

fix error in grapl-tracing and upgrade some deps

---

src/rust/Dockerfile
src/rust/generator-dispatcher/Cargo.toml
src/rust/generator-dispatcher/tests/generator_dispatcher_integration_tests.rs
src/rust/generator-dispatcher/tests/test_utils/context.rs
src/rust/rust-proto-clients/src/grpc_client.rs

none
Re-add commented out generator dispatch tests.
Needed a few new steps, but it worked on the first try :)
its tests

Resurrect generator-dispatcher tests!

---

src/rust/generator-dispatcher/src/generator_ids_cache.rs
src/rust/generator-dispatcher/src/lib.rs
src/rust/kafka-retry/src/main.rs
src/rust/pipeline-ingress/src/main.rs

NA
This PR adds some `[tracing::instrument]` decorators and attempts to make some logging improvements in generator-dispatcher, kafka-retry, and pipeline-ingress.

attempt to improve logging in some services

---

src/rust/Dockerfile
src/rust/plugin-work-queue/Cargo.toml
src/rust/plugin-work-queue/sqlx-data.json
src/rust/plugin-work-queue/src/psql_queue.rs
src/rust/plugin-work-queue/src/server.rs
src/rust/plugin-work-queue/tests/pwq_integration_test.rs

none
I discovered this requirements miss while doing e2e tests. 
i added a test suite

Plugin Work Queue: query by plugin_id for get_execute_[generator/analyzer]

---

src/rust/generators/sysmon-generator/src/api.rs
src/rust/generators/sysmon-generator/src/main_legacy.rs

Currently,
sysmon-generator treats an input of
```
<Event> stuff </Event>
<Event> other stuff </Event>
```
the same as
```
<Event> stuff </Event>
```
that is really hard to debug and led me down multiple goose chases. My hope is this 'warn' here will help future devs!

Warn if a multi-event log comes through sysmon-generator[-legacy]

---

src/rust/Cargo.toml

https://doc.rust-lang.org/cargo/reference/config.html#termcolor

Disable ANSI color codes in rust logs

---

pulumi/grapl/Pulumi.testing.yaml
pulumi/rust_integration_tests/Pulumi.testing.yaml

⚠️ THIS IS A PR AGAINST THE `rc` BRANCH ⚠️ 
We've retired a number of services lately; this cleans up our Pulumi
stacks to reflect the current state of things.

Remove outdated artifacts

---

src/rust/Cargo.lock
src/rust/grapl-config/Cargo.toml
src/rust/grapl-config/src/env_helpers.rs

Remove some Rusoto cruft

---

docs/development/services.md

I used to like consulting this file
https://grapl.readthedocs.io/en/main/development/services.html
to refresh myself on what goes on, what's going where?! 
This updates it, describing which services do what, and what their inputs/outputs are.

Update services.md to describe the new Kafka-y, Plugin-y world.

---

src/rust/client-executor/src/lib.rs

None, this is just some extra linting stuff.
Very minor changes like giving the builder methods `#[must_use]`, removing unnecessary clones, and adding ticks to doc comments.
Existing tests are sufficient, these are almost all cosmetic changes.

Clippify client-executor

---

Dockerfile.pulumi

https://github.com/pulumi/pulumi/releases/tag/v3.38.0

Update Pulumi to v3.38.0

---

pulumi/grapl/Pulumi.testing.yaml
src/rust/graph-query-service/src/graph_query.rs
src/rust/graph-query-service/src/node_query.rs
src/rust/graph-query-service/src/property_query.rs

Quick followup to some requests on https://github.com/grapl-security/grapl/pull/1889

Address jesse and ian comments on graph-query-service

---

pulumi/grapl/__main__.py

This one? This is the holy grail. No more local_grapl_core_vars/prod_grapl_core_vars, no more forgetting to add something for prod.

Rip out more if-prod-else-local Pulumi stuff!!!

---

nomad/grapl-core.nomad
nomad/grapl-graph-db.nomad
pulumi/grapl/__main__.py

None
Split apart our `grapl-core.nomad` by a reasonable boundary (stuff related to querying and mutating our graph databases).
integration tests :')

Move Graph DB related services to their own Nomad file

---

nomad/local/grapl-local-infra.nomad
src/rust/plugin-registry/src/error.rs
src/rust/plugin-registry/src/nomad/client.rs
src/rust/plugin-registry/src/server/deploy_plugin.rs
src/rust/plugin-registry/tests/test_nomad_client.rs

Add debuggability when theres a nomad allocation error

---

nomad/local/grapl-local-infra.nomad

Comment is self explanatory.
Related to https://grapl-internal.slack.com/archives/C02JCBKS97V/p1661885346470759

Docker postgres: shm size

---

devbox/provision/provision.sh

also I bumped the HDD size to 250gb, an amount that I found works reasonably well for me and requires few make clean-alls

Some improvements to devbox provisioner logging

---

etc/chromeos/lib/installs.sh

https://discuss.hashicorp.com/t/nomad-1-3-5-1-2-12-and-1-1-18-released/43844

setup_chromeos.sh: nomad 1.3.5 which theoretically  fixes UI ACLs issue

---

Dockerfile.pulumi
scylladb/Dockerfile
src/python/Dockerfile
src/rust/Dockerfile
src/rust/build-env.Dockerfile

None. It's just a dep update.
Update `curl` and `unzip`
No additional testing.

Update unzip curl

---

src/rust/e2e-tests/tests/sysmon_log_e2e_test.rs

asdfdshfdsj i need to catch an airplane

Fix sysmon e2e test - merged graphs for some reason is more than 36

---

.buildkite/pipeline.cargo-audit.sh
.buildkite/pipeline.npm-audit.sh
.buildkite/pipeline.verify.yml
.buildkite/pipeline.yarn-audit.sh

Update docker Buildkite plugin version to v3.14.0
https://github.com/buildkite-plugins/docker-buildkite-plugin/releases/tag/v3.14.0
---

Update `docker` Buildkite plugin to `v3.14.0`

---

.buildkite/pipeline.merge.promote.yml
.buildkite/pipeline.merge.yml
.buildkite/pipeline.provision.yml
.buildkite/pipeline.testing.yml
.buildkite/pipeline.verify.yml

Update grapl-security/vault-env Buildkite plugin version to v0.2.0
https://github.com/grapl-security/vault-env-buildkite-plugin/releases/tag/v0.2.0
---

Update `vault-env` Buildkite plugin to `v0.2.0`

---

Makefile

This was inadvertently left out of #1969.

Build test prerequisites we build images to push to Cloudsmith

---

nomad/local/grapl-local-infra.nomad

https://github.com/scylladb/scylladb/issues/10007
Speed up Scylla startup for local-grapl, which is single-node.
Lets us skip some cluster-y stuff.
CI here

Speed up scylla startup locally

---

src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/grapl-tracing/Cargo.toml
src/rust/uid-allocator/Cargo.toml

I'm gonna start integrating the otel rust client soon, so, yeah, this feels like a nice little cleanup

workspace dependencies for all three opentelemetry things

---

src/rust/Cargo.lock
src/rust/graph-query/Cargo.toml
src/rust/uid-allocator/Cargo.toml

Remove a bunch of Prost and Tonic stuff; rust-proto is the only place that should live!

---

.buildkite/pipeline.merge.promote.yml
.buildkite/pipeline.merge.yml
.buildkite/pipeline.provision.yml

Update artifacts Buildkite plugin version to v1.6.0
https://github.com/buildkite-plugins/artifacts-buildkite-plugin/releases/tag/v1.6.0
---

Update `artifacts` Buildkite plugin to `v1.6.0`

---

src/rust/Cargo.toml
src/rust/client-executor/Cargo.toml
src/rust/event-source/Cargo.toml
src/rust/graph-query/Cargo.toml
src/rust/organization-management/Cargo.toml
src/rust/plugin-registry/Cargo.toml
src/rust/scylla-provisioner/Cargo.toml
src/rust/uid-allocator/Cargo.toml

pretty straightforward: turn these two into workspace dependencies.

workspace-deps test-log and env_logger
