graph-descriptions/Cargo.lock
graph-descriptions/Cargo.toml
graph-descriptions/src/file.rs
graph-descriptions/src/ip_port.rs
graph-descriptions/src/lib.rs
graph-descriptions/src/process.rs
graph-descriptions/src/process_inbound_connection.rs
graph-descriptions/src/process_outbound_connection.rs
node-identifier/src/lib.rs

This PR includes a few fixes.
* AssetId is no longer pushed into the Master Graph for anything other than asset nodes
* IpPort identity no longer relies on ip_address
* Helper for NodeProperty

Schema Fixes

---

.github/workflows/grapl-release.yml

Trigger the release workflow on `prerelease` releases as well as `release` releases.

Internal 9 fix workflow

---

src/js/graphql_endpoint/server.js
src/js/grapl-cdk/index.ts

Quick fix to add a dynamic origin check for the bucket we pass into the graphql endpoint stack.
In the future we should pull that bucket name out of a passed property from the bucket itself.

Fix Cors Error

---

.github/workflows/grapl-release.yml

Internal 18 fix release workflow

---

.github/workflows/grapl-release.yml

We were pointing at `@v1` instead of `@v1.1.0` which appears to not work.

Fix pypa/gh-action-pypi-publish version

---

docker-compose.build.yml

Missing a dep in the docker-compose build file causes builds to fail in CI

add another depends_on

---

src/js/grapl-cdk/lib/engagement.ts
src/js/grapl-cdk/lib/graphql.ts
src/js/grapl-cdk/lib/grapl-cdk-stack.ts

Pretty simple PR.
This add pretty tight rate limiting to the login API, in particular. The other APIs basically keep you in the free tier, but otherwise are reasonably loose.

Add rate limiting to all API Gateways

---

.github/workflows/grapl-release.yml
.gitignore
etc/build_scripts/check_pypi_version.py

This PR adds a build script used in the grapl-release workflow to check whether grapl_analyzerlib or grapl_graph_descriptions need to be bumped before it attempts to build anything. The reason for this is that the PyPI upload will fail if we attempt to overwrite any existing versions.

Check whether versions need to be bumped before building

---

src/rust/Dockerfile
src/rust/analyzer-dispatcher/Dockerfile
src/rust/generic-subgraph-generator/Dockerfile
src/rust/graph-merger/Dockerfile
src/rust/node-identifier/Dockerfile
src/rust/sysmon-subgraph-generator/Dockerfile

We can't use Alpine images for the builds due to this issue: https://github.com/rust-lang/cargo/issues/7563#issuecomment-553526254
Our binaries need to be statically linked to work with AWS Lambda.

build in debian images instead of alpine

---

src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/lib/service.ts

We refer to Lambda execution roles directly and the auto-generated names are sometimes not legible. This gives a clear name and uses a common role for both handlers.

CDK - manually create Lambda execution role so we can name it

---

src/js/grapl-cdk/bin/grapl-cdk.ts
src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/python/analyzer_executor/src/analyzer-executor.py
src/python/grapl_analyzerlib/grapl_analyzerlib/plugin_retriever.py
src/rust/analyzer-dispatcher/src/main.rs
src/rust/graph-merger/src/main.rs

This fixes a number of issues with how the AnalyzerExecutor loads plugins. In particular, it tried to write to paths in the lambda that are not writable, and now it writes to /tmp/, which also gets added to the sys.path .

Fix analyzer executor

---

src/rust/Dockerfile

We were previously skipping debug builds and producing empty binaries.

Fix debug builds

---

src/rust/Cargo.lock

It seems a recent update to Cargo.lock broke staging and got passed the github build.

revert cargo update.

---

src/python/grapl-model-plugin-deployer/src/grapl_model_plugin_deployer.py

The Model Plugin Deployer was failing in AWS with errors point to the line fixed in this PR.
Made a local build with the diff in this PR and pushed that onto the AWS deployment that showing the error.

Fix format string.

---

src/rust/Cargo.lock

This bumps the version of the sqs-lambda used by our Rust services to incorporate a fix we were seeing in an AWS deployment. That fix can be found here: https://github.com/grapl-security/sqs-lambda/commit/b4713e8a45c08ba813bef2f7ecfc56581652a7c2.
The changes were tested in an AWS deployment using the CloudTrail generator.

Bump the version of sqs-lambda lib to 0.20.21.

---

CONTRIBUTING.md
README.md
docs/setup/local.md
src/python/grapl_analyzerlib/README.md

https://github.com/grapl-security/grapl/issues/214
Change the docs urls.
I visited the doc urls.

Fix all urls to point to new docs

---

etc/Grapl Provision.ipynb
src/js/grapl-cdk/README.md
src/js/grapl-cdk/docker-compose-multi.yml
src/js/grapl-cdk/lib/engagement.ts
src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/lib/swarm.ts

There were a couple issues this resolves:
1. Grapl Jupyter provision from wasn't working due to DGraph not whitelisting IPs
2. Docker Swarm AWS resources need deployment prefix in their names to support multiple deployments within an AWS environment.
1. The DGraph alphas now whitelist 10.0.0.0/8
2. DGraph AWS resources now have Grapl deployment name prefixed
3. Docker/DGraph provision now enables the docker systemctl service, and we run the provision as `ec2-user` instead of `ssm-user`.
Tested by running a single deployment in AWS sandbox account and running all provision steps, as well as deployed AWS plugin and uploaded model plugin via Grapl UI.

Docker Swarm CDK and provision

---

src/python/grapl-model-plugin-deployer/src/grapl_model_plugin_deployer.py

I was unable to upload model plugins, receiving HTTP 400 response with `{error: "Unexpected Error"}`. Upon checking logs on the backend I noticed "Origin did not match" log lines and found the regex indeed did not match the origin. After making this fix, I was able to upload plugins again.
Tested these changes in AWS in sandbox environment with AWS plugin.

Fix S3 Origin regex in model plugin deployer.

---

.github/workflows/grapl-build.yml
.github/workflows/grapl-lint.yml
dobi.yaml
src/python/analyzer-deployer/analyzer_deployer/app.py
src/python/analyzer-deployer/tests/test_app.py
src/python/grapl-common/grapl_common/py.typed
src/python/grapl-common/mypy.ini
src/python/grapl-common/setup.py

I've added Dobi targets that will run mypy on two of our libs/services: analyzer-deployer and grapl-common.
The existing mypy typecheck workflow simply silently failed.
I chose these two, for starters, because they:
- do not depend on analyzerlib
- are easy to get down to 0 type failures

Add a 'dobi python-typecheck' and corresponding Github Actions workflow

---

src/python/grapl-common/grapl_common/metrics/statsd_formatter.py
src/python/grapl-common/tests/metrics/test_statsd_formatter.py

If you're reviewing this, I highly suggest looking at things in the following order
- ctrl-f     `https://github.com/b/statsd_spec` - to see what the output should look like
- ctrl-f `TestStatsdFormatter` - see the tests
- finally, read the source code
---
As discussed in Slack yesterday, we will emit metrics in statsd format to stdout for our lambdas.
This is simply a first step in getting there. :)
Shockingly (or not), I couldn't easily find any OSS libraries dedicated strictly to the statsd format; instead, they were often paired with a UDP client/server. 
I will also have to make a Rust version of this - exciting, it'll be my first real Rust foray beyond a hello world!

Statsd formatter in Python grapl_common

---

src/rust/Cargo.lock
src/rust/grapl-observe/src/statsd_formatter.rs
src/rust/metric-forwarder/Cargo.toml
src/rust/metric-forwarder/based_on_github_repo.md
src/rust/metric-forwarder/src/cloudwatch_logs_parse.rs
src/rust/metric-forwarder/src/cloudwatch_send.rs
src/rust/metric-forwarder/src/error.rs
src/rust/metric-forwarder/src/main.rs

#232
`deser_logs_data`: deserialize the crazy gzip input from Lambda into pure strings
`cloudwatch_logs_parse`: parse those pure strings into a platform-agnostic `Stat` type
`cloudwatch_send`: turn Stat into Cloudwatch types and send it to Cloudwatch
`main.rs` please triple check my usage of Arc<Mutex
i have some very small unit tests, but unfortunately this is not super testable until it's complete.
I haven't added it as a service to our CDK yet, but that's up next, at which point I'll be able to test on my personal instance.

Metric Forwarder: parsing input, converting to Cloudwatch, sneding to Cloudwatch

---

etc/local_grapl/grapl_provision.py
src/python/grapl-model-plugin-deployer/src/grapl_model_plugin_deployer.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/base.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/entity.py
src/python/grapl_analyzerlib/grapl_analyzerlib/schema.py

This is a hotfix. I'll create an issue for this retroactively, but I want to start the PR now.
When deploying new nodes, we need to fetch the existing schemas of nodes from dgraph and reconstruct them as python
The problem is that we don't know what the reverse edges are, ie: We can know that it's a ManyToX relationship, but not if it's a ToOne or a ToMany
We basically just set the reverse edge to null and say "don't worry about it, just worry about what we know"
There was an inversion in some of the code that led to the edge being OneToMany, not ManyToOne, and so that broke some of our model plugin deployer code.
Tested via localgrapl.

Fix issue with grapl-model-plugin-deployer

---

src/rust/Cargo.lock
src/rust/derive-dynamic-node/Cargo.toml
src/rust/derive-dynamic-node/src/lib.rs
src/rust/node-identifier/src/dynamic_sessiondb.rs

https://github.com/grapl-security/grapl/issues/263
#263 
There was an attempt to have identities be parameterized by their types. Not only is this probably not a thing we want, it also introduced a complete and total breakage of identification of plugin nodes.
They were not. It's a one liner, and a revert.

Update dynamic node static idenfication

---

dobi.yaml
docker-compose.yml
etc/local_grapl/bin/upload-sysmon-logs.py
src/js/grapl-cdk/extract-grapl-deployment-artifacts.sh
src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/lib/service.ts
src/rust/Cargo.lock
src/rust/Dockerfile
src/rust/grapl-observe/Cargo.toml
src/rust/grapl-observe/src/metric_reporter.rs
src/rust/metric-forwarder/Dockerfile
src/rust/metric-forwarder/src/cloudwatch_logs_parse.rs
src/rust/metric-forwarder/src/cloudwatch_send.rs
src/rust/metric-forwarder/src/error.rs
src/rust/metric-forwarder/src/main.rs
src/rust/sysmon-subgraph-generator/src/main.rs
src/rust/sysmon-subgraph-generator/src/metrics.rs

#232
- Add all the dobi/docker/cdk scaffolding for Metric Forwarder as a lambda service; also some bugfixes in the docker files
- quicker parallelized `extract-grapl-deployment-artifacts`
- Added Sysmon as a 'client' of the metric forwarder (its logs are sent to the metric forwarder)
- Completely revamped the printlns for monitoring
(Before: Assumed the Lambda runtime spit out timestamp info; it does not, so I now encode it, like `MONITORING|timestamp_here|statsd_stuff_here`)
- Add some debuggability to the metric forwarder (info!s, better errors)
Deployed to CDK, and it works! I see the sysmon metric in Cloudwatch.

Promote Metric Forwarder to a true CDK service (and a bunch of random fixes I found along the way)

---

src/rust/analyzer-dispatcher/src/main.rs
src/rust/generic-subgraph-generator/src/main.rs
src/rust/graph-merger/src/main.rs
src/rust/grapl-config/src/lib.rs
src/rust/metric-forwarder/src/main.rs
src/rust/node-identifier/src/bin/node-identifier-retry-handler.rs
src/rust/node-identifier/src/bin/node-identifier.rs
src/rust/sysmon-subgraph-generator/src/main.rs

none, but I want to easily grab service name for my MetricReporter ( #232 )
init_grapl_log knew about service name, but hogged it to itself. this new struct exposes it, as well as the extremely useful and common is_local
cargo test

Change init_grapl_log to init_grapl_env, which returns a new struct ServiceEnv

---

src/python/grapl-common/grapl_common/metrics/statsd_formatter.py
src/python/grapl-common/tests/metrics/test_statsd_formatter.py
src/rust/grapl-observe/src/metric_reporter.rs
src/rust/grapl-observe/src/statsd_formatter.rs
src/rust/metric-forwarder/src/cloudwatch_logs_parse.rs
src/rust/metric-forwarder/src/cloudwatch_send.rs
src/rust/metric-forwarder/src/error.rs
src/rust/metric-forwarder/src/main.rs
src/rust/sysmon-subgraph-generator/src/main.rs
src/rust/sysmon-subgraph-generator/src/metrics.rs

#232
When reporting metrics to stdout, include the name of the service.
When reading those metrics and sending them to Cloudwatch, use the service name as the Namespace.
I added a few tests, and I'm about to CDK it up

Grapl metrics now report their 'service name', and Metric Forwarder uses that as a Cloudwatch Namespace

---

dobi.yaml
docs/setup/local.md
etc/Dockerfile
etc/local_grapl/bin/upload-sysmon-logs.py
src/python/grapl_e2e_tests/Dockerfile
src/python/grapl_e2e_tests/main.py
src/python/grapl_e2e_tests/pytest.ini
src/python/grapl_e2e_tests/resources.py
src/python/grapl_e2e_tests/tests.py

#231 
Created a skeleton framework for e2e tests with empty, useless tests.
However I'm confident that the 'setup' part of it works well.
Output:
```
Starting grapl-integration-tests_grapl-graph-provision_1               ... done
Starting grapl-integration-tests_analyzer-deployer_1                   ... done
Starting grapl-integration-tests_grapl-node-identifier-retry-handler_1 ... done
Starting grapl-integration-tests_grapl-node-identifier_1               ... done
Starting grapl-integration-tests_grapl-sysmon-subgraph-generator_1     ... done
Starting grapl-integration-tests_grapl-graph-merger_1                  ... done
[compose:up integration-env] docker-compose.yml Done
[job: run-e2e-integration-tests] /bin/bash -c "sleep 5 && source venv/bin/activate && cd grapl_e2e_tests && python3 …
```

E2E integration tests - performs the setup, doesn't have any tests yet

---

src/python/grapl_e2e_tests/tests.py

#231 
The e2e test failed once yesterday because the lens only had 1 node in scope instead of 3. turns out adding those edges is not atomic. 
Upon re-run it worked fine.
by submitting this diff, yolo

Add one more sleep to e2e test

---

.github/workflows/grapl-build.yml
dobi.yaml
src/python/grapl_e2e_tests/main.py
src/python/grapl_e2e_tests/resources.py
src/python/grapl_e2e_tests/tests.py

#231
E2E tests are no longer part of the integration-tests workflow, and are no longer required.
It's highly timing dependent, and sometimes it works, and sometimes it's not.
I've bumped the timeout on "4 entities within scope" up from 30s to 120s.
its tests

E2E tests are no longer part of the integration-tests workflow, and are no longer required.

---

.github/workflows/grapl-staging-release.yml

Minor bug in the yaml - it didn't like an empty `env:`

Bugfix for "push staging images to dockerhub" workflow

---

docker-compose.yml

No Grapl issue (yet?) but when trying to run a simple query in local grapl I'd get a connection.
```
q = ProcessQuery()
q.query(mclient, first=500)
```
```
debug_error_string = "{"created":"@1601954099.726020446","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4133,"referenced_errors":[{"created":"@1601954099.726014048","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
```
I'm adding the MG_ALPHAS env var to the notebook container in docker-compose.
Ran `docker-compose up` with this diff and ran the same query with no issue. The query returned empty list, as expected.

Add MG_ALPHAS env variable to notebook in docker-compose

---

etc/build_scripts/push_py_to_docker.sh

sadly, this is the output in the current setup:
```
00656e899bf2: Pushed
1bdb7650b726: Pushed
staging: digest: sha256:4d79fa36ae25335a3153ffe882b1dc9cea7796c297bc6ada0e87267ef38f0e72 size: 2625
An image does not exist locally with the tag: grapl/grapl-local-provision
The push refers to repository [docker.io/grapl/grapl-local-provision]
An image does not exist locally with the tag: grapl/grapl-dynamodb-provision
The push refers to repository [docker.io/grapl/grapl-dynamodb-provision]
The push refers to repository [docker.io/grapl/grapl-dgraph-ttl]
cfe427083b37: Preparing
1d6ab56bf426: Preparing
3062cf14e417: Preparing
```
wtf that should be a hard fail imo but ok docker

Fix push_py_to_docker for new provision service

---

.github/workflows/grapl-build.yml
.github/workflows/grapl-release.yml
.github/workflows/grapl-staging-release.yml
etc/ci_scripts/clean_gh_actions_space.sh
etc/ci_scripts/install_requirements.sh

Add script to clean up Github Actions CI before builds

---

dobi.yaml
etc/local_grapl/suspicious_svchost/main.py
src/python/engagement-creator/src/engagement-creator.py
src/python/grapl-tests-common/grapl_tests_common/setup.py
src/python/grapl_analyzerlib/grapl_analyzerlib/execution.py
src/python/grapl_e2e_tests/tests.py

#348 
- stop the suspicious-svchost from looking up a Process without an associated Asset
- throw a TypeError if we encounter a None in the lenses k/v
ran e2e tests a lot

Fix #348 and add some documentation on debugging e2e tests

---

src/js/grapl-cdk/.dockerignore

This creates a .dockerignore for the grapl CDK. the zips and cdk.out dirs can get fairly large over time when deploying from there.
Built the cdk image (`dobi build-grapl-cdk`) and created a container to verify they were no longer copied.

Add a .dockerignore for CDK to exclude zips and cdk.out, both of which

---

etc/ci_scripts/clean_gh_actions_space.sh

I noticed the `ubuntu-latest` that we use for GitHub CI actions comes pre-loaded with a number of docker images that we don't use, such as `jekyll/builder:latest` and `mcr.microsoft.com/azure-pipelines/node8-typescript:latest`. Seems like removing those would give us a fair amount of headroom to mitigate the disk space limits we've hit in the past.
Tested with this PR. From the cleanup script run for this PR:
```
Starting space: /dev/sdb1        84G   64G   21G  76% /
...
Ending space: /dev/sdb1        84G   52G   32G  62% /
```
This doesn't exactly show final space savings at tail end of all checks - it's possible docker ends up downloading layers we remove.

Cleanup unused docker images for GitHub CI

---

dobi.yaml
docker-compose.yml
src/python/grapl-python-build/Dockerfile
src/rust/Dockerfile

#363
I have reason to believe a number of our e2e test failures are due to the dgraph schema not being provisioned in time for the tests.
I ran this locally and it appears to work.
grapl-aws-provision sometimes takes 38 seconds to come up.

Add a rudimentary health check to grapl_provision; depend on this health check from tests

---

.github/workflows/grapl-build.yml
etc/ci_scripts/dump_compose_logs.py

#231 
- Introduce a new script that just collects all `docker logs` for a given dobi `compose=` task
- Run that new script after an e2e test run
- Upload results of script to Github artifacts - learn more here! https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts
by submitting this very diff!!!

Dump logs for all services to Github after running e2e integration tests

---

etc/Grapl Provision.ipynb

The grapl analyzer lib was apparently updated such that a line in the provision notebook doesn't work, and isn't needed. This removes that.
I uploaded this new notebook to a deployment in AWS and verified it doesn't error.

remove broken line from Grapl provision notebook - new analyzer lib.

---

src/js/grapl-cdk/lib/grapl-cdk-stack.ts

I was getting connection issues in the model-plugin-deployer. Found that a previous change[1] the CDK changed the value of MG_ALPHAS for all services, where it looks like it was meant for the graph-merger only. This PR resolves that by restoring the original function and applying the addition of the schema to the graph-merger service, similar to how this was done for the docker-compose config for running locally.
[1] https://github.com/grapl-security/grapl/commit/cc3689f746a2089e5f81b0d9ff63262b7d6f9fcd#diff-e61371fab55a097df00568e44afa96c515ff70cbbfae4317c8be6cf7c3f8e6cfL477-R477
I redeployed these changes on an AWS deployment in my sandbox account and noticed I had no longer had connection issues in model-plugin-deployer. Also, I noticed I was *not* getting connection errors in …

Restore MG_ALPHA for services other than graph merger

---

dobi.yaml
docker-compose.yml
src/python/grapl-common/grapl_common/debugger/vsc_debugger.py
src/python/grapl_e2e_tests/main.py

it sort of came up as part of #231 
Adds a new library to grapl-common that makes it relatively simple for a service to optionally attach to the VSCode pycharm debugger.
The whole debugger code path won't trigger unless the caller specifies
DEBUG_SERVICES=service1,service2

Add VSCode debugger support to Python services (but for now, just grapl-e2e-tests)

---

dobi.yaml
docker-compose.yml
src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/lib/service.ts
src/python/analyzer_executor/Dockerfile
src/python/analyzer_executor/setup.py
src/python/analyzer_executor/src/analyzer_executor_lib/analyzer_executor.py
src/python/analyzer_executor/src/lambda_function.py
src/python/analyzer_executor/src/run_local.py

none
- fun fact: NONE of our python lambdas are >1 file. while that's _okay_ for now, I want to rip the bandaid off before we end up with 5000 line files
- makes the `analyzer_executor` lib something that can actually be tested now (previously, a filename with a `-` is not a valid Python module and cannot be imported)
- enables us to split files up further in the future
- also, splits apart the entrypoint for the 'run local' stuff versus the lambda handler stuff
- put it on AWS and sent a test event (poorly formatted one). it failed, but not due to import error - instead, due to json stuff
- locally: just gonna ran e2e tests

Proof-of-concept: split up analyzer_executor into multiple files

---

src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/package-lock.json
src/python/engagement-creator/Dockerfile

Started seeing an error for engagement-creator:
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'engagement-creator': No module named 'engagement-creator'
```
This PR does a couple things:
1. Change the zip package layout for engagement-creator to be consistent with other packages and in a way that is expected for AWS lambda.
2. Doing a `npm i` in a fresh src/js/grapl-cdk dir resulted in the package-lock.json diff. Figured might as well include here.
~I tested 1. above by standard steps for build and cdk deploy. For 2. I didn't do that, I just changed the entrypoint value in the AWS Console and submitted new test data, which succeeded with an engagement created in the Grapl UI. I made sure have the value I used there match what I put in the CDK.~
Previous test was …

Fix engagement-creator zip packaging for AWS

---

src/rust/Cargo.lock

example:
https://github.com/grapl-security/grapl/runs/1343623868?check_suite_focus=true
technically this is less minimal than it could have been, but hey, nothing wrong with an update here and there

`cargo update`, due to two `futures-` having a vulnerability

---

dobi.yaml
docker-compose.yml

This names the docker-compose network and makes it easier for us to `docker-compose up` from a generator in another location/repo by joining the network.
Tested with local version of CloudTrail generator compose file.

Name and expose the docker-compose network

---

docker-compose.yml

https://github.com/grapl-security/grapl/issues/393
This restores the command to run in the engagement-view container for local grapl. We were using the default from the base image, which was recently overwritten in a build stage. This tells docker-compose to use the original command, the original default from base image.
Ran `docker-compose up` and saw the engagement view restored.

restore cmd to run for engagement-view in local grapl.

---

.github/workflows/grapl-build.yml
dobi.yaml
etc/ci_scripts/dump_artifacts.py
src/python/grapl-tests-common/grapl_tests_common/setup.py

Rename "e2e-integration" to just "e2e"; mark flaky tests as obviously flaky; rename the `dump_artifacts` script

---

src/js/grapl-cdk/README.md

The current CDK README.md hard-codes the EC2 AMI to use for dgraph provisioning. This is unfortunate for those deploying to regions other than us-east-2. This PR:
- add notes as comments to the script on how find new AMIs
- provides AMIs to use for different regions
- default uses the latest AMI found for the region (search via aws cli)
This will go away when https://github.com/grapl-security/grapl/tree/internal-79-dgraph-disk-monitoring gets merged, which should be soon, but this will help deployments until that happens.
I ran the search command and verified the results were expected.

Have the dgraph provision shell steps find and use latest Ubuntu 18.04 AMI

---

.github/workflows/grapl-build.yml
docs/development/vscode_debugger.rst

woops, the most important reference to `run-e2e-integration-tests` was not replaced, and we allow it to fail anyways since it's flaky.

Fix the Github Workflow for e2e - which is still flaky lol

---

src/js/grapl-cdk/README.md
src/js/grapl-cdk/bin/grapl-cdk.ts
src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/test/grapl-cdk.test.ts

This allows users to supply CDK deployment arguments via environment variables instead of specifying in the bin/grapl-cdk.ts file.
Local CDK build works, but I haven't yet tested a deploy to AWS. Can do before merging.

Try to get required CDK deployment args from environment.

---

docker-compose.yml
src/js/graphql_endpoint/modules/jwt.js
src/python/engagement_edge/Dockerfile
src/python/engagement_edge/src/engagement_edge.py
src/python/grapl-model-plugin-deployer/src/grapl_model_plugin_deployer.py
src/python/grapl_provision/grapl_provision.py

This solves Andrea's issue. 
- engagement edge assumes a secretmanager available on 4566 (but that port was never opened)
- engagement edge silently fails if that secretmanager is never made available (it's just in a while-loop of failure, forever)
I've:
- exposed 4566
- made it not silently fail (if it can't retrieve JWT within N seconds, raise an error)
- made it explicitly depend on the user creation in grapl-provision, instead of just wait-forever

more-robust consumption of secrets manager

---

dobi.yaml
src/js/grapl-cdk/lib/engagement.ts
src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/python/engagement_edge/Dockerfile
src/python/engagement_edge/setup.py
src/python/engagement_edge/src/engagement_edge.py
src/python/engagement_edge/src/lib/constants.py
src/python/engagement_edge/src/lib/env_vars.py
src/python/engagement_edge/src/lib/sagemaker.py
src/python/engagement_edge/tests/test_default.py
src/python/engagement_edge/tests/test_engagement_edge.py

https://github.com/grapl-security/issue-tracker/issues/115
- Expose an endpoint on Engagement Edge that will return a URL to the Jupyter notebook.
- IAM insanity.
I tested in prod to ensure the URL is returned correctly. 
I'm going to quickly add Chalice tests (that will not be super helpful for this exact task) but u gotta start somewhere

Get grapl notebook url from Engagement Edge

---

src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/lib/swarm.ts

The value for MG_ALPHAS in AWS has an extra scheme spec. Looks like this is due to swarm/clusterHostPort() also returning scheme.

Fix MG_ALPHA for graph merger in cdk.

---

.github/workflows/grapl-release.yml
.github/workflows/grapl-staging-release.yml

https://grapl-internal.slack.com/archives/G017L03AE0L/p1606775942132700
```
Run echo "::set-env name=TAG::staging"
Error: Unable to process command '::set-env name=TAG::staging' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
This is the new way to do that.

Fix github workflows that depend on set-env

---

src/js/grapl-cdk/bin/grapl-cdk.ts

A region arg is supplied to the base stack, but not the Edge UX stack in CDK, so they will deploy to different regions if the region specified is not the default. This change passes the region to the Edge UX stack, as is done for the base stack.
The build passes, testing a deployment now.

Adding missing region arg to Edge UX stack in CDK.

---

src/rust/generators/osquery-subgraph-generator/src/parsers/grapl_pack/process_files.rs

https://github.com/grapl-security/grapl/issues/450
It corrects an issue with the OSQuery Generator that occasionally caused panics with certain process-file events.
Local validation of remediation of issues.

Fix 0u64 panic caused by OSQuery Generator

---

src/js/graphql_endpoint/server.js

Corrects a fatal bug causing the graphql_endpoint service to crash due to an improperly named environment variable. This caused the `prefix` variable to be undefined resulting in an exception when the CORS origin check regular expression was crafted.
Local validation

Fix incorrect env name

---

src/js/grapl-cdk/lib/swarm.ts

This PR sets the docker root directory to `/dgraph` on the Swarm nodes, which is mounted on a larger drive.
These changes were tested in AWS sandbox.

put docker data-root in /dgraph partition

---

src/js/grapl-cdk/lib/alarms.ts
src/js/grapl-cdk/lib/grapl-cdk-stack.ts

The CDK creates a CloudWatch alarm for Grapl Risk nodes with a static name, which breaks multiple deployments within an AWS account. This makes that name depend on deployment name.
Tested by completing a second deployment that had previously failed due alarm name collision.

Making Risk node alarm name depend on Grapl deployment name.

---

dobi.yaml
src/js/engagement_view/src/components/EngagementViewContent.tsx
src/js/engagement_view/src/modules/GraphViz/graphQL/expandScope.tsx
src/js/graphql_endpoint/package-lock.json
src/js/graphql_endpoint/package.json
src/js/graphql_endpoint/server.js
src/js/graphql_endpoint/yarn.lock

https://github.com/grapl-security/issue-tracker/issues/124
- upgraded `grpc`, `dgraph-js` and changed `graphql` endpoint to `graphQlEndpoint/graphql`
We were unable to retrieve a graph because we were calling the wrong graphql endpoint. we recently added a new endpoint to be called for graphql instead
Manually, logged in to local grapl, made sure we could call the new graphql endpoint and retrieve the graph.

Internal 124 upgrade dgraph grpc

---

docker-compose.yml
src/js/engagement_view/src/components/EngagementViewContent.tsx
src/js/graphql_endpoint/modules/schema.js
src/js/graphql_endpoint/package-lock.json
src/js/graphql_endpoint/package.json

lenses were not showing up on FE, converted from `grpc` to `http` until `dgraph-js-grpc` stabilizes
We were talking to Dgraph using `grpc`  had a bug that was resolved in `grpc` v1.24.4. DGraph does not have the update yet, so `grpc` was timing out and we were unable to retrieve lenses. Using `http` for now. 
Locally. Once merged, we'll test in the AWS sandbox.

Internal 126 grpc to http

---

src/js/grapl-cdk/swarm/swarm_setup.py

Cloudwatch alarms need *all dimensions to be specified*, so we do a quick query first
I ran the new query function in ipython:
and I ran mypy locally, it succeeds (i didnt make a dobi job cuz, ehh)
I'd be happy to give it a shot in AWS.

Fix dgraph disk usage alarms to specify all dimensions

---

src/js/engagement_view/src/components/EngagementViewContent.tsx
src/js/grapl-cdk/lib/graphql.ts

EngView timeout is because every 1s was kinda polluting our network console
Graphql lambda timeout is because, the timeout at 25 seconds is just a silent kill; bumping it to 30s puts us here:
https://grapl-internal.slack.com/archives/G017L03AE0L/p1607389929303800
```
so, basically, my theory is
lambda takes more than 25 seconds -> silent failure
<then I upped the lambda to accept 5 minute runs>
now if it takes more than 30 seconds -> {"message": "Endpoint request timed out"}
5:13
and, once in a blue moon, we do get results in like 26 seconds
```

Bump EngView timeout to every 5 seconds. Bump graphql lambda timeout to 30s.

---

src/js/grapl-cdk/bin/deployment_parameters.ts
src/js/grapl-cdk/lib/alarms.ts
src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/swarm/swarm_setup.py
src/js/grapl-cdk/test/grapl-cdk.test.ts

- makes security / operational alarms mandatory
- gives AlarmSink topics a stable identifier
- subscribes disk_use_percent alarms to that same stable identifier for operational alarm
I tested the `find` function just locally, and it passes my typecheck.
I'm going to kick off a cdk deploy - to my sandbox, not jgrillo's - momentarily...

Subscribe disk use alarms to Operational Alarms

---

dobi.yaml
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/base.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/ip_address.py
src/python/grapl_analyzerlib/grapl_analyzerlib/nodes/ip_connection.py
src/python/grapl_analyzerlib/grapl_analyzerlib/viewable.py
src/python/grapl_analyzerlib/pytype.cfg
src/python/grapl_analyzerlib/test2.py
src/python/grapl_analyzerlib/tests/test_comparators.py
src/python/grapl_analyzerlib/tests/test_default.py
src/python/grapl_analyzerlib/tests/test_engagement.py

none in particular
Before this we were getting
```
~/venv/lib/python3.7/site-packages/grapl_analyzerlib/nodes/base.py in into_view(self, v)
133                 graph_client=self.graph_client,
134                 node_types=self.node_types,
--> 135                 **self.predicates,
136             )
137         return None
TypeError: ABCMeta object got multiple values for keyword argument 'node_types'
```
I pop out `node_types` from self.predicates and merge it into self.node_types.
Oh, and I enabled typechecking for analyzerlib in CI :+1:
wrote an integration smoke test for EngagementView.get_or_create

Fix EngagementView.get_or_create; enable analyzerlib python typechecking in CI

---

src/js/grapl-cdk/lib/engagement.ts
src/js/grapl-cdk/lib/grapl-cdk-stack.ts

we found out in #bugs that schema table was not read-write from the engagement notebook
https://grapl-internal.slack.com/archives/C0176MS6LBY/p1607979680024800

Fix notebook role

---

dobi.yaml
src/python/analyzer_executor/tests.Dockerfile
src/python/engagement-creator/tests.Dockerfile
src/python/engagement_edge/tests.Dockerfile
src/python/grapl-common/Dockerfile
src/python/grapl-common/tests.Dockerfile
src/python/grapl-dgraph-ttl/tests.Dockerfile
src/python/grapl-model-plugin-deployer/tests.Dockerfile
src/python/grapl-python-build/Dockerfile
src/python/grapl-tests-common/Dockerfile
src/python/grapl_analyzerlib/tests.Dockerfile
src/python/grapl_e2e_tests/Dockerfile
src/python/python_test_deps/Dockerfile
src/python/python_test_deps/README.md
src/python/python_test_deps/download_requirements.sh
src/python/python_test_deps/install_requirements.sh
src/python/python_test_deps/requirements.txt
src/rust/graph-descriptions/Dockerfile
src/rust/graph-descriptions/tests.Dockerfile

none
Remove some of our test-only dependencies (pytest, xdist, hypothesis) from the zips we upload to Lambda.
Make new images that _do_ include them, which include other QA-helper libraries, like mypy, boto stubs, etc
its all about the tests baby

Dedicated Python "-test" images, for tests/typechecking; strip pytest/etc out of build/deploy images

---

src/js/grapl-cdk/swarm/swarm_setup.py

none
Move the disk alarms up before we ever send off an SSM command.
Because sometimes we'd have a situation where we set up the first node successfully, but the worker nodes' disk alarms couldn't be set up; and running swarm_setup again would fail.
Store export commands on-disk so that future docker stack deploy operations are easier. 
on my aws sandbox

Swarm Setup: do disk alarms first + store export commands on-disk

---

src/rust/graph-merger/src/main.rs

Avoids holding a transaction open on edge mutations by using the `commit_now` feature of dgraph mutations to commit mutations immediately. This should have a very tiny performance improvement and close the most likely cause of transient write failures.
locally

Immediately commit edge writes in dgraph to avoid occasional transactional failures

---

src/python/engagement_edge/requirements.txt
src/python/engagement_edge/src/engagement_edge.py

TLDR they removed py2 support from pyjwt, meaning this object is now a `str` not a `bytes`

Fix python typecheck, pin pyjwt

---

src/js/grapl-cdk/deploy_all.sh

The CDK reference `edge_ux_package` directory as asset for upload, so it expects to find it on first CDK deploy, before the following step to create the contents of it (`npm run create_edge_ux_package`). On a clean clone of the repo, the CDK deploy_all.sh script fails.
This creates an empty directory with the name to satisfy the first CDK deploy. 
Tested by running the deploy_all.sh script to deploy to AWS.

Create edge_ux_package dir in CDK deploy_all.sh

---

src/python/grapl-common/grapl_common/metrics/metric_reporter.py
src/rust/grapl-observe/src/metric_reporter.rs
src/rust/metric-forwarder/src/accumulate_metrics.rs
src/rust/metric-forwarder/src/cloudwatch_send.rs

https://github.com/grapl-security/issue-tracker/issues/132
Now we shoehorn unit data into <tags / dimensions> on the `metric_reporter.py|rs` side
and we optionally pop that data off and consume it on the `metric_forwarder` side, to send the requisite units to Cloudwatch.
I didn't test the reporter side, since it's pretty straightforward piggybacking off of existing, well-tested tag infrastructure.
I did unit test the `metric_forwarder` side.

Histogram now supports seconds and microseconds. 

---

src/python/analyzer_executor/requirements.txt
src/python/engagement-creator/requirements.txt
src/python/engagement_edge/requirements.txt
src/python/grapl-dgraph-ttl/requirements.txt
src/python/grapl-model-plugin-deployer/requirements.txt

The analyzer-executor build process was installing an older version of the grapl_analyzerlib from pip, uninstalling the locally built version. This removes the version spec for grapl_analyzerlib from analyzer-executor and other python services that depend on it.
The following error was observed in AWS deployment:
```
[ERROR] ValueError: No clients provided in DgraphClient constructor
Traceback (most recent call last):
File "/var/task/analyzer_executor_lib/analyzer_executor.py", line 190, in lambda_handler_fn
client = GraphClient()
File "/var/task/pydgraph/client.py", line 38, in __init__
raise ValueError('No clients provided in DgraphClient constructor')
[ERROR] ValueError: No clients provided in DgraphClient constructor Traceback (most recent call last):   File …
```

Remove version spec from python grapl lib dependencies

---

dobi.yaml
docker-compose.yml
etc/local_grapl/bin/upload-osquery-logs.py
etc/local_grapl/bin/upload-sysmon-logs.py
src/python/analyzer_executor/src/analyzer_executor_lib/analyzer_executor.py
src/python/analyzer_executor/src/run_local.py
src/python/grapl-common/grapl_common/env_helpers.py
src/python/grapl-tests-common/grapl_tests_common/setup.py
src/python/grapl-tests-common/grapl_tests_common/upload_logs.py
src/python/grapl-tests-common/grapl_tests_common/upload_test_data.py
src/python/grapl_analyzerlib/grapl_analyzerlib/grapl_client.py
src/python/grapl_analyzerlib/grapl_analyzerlib/plugin_retriever.py
src/python/grapl_analyzerlib/grapl_analyzerlib/prelude.py
src/python/grapl_provision/grapl_provision.py
src/python/python_test_deps/requirements.txt

compare with env_helpers.rs in Colin's big PR:
https://github.com/grapl-security/grapl/pull/515/files#diff-fcad1f6e2e3eb8c0bc18e7372dd0734d2b6c2d72f8c87b12bc580c82c8a74d80
I migrated Analyzer Executor to this, and I ripped a bunch of complexity out of the Upload Logs code.
Testing: I tested the CLI `upload-sysmon-logs` script and I actually got e2e tests to run a few times

Begin to migrate python S3/SQS clients to a FromEnv equivalent

---

.gitignore
src/rust/.cargo/config.toml

To silence our noisy build output for the time being, we will allow
certain classes of compiler lints that are warnings by default.
Eventually, we'll actually _fix_ these violations and allow the lints
to become warnings again. This allows us to have a nicer local build
experience today, while allowing us a structure for fixing the
violations in a principled way, at our own pace.

[Chore] Temporarily allow certain compilation warnings

---

src/rust/.dockerignore
src/rust/Dockerfile

Previously, `.cargo` was specifically excluded from Docker
builds. This seems to be related to how we use `cargo vendor` builds.
In particular, the output of `cargo vendor` was saved to
`.cargo/config`. This file was the name of the configuration file
prior to Rust 1.39, but the current preferred name is `cargo.toml`. If
both files are present, `config` is used and `config.toml` is ignored.
Because of this, the configuration added in #544 was not being honored
in any of the container-based build systems.
Here, we stop ignoring `.cargo` in builds, allowing us to copy
`.cargo/config.toml` into the container. Then, we append the output of
`cargo vendor` to this file.
For reference, this is what that appended output looks like:
[source.crates-io]
replace-with = "vendored-sources" …

[CI] Ensure Docker builds obey .cargo/config.toml settings

---

.github/CODEOWNERS
.github/workflows/grapl-lint.yml
src/rust/bin/run-clippy.sh
src/rust/rust-toolchain

https://github.com/grapl-security/issue-tracker/issues/215
This introduces the use of [Clippy](https://github.com/rust-lang/rust-clippy) for linting Rust code.
Since detailed configuration of the levels of each Clippy lint isn't currently possible, we have to manage it all at the command line. To ensure that we lint consistently everywhere, all that logic is consolidated into a single script (`run-clippy.sh`).
Basic usage is simply calling the script:
cd src/rust
bin/run-clippy.sh
However, this script can be integrated into editors to provide linting-on-save functionality. Editor integrations usually operate on
machine-readable output of tools, though, and so this script can be called with a formatting argument for those usecases, e.g.,
bin/run-clippy.sh json
For example, integrating into …

[Chore] Add foundation for Clippy usage on Rust code

---

src/rust/Cargo.lock
src/rust/generators/generic-subgraph-generator/Cargo.toml

They're not being used, so there's no reason to keep them around.
Also organized the `Cargo.toml` file while I was at it. Looking at only the final diff of `Cargo.toml` is a bit confusing, so I recommend looking at the sequence of individual changes to get a better feel for how the changes progressed.

Remove unused dependencies from generic-subgraph-generator crate

---

src/rust/.cargo/config.toml
src/rust/generators/generic-subgraph-generator/src/tests.rs
src/rust/generators/osquery-subgraph-generator/src/tests/process.rs
src/rust/generators/osquery-subgraph-generator/src/tests/utils.rs
src/rust/node-identifier/tests/assetdb_integration_tests.rs
src/rust/node-identifier/tests/sessiondb_integration_tests.rs

It makes Rust builds more strict by denying violations of the following compiler lints in our code:
- [non_snake_case](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#non-snake-case)
- [unused_mut](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#unused-mut)
- [unused_variables](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#unused-variables)
- [unused_imports](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#unused-imports)
In addition to denying these violations, any existing violations were addressed. Please see individual commits for further details.
Run `cargo build --all-targets` and observe a clean build.

[Chore] Deny some lint violations

---

CHORES.md

Adds a place to begin collecting the rationale for various chores we should be doing on a regular basis to keep our code in shape.
This also serves as a checklist of things to automate in the future.
(Note to reviewers: in part, these instructions describe features that assume that #552 has merged, which is anticipated later today.)

Document some code maintenance chores

---

src/python/Dockerfile

This restores the Jupyter notebook config for local Grapl, which broke when switching to the new Dockerfile from https://github.com/grapl-security/grapl/pull/524.
I ran local Grapl and successfully logged in to the UI.

Notebook fix

---

.github/workflows/grapl-build.yml
Makefile
docker-compose.yml
src/python/grapl_provision/grapl_provision.py
src/python/grapl_provision/provision_local_identity_table.py

https://github.com/grapl-security/issue-tracker/issues/230
-  Change it to a `docker-compose stop` not `down` for integ tests
- Add the dump command to the github workflow 
CI on this build

Dump logs for integration tests so we can see why grapl-provision seemingly fails

---

BUILDING.md
Makefile
docker-compose.yml
src/rust/Dockerfile
test/docker-compose.integration-tests.yml
test/docker-compose.unit-tests-rust.yml

The Rust Dockerfile had a param named `PROFILE`, which AWS tooling also uses for it's own purposes. This renames to help avoid name collision.
tested locally by running `make test` after having first ran `make clean`.

Rename the Rust Docker param PROFILE to CARGO_PROFILE

---

src/js/grapl-cdk/deploy_all.sh

None
We had a flag conflict between Cargo and `deploy_all` both using the `PROFILE=` env var.
We already renamed the cargo one to CARGO_PROFILE, so the bug is fixed ( https://github.com/grapl-security/grapl/pull/569 ) - but it makes sense to specialize the AWS profile to AWS_PROFILE= as well.
locally

Rename the profile env var

---

src/rust/metric-forwarder/src/accumulate_metrics.rs

A transient failure in https://grapl-internal.slack.com/archives/C0176MS6LBY/p1611158138042600 is odd and hard to repro/debug.
These fancier Err statements will help us debug why it fails in the future.

Add more debuggability to accumulate_metrics tests

---

src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/lib/pipeline_dashboard.ts

Current dash only shows cpu/mem for Fargate, not super useful.
The idea is that this would help operators (us) detect where in the flow stuff breaks
(except dispatch and executor positions are switched now)

Grapl Pipeline dashboard refreshed for sqs fargate

---

Makefile
test/docker-compose-with-error.sh

This resolves an issue where integration and e2e tests were properly being cleaned up, causing subsequent tests to fail, as well as cleaning up that logic by moving that to the test wrapper and out of the Makefile.
- I ran `make test` locally with great success.
- I started running the integration test, let the grapl environment finish coming up, then CTRL+C and verified the script gracefully brought stopped the grapl env before exiting.

Move test cleanup to the test wrapper, removing that and exit code logic from the Makefile.

---

.github/etc/cargo-audit/Dockerfile
.github/workflows/cargo-audit.yml
.github/workflows/grapl-build.yml
BUILDING.md

We don't want failing `cargo audit` jobs to block our regular builds,
and we also don't need them running all the time.
Here, we schedule it to run every week.

Run `cargo audit` job on a schedule

---

.github/workflows/cargo-audit.yml

TIL strings must be single-quoted in Github Actions

Fix cargo audit Github Actions workflow

---

.github/workflows/grapl-build.yml
src/python/grapl_e2e_tests/tests.py

None in particular
- Retry the e2e tests 3x.
- Allow for the "lens with scope 3, not 4" case, which means the pipeline is moooostly working.
Basically, the hope is that we'll get fewer false negatives ("IT'S BROKEN BECAUSE OF SOMETHING YOU DID AHHHH!!!!") from these tests, which are relatively useless right now from the standpoint of providing confidence in your PR
creating this PR and looking at its CI

Get higher signal out of the flaky e2e tests - retries, and allow for a semi-failure

---

docker-compose.zips.yml

Make target `zip` broke recently with docker context changes. This fixes that.
I can `make deploy`, which first calls the `zip` target, which now succeeds.

Fix Rust context for zip creation, which changed recently.

---

.github/workflows/grapl-build.yml

Just to ensure we don't inadvertently break the build logic.

Ensure that Lambda ZIPs build in CI

---

.dockerignore
src/.dockerignore
src/js/engagement_view/.dockerignore
src/js/graphql_endpoint/.dockerignore
src/js/grapl-cdk/.dockerignore
src/python/graplinc-grapl-api/.dockerignore
src/rust/.dockerignore

https://github.com/grapl-security/issue-tracker/issues/236
This unifies our .dockerignore files.
I ran a clean build and verified the context size transferred for the Rust build didn't include my `target` directory. Verified by compared sizes.

Consolidate the .dockerignore files

---

src/js/grapl-cdk/lib/services/analyzer_dispatcher.ts
src/js/grapl-cdk/lib/services/graph_merger.ts
src/js/grapl-cdk/lib/services/node_identifier.ts
src/js/grapl-cdk/lib/services/osquery_graph_generator.ts
src/js/grapl-cdk/lib/services/sysmon_graph_generator.ts

None
We were passing an autogenerated id to `serviceName` for FargateService when, in fact, we should just be passing the service name.
Don't worry, it adds the prefix for us :) 
I'm `make deploy`ing as we speak

Fargate cluster names don't have autogenerated ids

---

.github/workflows/cargo-audit.yml

The `actions-rs/audit-check` action doesn't appear to be able to run
in a subdirectory, and Github Actions' `working-directory` doesn't
apply to `uses` steps. Until either of those change, we'll just do it
ourselves.
Longer term, it would be nice to use that action, though, because it's
got much nicer output. In the meantime, however, this will serve our
purposes.

Ensure that `cargo audit` is run from the proper directory 

---

src/js/grapl-cdk/lib/fargate_service.ts
src/js/grapl-cdk/lib/historydb.ts
src/js/grapl-cdk/lib/schemadb.ts
src/js/grapl-cdk/lib/services/analyzer_dispatcher.ts
src/js/grapl-cdk/lib/services/graph_merger.ts
src/js/grapl-cdk/lib/services/node_identifier.ts
src/js/grapl-cdk/lib/services/osquery_graph_generator.ts
src/js/grapl-cdk/lib/services/sysmon_graph_generator.ts

partial revert of https://github.com/grapl-security/grapl/pull/590/files
trying to investigate https://github.com/grapl-security/issue-tracker/issues/242
- Remove the (probably good, but more entropy) connection/tcp changes made in #590. This will help us ensure that, well, these changes are not responsible for `graph-merger` failing to work: https://grapl-internal.slack.com/archives/C01870CFDEC/p1613031116031200
- But keep the Rust dockerfile changes.
- (also, fix one missed `id` swap out for `service_name`) in node-identifier
they were not.

Revert part of #590, to reduce entropy during the search for 'why does graph merger fail to connect' debugging

---

docker-compose.yml
docker-compose.zips.yml
src/js/engagement_view/Dockerfile
src/js/graphql_endpoint/Dockerfile
src/js/grapl-cdk/Dockerfile
test/docker-compose.unit-tests-js.yml

#589 failed to account for some of our build images which still used different build contexts than `src/`
By removing those `.dockerignore`s, stuff is now breaking **on developers' machines** that might have large build contexts, e.g.
```
=> CANCELED [grapl-cdk-test internal] load build context                                                                                                                          78.1s
=> => transferring context: 3.10GB   (it was getting bigger and bigger due to node_modules not being excluded)
```
Standardizing on src/ will fulfill the initial intent of 589.
some discussion around
https://grapl-internal.slack.com/archives/C0176MS6LBY/p1613083243265500

All docker-compose images are done with build context src/

---

.gitignore
test/Dockerfile
test/cypress.json
test/cypress/integration/sample_spec.js
test/docker-compose.integration-tests.yml

Re-enables Cypress, per #231.
`make test-integration` should conclude with running Cypress, within Docker.
Should run 3 tests, all of which pass.

#231, reenable Cypress

---

Makefile

This removes unused environment variable from the Makefile.
I ran `make test-unit` locally and will rely on github tests for the rest.

Remove unused env vars from Makefile.

---

docs/setup/aws.md
src/js/grapl-cdk/bin/create_edge_ux_package.ts
src/js/grapl-cdk/bin/deployment_parameters.ts

We had three different environment variables to store the AWS deployment name across the codebase. This consolidates them to a single variable.
I ran `make deploy` on an existing deployment to ensure these changes didn't break the CDK. Other changes were to documentation steps, which I also ran.

Consolidate on deployment name environment variable.

---

src/js/grapl-cdk/lib/services/graph_merger.ts

We observed connection issues between the graph merger and DGraph swarm. @wimax-grapl noticed the swarm security group didn't have inbound rules to allow connections from the graph merger Fargate service, even though it looked like we should: https://github.com/grapl-security/grapl/blob/ebe6e805366a8232763f703a57a8f5d74d059af2/src/js/grapl-cdk/lib/services/graph_merger.ts#L78.
I'd tried passing the Fargate service itself as an argument instead of the Cluster, which also implements `IConnectable`, thinking there may be two different Security Group definitions under the hood. That seems to have worked.
I'd update my deployment with this diff and noticed my swarm SG now had entries for the graph merger services. I then uploaded the `etc/sample_data/events6.xml` sample data file, which I …

CDK: Pass Fargate service for allowing Security Group connections instead of Cluster

---

src/js/grapl-cdk/lib/fargate_service.ts
src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/lib/services/analyzer_dispatcher.ts
src/js/grapl-cdk/lib/services/graph_merger.ts
src/js/grapl-cdk/lib/services/node_identifier.ts
src/js/grapl-cdk/lib/services/osquery_graph_generator.ts
src/js/grapl-cdk/lib/services/sysmon_graph_generator.ts

results:
None, just existing TODOs
- Manually name the Fargate Services' log groups
- reintroduce metric forwarder props to FargateService
- I saw the lambda being triggered by these.
- However, turns out the m-f lambda is currently broken:  https://github.com/grapl-security/issue-tracker/issues/249

Better LogGroup names for Fargate; reintroduce Metric Forwarder

---

Makefile

When we invoke `docker-compose` multiple times with the same project
name, but different files, we see warnings about the presence of
"orphan containers". Any time `docker-compose` runs and finds services
in a project, but that aren't defined in the file(s) it is currently
operating, it regards them as "orphans".
Since we run two compose runs (once to set up an environment, and once
to execute a series of tests within that same environment), we trigger
this "orphan" detection. In our case, this is expected and not an
issue for concern.
To remove potentially confusing warning messages, we can selectively
ignore orphans in these tasks by setting task-specific environment
variable overrides.

Ignore orphan containers in targets with multiple compose runs

---

src/js/grapl-cdk/lib/service.ts

https://github.com/grapl-security/issue-tracker/issues/249
Change the runtime to Amazon Linux 2
We removed musl and now depend on glibc, which `provided` doesnt provide but `provided.al2` does
aws deploy - I saw the lambda running and i saw results showing up in cloudwatch.

Rust zips (just Metric Forwarder) now use Amazon Linux 2, which provides glibc

---

docker-compose.yml

A recent diff accidentally removed the host port binding to the local grapl environment. This restores those mappings.
Additionally, I removed `ports` specs from services that seem like they don't need to be accessible from the host. This is so the host ports won't be bound.
Andrea initially identified in the issue. Making similar changes resolved that for her.
Also, I ran `make test-integration` locally with great success.

Restore host port binding to containers for local grapl environment

---

.github/workflows/grapl-release.yml
.github/workflows/grapl-staging-release.yml
Makefile
docker-compose.build.yml
docker-compose.yml

Building containers and running containers are separate tasks, and
combining them into one `docker-compose.yml` file isn't necessarily
useful.
In particular, all the environment variables declared in
`local-grapl.env` are concerned with how the containers should run,
and have nothing to do with how they are built. When we release
containers, we shouldn't need to provide a bunch of unnecessary
variables just so `docker-compose` can parse the file.
Here, we extract a `docker-compose.build.yml` file from
`docker-compose.yml`. Each service only defines a `build`
component. These are exactly the same `build` components that existed
in `docker-compose.yml` before. Additionally, no non-Grapl
services (e.g, Dgraph, Redis) are defined, since those are operational
concerns.
Correspondingly, all the …

Fix release image push

---

debugger/Dockerfile
debugger/Makefile
debugger/README.md
debugger/attach.sh

Adds a container full of handy debugging tools, as well as a script to
make it easy to attach to an existing container for debugging
purposes.
Fixes https://github.com/grapl-security/issue-tracker/issues/109

Add a debugging container

---

src/rust/Cargo.lock
src/rust/sqs-executor/src/cache.rs
src/rust/sqs-executor/src/redis_cache.rs

Internally requested: Update the `Cache` trait `get_all` method to return `Vec<(Cacheable, CacheResponse)>` instead of just `Vec<CacheResponse>` to make it easier to determine which elements need to be actioned on.

Update cacheT interface to return cacheable alongside cacheresponse

---

src/rust/sqs-executor/src/cache.rs

Not sure if it's worth creating an issue to track time spent on this PR.
This adds `#[derive(Eq, PartialEq)]` to `sqs-excutor::cache::CacheResponse`. This should enable us to do things like:
```
resp == CacheResponse::Miss
```
I ran `make test-unit-rust`.

Add #[derive(Eq, PartialEq)] to sqs-excutor::cache::CacheResponse.

---

docker-compose.yml

https://github.com/grapl-security/issue-tracker/issues/257
Opens up ports required for SQS and Ratel interface to operate on local grapl
Ran `make up` locally to verify that:
* I was able to upload logs to local sqs using `upload-sysmon-logs.py`
* I was able to access and interact with the ratel interface on port 8000 (which uses port 8080 for running queries)

Fix missing ports

---

etc/local_grapl/nginx_templates/default.conf.template

https://github.com/grapl-security/issue-tracker/issues/258
Fixes a host being passed in where a port is expected
I was able to log in locally, thus demonstrating the fix.

Internal 258 nginx port

---

src/python/analyzer_executor/tests/test_sqs_timeout_manager.py

https://github.com/grapl-security/issue-tracker/issues/268
Basically, we have this fixture that - by default - creates an instance of a coroutine (but doesn't run it).
Pytest helpfully lets you know when you've done this, as it usually implies a programming error.
However, in this case, it's a red herring.
make test-unit-python

Shush a harmless warning for 'coroutine was never awaited' in analyzer-executor

---

src/rust/generators/sysmon-subgraph-generator/src/generator.rs
src/rust/sqs-executor/src/errors.rs

- https://github.com/grapl-security/issue-tracker/issues/271
- https://github.com/grapl-security/issue-tracker/issues/265
In fixing 271, we provide two ways for users to check the type. They could use helper functions we've added to the type, or they can now check for equality now that `Eq` and `PartialEq` are derived for the type enum.
In order to resolve 265, we first needed to resolve 271. The fix is a little awkward, which is its own issue being tracked at https://github.com/grapl-security/issue-tracker/issues/269. The fix is for the generator to prefer to return a `Recoverable::Transient` error over a `Recoverable::Persistent` error.
I only ran the local tests.

Sqs executor error helpers

---

docker-compose.yml

The local Grapl docker-compose file would bind host ports on all interfaces, which isn't necessary and overly exposes services.. This binds them to the loopback interfaces only.
I ran `make up` and noticing we were binding each service to loopback only. The Grapl UI was still accessible at localhost:1234.

Have docker-compose bind host ports to loopback only

---

Makefile

https://github.com/grapl-security/issue-tracker/issues/235
Add a new mechanism to the makefile that makes spinning up integration tests easier
locally

Introduce a 'make up-detach' for integration tests (particularly, for Cloudtrail e2e to consume)

---

src/js/grapl-cdk/lib/fargate_service.ts

https://github.com/grapl-security/issue-tracker/issues/285
This changes the LogGroup removal policy to DESTROY. By default the log groups persist after CloudFormation stack removal, which will cause a later deployment of the same name to fail.
Alternative to this solution, it seems we could check `fromLogGroupName` and use that if found before trying to create a new one, but I'm not sure we want these log groups around after removing a stack anyway.
I have the same code for this in a generator in external repo, where I tested this diff. With these changes the issue was resolved.

change Fargate service LogGroup removal policy to DESTROY

---

src/js/grapl-cdk/deploy_all.sh
src/js/grapl-cdk/package-lock.json

This adds `npm install` to the CDK `deploy_all.sh` script. This will help ensure the appropriate packages are installed before trying to build and deploy. If all packages are already installed this only takes a few seconds, which is noise compared to the `cdk deploy` step.
After running `npm install` on staging I noticed the package-lock.json file changed, which was unexpected. I also had a warning to update my version of npm from 6.14.11 to 7.6.0 and ran `npm install` again. This resulted in the changes to package-lock.json in this PR.
I ran `make deploy` on top of an existing deployment, which succeeded.

Add 'npm install' to CDK deploy_all.sh

---

buf.yaml

The `Edge#edgeName` field was renamed in #561 so we no longer need to
ignore any lints.
See https://github.com/grapl-security/issue-tracker/issues/237

Remove `allow_comment_ignores` from buf.yaml

---

src/python/grapl_e2e_tests/tests.py

None
Make e2e tests allow any answer from 3 to 5.
It is now too performant and actually shows us that 5 is possible and probably the right answer.
Yes i considered using range([start, end)) but whatever
CI

E2e tests: our 'correct' answer was wrong, it's actually 5

---

.gitignore
EDITOR_SETUP.md
Makefile
build-support/BUILD
build-support/editor_setup.py
pants.toml

https://github.com/grapl-security/issue-tracker/issues/320
Adds instructions on how to set up editors for efficiently working with our Python code. This includes some tooling to make it easier to keep this information up-to-date as we mature our use of Pants.
Read the individual commit messages for further details.
```sh
build-support/editor_setup.py pyright generate
```

Add instructions, tooling to aid editor setup for Python code

---

src/rust/Dockerfile

This does a couple things to improve subsequent builds for Rust:
- installs the Rust toolchain before copying sources
- adds the local cargo registry to the Docker mount cache to prevent re-downloading dependencies.
I tested these locally by running `make build-test-unit-rust` with slight modifications to one of the Rust libraries.

Rust Dockerfile tweaks

---

docker-compose.yml
docs/analyzers/deploying.md
etc/local_grapl/bin/upload-osquery-logs.py
etc/local_grapl/bin/upload-sysmon-logs.py
etc/local_grapl/bin/upload_analyzer_local.sh
local-grapl.env
pulumi/README.md
pulumi/infra/ux.py
src/js/engagement_view/upload_localhost.sh
src/python/grapl-ux-router/src/grapl_ux_router.py

In order to more closely mimic AWS in our testing environments, we need a way to implement our bucket notifications to SNS topics. As long as we are using MinIO, we can't do that.
This PR replaces MinIO with Localstack's built-in S3 implementation, which should allow this. This removes testing infrastructure, and also allows us to start removing a bunch of special-casing in our code, starting with the website bucket configuration logic in our Pulumi code, as well as modifying certain Pulumi stack configuration values.
One interesting aspect of this was that we needed to strip the leading `/` from the S3 object keys (derived from URL paths) in our `grapl-ux-router` code. Apparently, MinIO was able to deal with finding an object named "/static/js/2.642cd0fc.chunk.js", whereas Localstack is …

Remove MinIO in favor of Localstack's S3 implementation

---

build-support/manage_virtualenv.sh

```sh
build-support/manage_virtualenv.sh populate
direnv allow
which python # should be a path in our virtualenv
```

Add instructions for activating our virtulenv with direnv

---

src/python/engagement_edge/tests/test_engagement_edge.py
src/python/grapl-tests-common/grapl_tests_common/clients/engagement_edge_client.py
src/python/grapl-tests-common/grapl_tests_common/clients/graphql_endpoint_client.py
src/python/grapl-tests-common/grapl_tests_common/setup.py
src/python/grapl_e2e_tests/tests.py
test/docker-compose.e2e-tests.yml

None yet.
- Add a rudimentary GraphqlEndpointClient to grapl-tests-common
- Add a rudimentary test that, yes, it loads lenses okay
- Remove some `use_docker_links=` stuff that's no longer applicable
I would like to have integration tests on it within the graphql endpoint source tree, but right now, this is a low-effort/high-ROI addition that ensures the endpoint hasn't broken.
its all tests dude!!!

Added a graphql endpoint test to e2e tests, just so we have *some* coverage on it

---

Makefile
test/docker-compose-with-error.sh

In trying to clean a local environment by `make down`, docker-compose would fail in trying to remove the docker network. This would be due to the Grapl local environment still being up after tests were done running, so containers were still running that were using the network. 
```
Removing network grapl-network
ERROR: error while removing network: network grapl-network id 6b829bd70b1b4fd4ae89bb89c37219b38039f06b4e472be72f19e0e202bbd852 has active endpoints
make: *** [Makefile:285: down] Error 1
```
These changes do a few things:
1. Remove from the test wrapper the code that would stop test containers and move that functionality into the Makefile. We still have some functionality of that wrapper in a script, but it only checks the exit codes of containers now.
2. Set .ONESHELL in the …

Fix 'make down' by running with the various project names that we use

---

src/rust/Dockerfile

https://github.com/grapl-security/issue-tracker/issues/355
This removes the Cargo local registry from the docker build cache mount, which was originally put in place to help prevent from redownloading dependencies when iterating on Rust sources. However, this had the side-effect of https://github.com/grapl-security/issue-tracker/issues/355 because the Rust `target` directory was no longer available to the running containers, so cargo couldn't verify the test builds were up to date. Because it can't verify, it rebuilds. Not worth.
I ran `make test-unit-rust` and `make test-integration` locally and noticed the Rust test code is not recompiling at runtime. Also, I see similar for the GitHub actions from the PR as it is now: https://github.com/grapl-security/grapl/runs/2179081186?check_suite_f …

Revert 70ba3533ee422166edcf2c556f15404a59039024

---

Makefile

None filed (yet?), but I noticed https://github.com/grapl-security/grapl/pull/692 doesn't quite achieve what it was meant to. The test containers, although stopped, will still exist after running make down. This is apparently due to not passing each compose file used for each project.
For running docker-compose down, run by passing `EVERY_COMPOSE_FILE` to help ensure all containers are covered.
Additionally, this explicitly sets a default value for `COMPOSE_PROJECT_NAME` to `grapl`, which should be the same as what we currently expect. docker-compose will use the directory name that holds the compose file, which is still "grapl" in most cases, but not for those under `test/`. This helps ensure all container names created by us will be prefixed with "grapl", which makes cleanup easier.
I …

Make down again

---

docs/setup/aws.md
src/js/engagement_view/Dockerfile
src/js/graphql_endpoint/Dockerfile

- Add AWS provision command to AWS documentation 
- Resolve newly introduced bugs with dockerfiles that were preventing successful deployments for `graphqlEndpoint` because we weren't including `node_modules` so we weren't able to use dependencies
Docs: N/A
Package Manager: Locally & AWS  off a different branch ( did not test this branch in AWS, but tested these changes in a different branch - wanted to add them here in case someone else runs into these issues before the PR fixing them goes up )

add provisioning back to docs, fix dockerfiles for aws deployments

---

docs/setup/aws.md
src/js/graphql_endpoint/Dockerfile

Add instructions for generating password for grapl in AWS.
Remove line in graphql dockerfile per Max - this is not necessary (was introduced in https://github.com/grapl-security/grapl/pull/710) earlier today.
N/A - Documentation Changes

Add login instructions to aws deployment

---

docker-compose.lambda-zips.python.yml
src/js/grapl-cdk/lib/services/engagement_creator.ts
src/python/Dockerfile

Back when we started generating the ZIP file for this service with Pants, I neglected to update CDK to take the new handler into account. This fixes that, and also removes the old container-based ZIP file build (which didn't use Pants).

Fix engagement creator Lambda handler in CDK

---

src/rust/Dockerfile

https://github.com/grapl-security/issue-tracker/issues/374
1. This removes a gratuitous build stage we had in the Rust Dockerfile.
2. We had a bogus expansion of `TARGET` in the Rust Dockerfile, which is no longer used. This apparently was harmless, as the path resovles the same, but still doesn't make sense to be there.
I verified the Rust builds with Docker still work by running `make test-unit-rust`. I'll rely on CI tests for the rest.

Rust dockerfile fixes

---

src/python/grapl_analyzerlib/grapl_analyzerlib/test_utils/strategies/misc.py

https://grapl-internal.slack.com/archives/C0176MS6LBY/p1617301403291500
`hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: Only produced 4 valid examples in 1.01 seconds (7 invalid ones and 0 exceeded maximum size). Try decreasing size of the data you're generating (with e.g.max_size or max_leaves parameters).`
- Stop assuming len > 3, when we're generating len-3 strings
it's all about tests

Minor change to hypothesis tests - stop generating 3-char strings and assuming len > 3

---

pulumi/infra/bucket.py
pulumi/infra/emitter.py
pulumi/infra/ux.py

Uses more conventional `pulumi.ResourceOptions` arguments, rather than
simply providing a parent resource explicitly.
Also adds several permission-granting methods that will come in handy
as we move more infrastructure over to Pulumi.

Refactor bucket abstraction in Pulumi

---

Makefile
docker-compose.lambda-zips.python.yml
docker-compose.yml
pulumi/Pulumi.local-grapl.yaml
pulumi/__main__.py
pulumi/infra/dgraph_ttl.py
src/js/grapl-cdk/lib/services/dgraph_ttl.ts
src/python/Dockerfile
src/python/grapl-dgraph-ttl/BUILD
src/python/grapl-dgraph-ttl/grapl_dgraph_ttl.py

This also entails:
- Building the lambda ZIP using Pants
- Changing the handler name in our CDK code accordingly
- Renaming app.py to grapl_dgraph_ttl.py for use with Pants
We've got another `app.py` module elsewhere at the same level, so
that ends up clashing in Pants' dependency resolution logic.
- Removing old ZIP-building services and Docker containers
- Removing the standalone "local" DGraph TTL service from Local Grapl
- Removing the `IS_LOCAL` logic from the service

Add DGraph TTL service to Pulumi

---

docker-compose.yml
local-grapl.env
src/js/grapl-cdk/lib/services/analyzer_dispatcher.ts
src/js/grapl-cdk/lib/services/graph_merger.ts
src/js/grapl-cdk/lib/services/node_identifier.ts
src/js/grapl-cdk/lib/services/osquery_graph_generator.ts
src/js/grapl-cdk/lib/services/sysmon_graph_generator.ts
src/rust/Cargo.lock
src/rust/Dockerfile
src/rust/generators/generic-subgraph-generator/src/generator.rs
src/rust/generators/sysmon-subgraph-generator/src/generator.rs
src/rust/graph-merger/src/main.rs
src/rust/graph-merger/src/service.rs
src/rust/grapl-config/src/lib.rs
src/rust/node-identifier/src/lib.rs
src/rust/sqs-executor/Cargo.toml
src/rust/sqs-executor/src/cache.rs
src/rust/sqs-executor/src/lib.rs
src/rust/sqs-executor/src/redis_cache.rs
src/rust/sqs-executor/tests/redis_cache.rs
test/docker-compose.integration-tests.yml

This all started to resolve the following, but a number of other enhancements were made along the way:
- https://github.com/grapl-security/issue-tracker/issues/344
This PR not only swaps darkredis for redis-rs in the sqs-executor, it makes significant changes to the cache API:
- Remove the `get` public methods and `CacheResponse` and replace with a new method `filter_cached`. The `get` methods weren't actually "gets", and we aren't really storing values for keys. Users of the `get` methods, like generators, would partition the keys that weren't in the cache and continue to process those. Instead of requiring users to do this parsing, we now provide `filter_cached`.
- Add an `all_exists` method to the cache API, another helper that some users were previously using the `get` methods.
- The …

Rust sqs-executor cache changes

---

.gitignore
test/docker-compose.integration-tests.yml

1. The Cypress tests currently leave git in a dirty state after run:
```
Changes not staged for commit:
(use "git add/rm <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
deleted:    test/integration-outputs/screenshots/.gitkeep
deleted:    test/integration-outputs/videos/.gitkeep
```
https://github.com/grapl-security/issue-tracker/issues/386
2. Cypress test outputs are owned by root. 
https://github.com/grapl-security/issue-tracker/issues/385
This comments out the Cypress tests for now, because of the issues noted above, and because the results are being swallowed anyway (https://github.com/grapl-security/issue-tracker/issues/387). We can add these tests back in after the issues are resolved.
I ran `make …

Temporarily disable Cypress tests

---

etc/ci_scripts/install_requirements.sh

NA
This removes the Docker version update in that we were doing in CI, as it's no longer needed.
In addition, add notes about how adding software version updates should be tracked with housecleaning tickets, so that we can come back and remove in the future as the versions installed on the runners cover those we require.
Change to CI script only, will rely on CI tests.

Remove Docker version update in CI script. Add note for future use.

---

src/js/engagement_view/src/components/reusableComponents/notifications/Notifications.tsx

none
the login thing on the right side used to push the 3 buttons to the left; now, it's inside a Popover element, so it behaves as expected.
browser

Engagement UX: login card is now in a popover (floats on screen)

---

Makefile

https://github.com/grapl-security/issue-tracker/issues/394
This explicitly sets the Makefile shell to `bash` and changes how we're setting shell options, in order to resolve the issue and have Make error immediately upon error and with proper exit code.
I ran `make test`, `make up`, and `make down` to ensure those all still behaved correctly, and I created a test target with two lines, the first of which finishes with exit code 1, to ensure Make would exit there.

In the Makefile remove SHELLOPTS, set SHELL = bash, set SHELLFLAGS.

---

docker-compose.yml
pulumi/Pulumi.local-grapl.yaml
pulumi/__main__.py
pulumi/infra/dgraph_ttl.py
pulumi/infra/engagement_creator.py
pulumi/infra/lambda_.py
pulumi/infra/metric_forwarder.py
pulumi/infra/network.py
pulumi/infra/queue_driven_lambda.py
pulumi/infra/service.py

This replicates (to the best of my knowledge) the infrastructure that
was generated for us by CDK's VPC construct:
- One VPC
- 2 public subnets, 2 private subnets, one each in two separate
availability zones
- 1 internet gateway
- 1 NAT gateway
- Each lambda function gets a dedicated Security Group, as well as
access to both private subnets.

Add VPC infrastructure to Pulumi, Localstack

---

Makefile

The Makefile was referencing a file that no longer exists. This removes that reference.
I'll rely on CI tests.

Remove no-longer-existing file from `EVERY_COMPOSE_FILE` in Makefile.

---

Makefile
test/docker-compose-with-error.sh

None
- Users can now specify `TARGETS="service1 service2" make test-something` in order to only run a subset of tests.
- Add documentation:
Ran on my machine with
no TARGETS specified
TARGETS=something real
TARGETS=something fake

Make `TARGETS=` universal to any docker-compose-with-error.sh consumer; add documentation

---

Makefile

its hack week
KEEP_TEST_ENV=1 make test-e2e
will preserve the test environment
this is *super useful* for, say, manually logging in to engagement-UX afterwards and wanting to see how it renders the data (events.xml) 
locally, with and without KEEP_TEST_ENV

KEEP_TEST_ENV=1 to keep environment after running a test

---

.github/workflows/grapl-build.yml
.gitignore
Makefile
etc/ci_scripts/dump_artifacts.py

With the addition of lambda functions to our Local Grapl setup, we need to adjust how we're capturing logs to make it easier to debug issues. In particular, we must capture lambda output from the Localstack instance's Cloudwatch endpoint while it is still running.
Here, we modify the `dump_artifacts.py` script to take this into account. It dynamically determines which lambda functions are running (based on the containers that Localstack spins up for them) and runs the appropriate `aws` CLI command to dump the logs.
Also added in this PR is a change to dump artifacts into a timestamped directory, rather than always using `/tmp/dumped_artifacts`. This is particularly important for our coming Buildkite rollout, because a given runner may service multiple test runs over its lifetime. If we …

Tweak log dumping script to account for Lambda functions, Buildkite migration

---

docs/setup/aws.md

https://github.com/grapl-security/issue-tracker/issues/402
This just adds the CDK bootstrap steps to the AWS setup docs.
I ran the commands in the I've documented for an AWS deployment. My account apparently needed bootstrapping and this resolved that.

Re add AWS CDK bootstrap steps to AWS setup doc.

---

Makefile
docker-compose.build.yml
docker-compose.lambda-zips.python.yml
docker-compose.yml
etc/local_grapl/nginx_templates/default.conf.template
local-grapl.env
pants.toml
pulumi/infra/api.py
pulumi/infra/ux_router.py
src/js/grapl-cdk/lib/ux_router.ts
src/python/Dockerfile
src/python/grapl-ux-router/BUILD
src/python/grapl-ux-router/src/grapl_ux_router.py
src/python/grapl-ux-router/src/lib/BUILD
src/python/grapl-ux-router/src/lib/env_vars.py

Additionally, build the ZIP with Pants, remove some Docker
infrastructure for building ux-router images, and also simplify the
ux-router code a bit (mainly by moving the content of `env_vars` into
the main module).

Put UX Router behind the API Gateway

---

etc/ci_scripts/dump_artifacts.py

Turns out this only reliably works in a virtualenv where `python` is
actually Python 3. Outside of that, the `python` binary is generally
of the 2.x flavor, which causes failures.
A thousand apologies.

Fix the shebang line in dump_artifacts to explicitly use Python 3

---

docker-compose.yml

Previously, we were using an internally-built Localstack container
with a patch for calling our Chalice lambdas. Since then, the real fix
has landed in the main Localstack repository (possibly addressing some
additional lambda invocation related behavior that we also need, which
was not addressed in our custom container).
For now, these fixes are only available on the `latest` containers,
but in the interest of getting back on the official codebase, we'll
use this until Localstack 0.12.11 is formally released.

Switch back to official Localstack container

---

Makefile

This poorly named variable should not contain that docker-compose file (which, also, is not in test/)

Remove an incorrect entry from makefile

---

src/rust/node-identifier/src/dynamic_sessiondb.rs
src/rust/node-identifier/src/lib.rs

Part of Node Identifier Improvements
Changes statically identifiable nodes to use hashing instead of tracking node keys in dynamodb. As nodes with static identification strategies *must* be unique for a given set of static properties, we can hash these properties in a predictable order to avoid reaching out to dynamodb.
Integration tests + Unit Tests

statically identifiable nodes use hashing instead of dynamodb

---

docker-compose.yml
etc/ci_scripts/dump_artifacts.py

https://github.com/grapl-security/issue-tracker/issues/420
- Increase localstack startup period before it starts failing healthcheck
- while debugging the above issue I had to make an assumption about the identity of a contianer hash; to avoid that in the future we're writing `docker ps` to the artifacts.
throw it on CI and see what happens

Bump up Localstack startup period; write docker ps results

---

.buildkite/scripts/integration.sh
Makefile
docker-compose.build.yml
docker-compose.lambda-zips.rust.yml
src/js/grapl-cdk/lib/services/analyzer_dispatcher.ts
src/js/grapl-cdk/lib/services/graph_merger.ts
src/js/grapl-cdk/lib/services/node_identifier.ts
src/js/grapl-cdk/lib/services/osquery_graph_generator.ts
src/js/grapl-cdk/lib/services/sysmon_graph_generator.ts
src/rust/Dockerfile
test/docker-compose.integration-tests.yml
test/docker-compose.unit-tests-rust.yml

This changes the Rust Dockerfile to better leverage cache mounts by using them for the following:
1. The Cargo `target` directory, instead of using sccache and its local directory
2. The Cargo local registry. This prevents from having to redownload Rust sources on subsequent builds.
3. The Apt local repository. This prevents from having to redownload OS packages on subsequent builds.
To make this work, we need to save the `target` and Cargo local registry directories in the final image used for Rust tests in containers, so we have steps to copy them to temp directory and move them back before finishing.
This speeds up Rust builds for both clean builds and subsequent builds with changes (measured on my local machine):
| | Main  | This PR |
| ------------- | ------------- | ------------- | …

Use Docker mount cache for Rust builds

---

src/js/grapl-cdk/lib/fargate_service.ts
src/js/grapl-cdk/lib/grapl-cdk-stack.ts
src/js/grapl-cdk/lib/pipeline_dashboard.ts

https://github.com/grapl-security/issue-tracker/issues/401
- Remove `defaultCapacity` in favor of `min/maxScalingCapacity`, and flip on some sort of feature flag surrounding that
- will port to Pulumi once cm done with main fargate pulumi stuff
Tested behavior in AWS, it works :)

Fargate: Default services scale [1..4], retry services scale [0..4]. CDK only!

---

pulumi/infra/lambda_.py
pulumi/infra/metric_forwarder.py

Doesn't change any functionality, but prepares for when we add Fargate services, which will need the same metric forwarding.

Put forwarder-related infrastructure into MetricForwarder class

---

Makefile
src/python/Dockerfile
src/python/engagement_edge/requirements.txt
src/python/mypy.ini
test/docker-compose.typecheck-tests.yml

Typecheck grapl-common and engagement-edge using Pants, removing the components of the Docker build setup that were handling that.
While there are additional projects that we can typecheck with Pants, they are things that are not currently typechecked, and thus have some type failures. Those can follow later.
This is in support of removing all the extra code in place that Pants can handle now.

Typecheck more code with pants

---

pulumi/infra/emitter.py

Apparently, a TopicPolicy must exist before a BucketNotification is
created. Since the Pulumi resource does not have a direct dependency,
we have to declare one manually using `depends_on`.
This has worked many times in the past; my (unproven) hypothesis is
that maybe something got tightened up in the underlying AWS
interaction library between Pulumi 2.x and 3.x.
Fixes https://github.com/grapl-security/issue-tracker/issues/449

Tighten up dependency order with bucket notifications

---

src/rust/metric-forwarder/src/accumulate_metrics.rs

None, but
https://grapl-internal.slack.com/archives/C0176MS6LBY/p1620424222288400
Turns out, my metric accumulator nondeterminstically fails.
Instead of wasting time fixing it, I'm going to leave it broken and disable the test.
Why?
Near future has us moving off Cloudwatch logs for metrics and into something like Kafka, which does its own aggregation
I ran `make test-unit-rust` and ensured there was 1 ignored
grapl-rust-test_1  | running 17 tests
grapl-rust-test_1  | test accumulate_metrics::tests::test_buckets_diff_tags_differently_nondeterministic_fail ... ignored
grapl-rust-test_1  | test accumulate_metrics::tests::test_buckets_diff_names_differently ... ok
grapl-rust-test_1  | test cloudwatch_logs_parse::tests::test_parse_one_log ... ok
grapl-rust-test_1  | test …

Disable flaky Rust test

---

3rdparty/python/requirements.txt
src/python/grapl-tests-common/setup.py

We've noticed some issues with later releases that appear to result
from problems building with native dependencies. Until we sort that
out, we'll pin to the last known good version (which is already in our
constraints.txt file)

Pin zstd at 1.4.9.1

---

pulumi/__main__.py
pulumi/infra/lambda_.py
pulumi/infra/network.py
pulumi/infra/provision_lambda.py
pulumi/infra/swarm.py
src/python/grapl-common/grapl_common/grapl_logger.py
src/python/grapl-common/grapl_common/utils/benchmark.py
src/python/graplctl/graplctl/dgraph/lib.py
src/python/graplctl/graplctl/swarm/lib.py

https://github.com/grapl-security/issue-tracker/issues/441
- Introduce better abstractions to Ec2Port
- Introduce the Provisioner lambda into pulumi
- add a benchmark utility
- Pulumi Dgraph adds a few new tags
- graplctl consumes these new tags
Provision still doesn't work, but we're getting closer. It gets stuck on SSM - I suspect the cluster isn't allowing 443 correctly or something. This has blocked me for daaaaays
Against AWS

Beginning some work to allow Pulumi Dgraph to be provisioned by graplctl (but doesn't work all the way yet)

---

pulumi/Pulumi.local-grapl.yaml
pulumi/README.md
pulumi/infra/config.py
pulumi/infra/emitter.py
pulumi/infra/engagement_creator.py
pulumi/infra/lambda_.py
pulumi/infra/service_queue.py

Now that we're basically done with the CDK-to-Pulumi migration, this
is no longer needed.

Remove import_aware_opts abstraction

---

pulumi/__main__.py
pulumi/infra/bucket.py
pulumi/infra/dynamodb.py
pulumi/infra/emitter.py
pulumi/infra/engagement_creator.py
pulumi/infra/engagement_edge.py
pulumi/infra/engagement_notebook.py
pulumi/infra/graph_merger.py
pulumi/infra/metric_forwarder.py
pulumi/infra/model_plugin_deployer.py
pulumi/infra/node_identifier.py
pulumi/infra/policies.py
pulumi/infra/provision_lambda.py
pulumi/infra/queue_driven_lambda.py
pulumi/infra/repository.py
pulumi/infra/secret.py
pulumi/infra/service_queue.py
pulumi/infra/swarm.py

You can only have so many IAM policies attached to any given role, which is now causing issues due to how we have been modeling our policies in a relatively granular way. Basically, we have too many policies to attach, and we're exceeding the limit.
Inline policies, using `RolePolicy`, don't have a numerical limit, which makes them a bit more flexible for our purposes. They do have overall size limits, though, which calls for a bit of rethinking. The main change made here in that regard is to grant permissions on multiple DynamoDB tables in a single policy, as opposed to a policy per table as we had been doing before. This gives us the most savings in the case of the node identifier service, which needs access to nine tables.

Use RolePolicies, rather than RolePolicyAttachments

---

pulumi/infra/engagement_creator.py

This is apparently vestigial, as nothing uses it anymore.

Remove engagements-created-topic

---

pulumi/infra/queue_driven_lambda.py
pulumi/infra/queue_policy.py
pulumi/infra/service_queue.py

Ultimately, this allows us to reuse the same logic in the ServiceQueue
and QueueDrivenLambda classes.

Extract queue-related policies into shared module

---

pulumi/infra/network.py

https://github.com/grapl-security/issue-tracker/issues/441
Associate each subnet with a route table.
SSM still doesn't work, but this looks closer to correct than it was previously.
pulumi up

Add route tables to Pulumi network subnets. Still doesn't work, but it's an improvement

---

pulumi/infra/fargate_service.py
pulumi/infra/metric_forwarder.py

They don't need to be reused or referenced, and none of the other
RolePolicy instances are saved either.
This is just for consistency.

Don't bother saving RolePolicy instances as attributes

---

pulumi/infra/bucket.py

None of these GetBucket* permissions appear applicable to anything we
do.

Bucket read/write policy doesn't need s3:GetBucket* at all

---

pulumi/infra/emitter.py

I don't see any evidence of manipulating ACLs, tags, or anything else.

EventEmitter write policy only needs s3:PutObject

---

pulumi/infra/emitter.py

No service that adds objects to an EventEmitter ever needs to
delete any object.

Remove s3:DeleteObject* permissions from EventEmitter

---

pulumi/infra/bucket.py

Also, split permissions up by the resources they apply to.

Bucket read/write policy is actually just CRUD

---

pulumi/infra/engagement_notebook.py

This doesn't change any permissions, but is more explicit.

Engagement Notebook explicitly gets Get and List permissions

---

pulumi/infra/analyzer_dispatcher.py

`grant_get_and_list_to` provides the same permissions as
`grant_read_permissions_to` at the moment, but the latter will
ultimately just end up granting `s3:GetObject`. The analyzer-dispatcher
appears to legitimately need both `s3:GetObject` and `s3:ListBucket`,
however, so this change makes things more accurate and obvious.

Switch analyzer_dispatcher permissions method

---

src/python/grapl_e2e_tests/tests.py

Originally, the directory in question only had one file. Recently, a
`BUILD` file was added, which violated the assumptions of this
particular assertion. It has now been rewritten.

Rework an e2e assertion to account for multiple files

---

pulumi/infra/bucket.py
pulumi/infra/dgraph_cluster.py
pulumi/infra/swarm.py
pulumi/infra/ux_router.py

The only remaining consumers of this function appear to only need the
ability to retrieve objects from a bucket, not list their contents.
This affects the dgraph and swarm config buckets, and the ux bucket.

Remove s3:ListBucket from Bucket#get_read_permissions_to

---

src/python/grapl-common/grapl_common/retry.py
src/python/grapl-tests-common/grapl_tests_common/wait.py
src/python/graplctl/graplctl/cli.py
src/python/graplctl/graplctl/dgraph/lib.py
src/python/graplctl/tests/shared.py

None
There's a step where we try to create Cloudwatch alarms based off EC2 metrics.
Previously we waited a straight 5 minutes.
Now, we check for valid state every 30 seconds, up to 5 minutes.
against aws

Better waiting for disk metrics in graplctl

---

pulumi/infra/policies.py
pulumi/infra/swarm.py

This policy is a strict subset of
`CLOUDWATCH_AGENT_SERVER_POLICY`. The only user of the function
already has that policy attached, so it's redundant.

Remove `attach_policy_to_ship_logs_to_cloudwatch` function

---

pulumi/__main__.py
pulumi/infra/api.py
pulumi/infra/engagement_edge.py
pulumi/infra/graphql.py
pulumi/infra/lambda_.py
pulumi/infra/metric_forwarder.py
pulumi/infra/model_plugin_deployer.py
pulumi/infra/queue_driven_lambda.py
pulumi/infra/ux_router.py

Also removes the optionality of `MetricForwarder` everywhere, since
that was really an artifact of the process of getting things migrated
to Pulumi.

Remove circular dependency between Lambda and MetricForwarder

---

pulumi/infra/analyzer_dispatcher.py
pulumi/infra/analyzer_executor.py
pulumi/infra/ec2.py
pulumi/infra/fargate_service.py
pulumi/infra/graph_merger.py
pulumi/infra/node_identifier.py
pulumi/infra/service.py

none, general pulumi infra
443 outbound is enabled by default for lambda and fargate services.
also, I fixed a few "oh this is enabled for Default but not Retry" bugs.
pulumi up --preview

Use 443 outbound by default on all Lambda Services, Fargate Services

---

pulumi/__main__.py
pulumi/infra/quiet_docker_build_output.py
pulumi/infra/quiet_docker_build_spam.py

None of ours, but necessary due to the lack of quiet in buildx: https://github.com/docker/buildx/issues/621
Monkeypatch the pulumi logging system to throw away warnings from `pulumi_docker` modules.

Added `quiet_docker_build_output` to pulumi

---

etc/ci_scripts/dump_artifacts.py

Multiple people have been confused by the the "couldn't dump lambda logs", let's just fix it

Make dump_artifacts's lambda errors a bit more understandable

---

pulumi/infra/pipeline_dashboard.py

(the 'x' shouldn't be specified, and the reverse stuff was incorrect/false.)

Woops, I broke Pulumi with my dashboard

---

pulumi/infra/graph_merger.py

https://github.com/grapl-security/issue-tracker/issues/577
minor change, basically call `allow_egress_to_cache`

Graph Merger now has redis access correctly

---

pulumi/infra/analyzer_executor.py
pulumi/infra/fargate_service.py
pulumi/infra/lambda_.py
src/python/analyzer_executor/src/analyzer_executor_lib/event_retriever.py

Two things were broken with analyzer executor.
- `command` was wrong; just use the one defined in the dockerfile.
- there were permission issues with the SQS health check - that should not be needed anymore now that we have `depends_on` in docker-compose
I got data all the way up to `engagement-creator` :) 
against aws in my sandbox + looking at logs and dashboards

Fix AWS's `analyzer-executor` by unrequiring `command` and removing SQS health check

---

pulumi/infra/e2e_test_runner.py
pulumi/infra/provision_lambda.py
src/python/graplctl/graplctl/cli.py

bump execution timeouts for e2e-test-runner and provisioner from 5min to 15min, also bump lambda client read timeout in graplctl
graplctl aws test

bump provisioner and e2e-test-runner timeouts

---

pulumi/infra/graphql.py

https://github.com/grapl-security/issue-tracker/issues/578
This sets GRAPL_SCHEMA_PROPERTIES_TABLE for the GraphQL Endpoint lambda, which is needed.
I updated a deployment with these changes and eye-balled the env var in the Lambda console was set with appropriate value. I was unable to use pulumi to update the deployment where https://github.com/grapl-security/issue-tracker/issues/578 was originally found, but I verified a similar fix applied manually resolved the issue.

Adding missing GRAPL_SCHEMA_PROPERTIES_TABLE env var to graphql lambda.

---

src/python/graphql_endpoint_tests/test_schema_dynamodb.py
src/python/grapl-common/grapl_common/resources/BUILD
src/python/grapl-common/grapl_common/resources/known_dynamodb_tables.py
src/python/grapl-tests-common/grapl_tests_common/dump_dynamodb.py
src/python/grapl_analyzerlib/grapl_analyzerlib/provision/provision_common.py
src/python/graplctl/graplctl/aws/commands.py
src/python/graplctl/graplctl/aws/lib.py
src/python/graplctl/graplctl/common.py
src/python/graplctl/graplctl/idempotency_checks.py
src/python/graplctl/graplctl/upload/commands.py
src/python/graplctl/tests/shared.py
src/python/graplctl/tests/test_upload.py

https://github.com/grapl-security/issue-tracker/issues/340
- Unify all the places where we do Python string-formatting to figure out dynamodb's table names (primarily, just graplctl)
- Add some "assert grapl is provisioned" or "assert grapl is not provisioned yet" checks throughout graplctl
make graplctl
graplctl upload sysmon --logfile ./etc/sample_data/min_eventlog.xml
(this passed my 'is-provisioned' check)
did a `graplctl aws provision`
it failed with the assertion error
did a `graplctl aws wipe-state`
succeeded
did ^ again
failed, assertion error
did sysmon upload again
failed, assertion error

Graplctl has some idempotency checks, and prevents uploading to un-provisioned grapl

---

Makefile
test/docker-compose-with-error.sh

Sorta has to do with https://github.com/grapl-security/grapl/pull/934.
Jesse discovered that despite e2e failing, our CI reports success.
Heads up: I think this PR *will* fail e2e in CI; we need to land #934, #935 in some order
- More robust propagation of exit codes from docker -> docker-compose-with-error -> makefile
- introduce an `exit(42)` into e2e lambda; it fails.
- undo it; it succeeds.
- this was not the case before this change.
- (also, i tested it with https://github.com/grapl-security/grapl/pull/935 )

e2e (or rather, test-with-env) exit codes seem to work now

---

src/python/e2e-test-runner/e2e_test_runner/test_main.py
src/python/grapl-tests-common/grapl_tests_common/clients/graphql_endpoint_client.py
src/python/grapl-tests-common/grapl_tests_common/setup_tests.py

This PR fixes the graphql endpoint test client. Previously it was packing queries into URL parameters, now it's sending them as a request body.
`graplctl aws test`:
```
START RequestId: 0a8c3312-8640-408a-b763-36d3b03a32e8 Version: $LATEST
--
============================= test session starts ==============================
platform linux -- Python 3.7.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /var/task
collected 8 items
e2e_test_runner/test_main.py [DEBUG]	2021-06-21T20:10:29.625Z	0a8c3312-8640-408a-b763-36d3b03a32e8	created EngagementEdgeClient for endpoint https://e65twth5q4.execute-api.us-east-1.amazonaws.com:443/prod/auth
.[DEBUG]	2021-06-21T20:10:31.770Z	0a8c3312-8640-408a-b763-36d3b03a32e8	created …
```

fix the graphql endpoint client

---

etc/ci_scripts/dump_artifacts.py

the `docker ps` log is useful for when the log says "container <hex> exited" but you don't know which container that represents.
--all includes exited containers; this was an oversight on my part, I meant to include it.

Docker ps --all when dumping artifacts

---

src/rust/generators/sysmon-subgraph-generator/benches/generator_bench.rs
src/rust/generators/sysmon-subgraph-generator/src/generator.rs
src/rust/generators/sysmon-subgraph-generator/src/serialization.rs

Change Sysmon generator event handler to only take a Vec of events only, instead of Vec<Result<Event, Error>>.
Also, change the Sysmon parser to filter for supported events after parsing. This should help ensure we don't filter events that we shouldn't be.
I'm relying on CI tests.

Change Sysmon generator event handler to only take a Vec of events only

---

docker-compose.yml

Regarding discussion in:
https://grapl-internal.slack.com/archives/C024C7TMJ2J/p1624579400040200
in integration tests we'd see
```
2021-06-24T22:56:22.025514711Z Diagnostics:
2021-06-24T22:56:22.025516431Z   kafka:index:Topic (metrics-topic):
2021-06-24T22:56:22.025518291Z     error: kafka server: Topic with this name already exists
```

Kafka and Zookeeper containers delete their data between runs

---

Makefile
docker-compose.yml
test/docker-compose-with-error.sh

https://github.com/grapl-security/issue-tracker/issues/591
This does a few things:
1. reverts the "hack" from https://github.com/grapl-security/grapl/pull/949 (but keeps the formatting change from it).
2. adds `--always-recreate-deps` when we call `docker-compose up` with `--force-recreate`. This isn't strictly necessary to fix https://github.com/grapl-security/issue-tracker/issues/591, but it seems like what we'd want.
3. Instead of calling `docker-compose stop` on test cleanup, we call `make down`.
I re-ran the issue repro steps locally with great success.

Tear down test docker environment upon finishing.

---

docker-compose.build.yml
test/docker-compose.e2e-tests.yml

https://github.com/grapl-security/issue-tracker/issues/593
This passes a missing TAG arg to the provisioner Docker build.
```
$ make clean
...
$ export TAG=asdf
$ make graplctl
...
$ make build-services
...
$ echo $?
0
```

Pass missing TAG argument to provisioner build.

---

Makefile

https://github.com/grapl-security/issue-tracker/issues/592
This make the `build-services` Make target depend on the `graplctl` target.
I ran `make up` successfully.

Fix graplctl build order issue.

---

src/rust/Dockerfile
src/rust/graph-merger/tests/test_merging.rs
test/docker-compose.integration-tests.yml

https://github.com/grapl-security/issue-tracker/issues/594
Unfiled (at the moment):
The Rust integration tests were split into multiple containers, which adds unnecessary complexity and brittleness. An example of how this can cause issues can be seen with the latest addition of the kafka-metrics-exporter, which was not being built in the Dockerfile.
There are a number of small commits in this PR:
1. Consolidate a duplicate apt install line in the Rust Dockerfile
2. Add the kafka-metrics-exporter/integration feature to the cargo test build command.
3. Consolidate Rust integration tests to a single container.
4. ~Add the graph-merger integration tests~ Reverted, this apparently breaks other tests. I'll file a ticket for that.
5. Fix an issue in the graph-merger integration test where it was …

Rust integration test fixes

---

.buildkite/pipeline.verify.yml
docker-compose.yml
pulumi/README.md
pulumi/infra/config.py

https://github.com/grapl-security/issue-tracker/issues/593
This sets the `TAG` environment variable in CI to catch potential issues related to the above issue.
We'll test with CI, but need https://github.com/grapl-security/grapl/pull/957 to land before we can test this PR, which is why I'm keeping in draft mode for now.

Set TAG env var to non-default value in CI pipeline 

---

.buildkite/pipeline.verify.yml

I'm not quite certain why the `BUILDKITE_REPO` variable now appears to
be different between our verify and merge pipelines, but it appears
that appending `.git` isn't really needed.

Simplify the --against option for running Buf in CI

---

src/rust/Cargo.lock
src/rust/sysmon/Cargo.toml
src/rust/sysmon/src/lib.rs

(Unfiled) Building the sysmon crate alone in its directory didn't work, though the sysmon generator was able to build it.
This changes the sysmon crate to impors serde the same way the sysmon generator does.
Successfully building the crate from the sysmon directory.

Fix import issue in Sysmon crate where the project couldn't be built from its directory.

---

.dockerignore
.gitignore
Makefile
docker-compose.lambda-zips.js.yml
docker-compose.lambda-zips.rust.yml
docker-compose.yml
pulumi/README.md
pulumi/infra/dgraph_ttl.py
pulumi/infra/e2e_test_runner.py
pulumi/infra/engagement_creator.py
pulumi/infra/engagement_edge.py
pulumi/infra/graphql.py
pulumi/infra/lambda_.py
pulumi/infra/metric_forwarder.py
pulumi/infra/model_plugin_deployer.py
pulumi/infra/provision_lambda.py
pulumi/infra/service.py
pulumi/infra/ux_router.py
src/python/e2e-test-runner/e2e-test-runner.Dockerfile
src/python/e2e-test-runner/e2e_test_runner/BUILD
src/python/engagement-creator/BUILD
src/python/engagement_edge/BUILD
src/python/grapl-dgraph-ttl/BUILD
src/python/grapl-model-plugin-deployer/BUILD
src/python/grapl-ux-router/BUILD
src/python/provisioner/provisioner.Dockerfile
src/python/provisioner/provisioner/BUILD

The idea of a "tag" doesn't make much sense when thinking about lambda
zip files, particularly in the near future when we'll have an artifact
repository for them. As such, we can remove this logic from our zip
file creation.
Additionally, zip files will not be created in
`src/aws-provision/zips` anymore, since they are artifacts and not
source code. Instead, they will be created in `dist`. Though this is
the default directory in which Pants creates its packages, we will
also use this for our Rust and Typescript-based lambdas.
Now, all lambda zip files will simply be named like
`<LAMBDA_NAME>-lambda.zip`.

Create lambda zip files in dist directory without "tags"

---

Makefile

https://github.com/grapl-security/issue-tracker/issues/596
1. This makes the `lambdas` target a dependency of `build-services`, helping ensure all targets that depend on `build-services` will build in the correct order.
2. This removes the `build` target alias for `build-services`. Note: there is still no help text for the `build-services` target in `make help`. This is intention as we want to discourage users from using it directly, at least unless we exercise it directly in CI.
I verified  `make build-services` works locally.

Makefile: Remove `build` target and fix dependency issue

---

pulumi/grapl/BUILD

This was inadvertently left out of
https://github.com/grapl-security/grapl/pull/970

Add a missing BUILD file

---

pulumi/grapl/Pulumi.testing.yaml

While we're not currently doing anything with this at the moment, it
needs to be in place to exercise some of the deployment pipeline being
worked on now.

Add a testing stack configuration for the grapl Pulumi project

---

.buildkite/pipeline.verify.yml

In preparation for creating container images for actual consumption in
our infrastructure in our new merge pipeline, I created a dedicated
"docker" agent queue. It has the same machine type as our "beefy"
queue, but instances hang around for much longer (3 hours of idle
time, as opposed to 10 minutes), and also have more
agents-per-machine (3 versus 1).
With this longer time, repeated runs of integration and e2e
tests (which currently rely heavily on containerized test runs) will
proceed faster because of the container layer cache. Furthermore,
since the same images we'll use in production get built in these
steps, it will also speed up those builds when we do them in the merge
pipeline.
We may adjust the idle time, agent density, and power of these
machines in the future, or shift to …

Run e2e and integration tests on docker queue

---

docker-compose.build.yml
docker-compose.lambda-zips.js.yml
docker-compose.lambda-zips.rust.yml
docker-compose.yml
test/docker-compose.e2e-tests.yml
test/docker-compose.integration-tests.yml
test/docker-compose.typecheck-tests.yml
test/docker-compose.unit-tests-js.yml
test/docker-compose.unit-tests-rust.yml

This is just redundant, particularly in a world where we'll be
uploading containers to a registry that already incorporates the name
"grapl".

Remove "grapl-" prefix from Docker services, container names

---

src/rust/Dockerfile

NA
The Rust service containers were previously built from the `debian:buster-slim` image from Docker Hub. This changes that to use `gcr.io/distroless/cc`[1] instead, which is a much smaller image that contains a minimal environment for running our Rust services. The distroless image is significantly smaller than the buster-slim image:
```
debian                                      buster-slim          7c5871f12659   9 days ago           69.2MB
...
gcr.io/distroless/cc                        latest    2d782957ae08   51 years ago         21.2MB
```
Note: this is pulling from Google's registry, not Docker Hub.
[1] https://github.com/GoogleContainerTools/distroless/blob/main/cc/README.md
I tested locally by running the E2E tests.

Swap the base image used for Rust service containers.

---

.buildkite/pipeline.verify.yml

These shouldn't actually run on our "docker" queue as it exists right
now, because more than one agent can run on those machines. These
tests don't seem to be able to tolerate having multiple instances
running at once on a single machine.
For now, we'll just move back to the "beefy" queue, which is one agent
per machine, pending further investigation.

Switch integration and e2e tests back to "beefy" queue

---

pulumi/grapl/Pulumi.testing.yaml

When you use Pulumi to manage your configuration (e.g., `pulumi config
set foo bar`), it will write the entire configuration file back out
according to its own notion of formatting. In our case, this means
that quotes that were manually added around string values will be
stripped.
Since we make heavy use of `pulumi config set` in our pipeline to set
and update artifact version pins, this means that commits to our `rc`
branch will always have spurious diffs around these stripped quotes.
We have lost the war of the YAML quotes.

Remove unnecessary quotes from Pulumi stack configuration

---

.buildkite/pipeline.merge.yml

Rather than creating new versions of every single artifact every time
we merge a PR, we will only build if something has changed that
requires a new artifact.
For our Python artifacts, we can rely on Pants' fine-grained
dependency awareness to only build the artifacts whose inputs have
changed since our last successful run through the merge pipeline.
For Rust- and Javascript-based artifacts, however, we have to use a
different approach (since Pants does not know about these languages
yet). Here, we'll use the `monorepo-diff` Buildkite plugin, along with
our tagging-convention-aware diff script. It is not a perfect
solution, since we currently either build all Rust containers or no
Rust containers, but it's a step forward.
(Absent code-aware "what changed" logic, we would have to maintain …

Selectively build artifacts only if we need to

---

.buildkite/pipeline.merge.yml

These got inadvertently left out of the steps when they were converted
to use the monorepo-diff plugin.

Add the step keys back to the lambda steps

---

.buildkite/pipeline.merge.yml
.buildkite/pipeline.verify.yml
.buildkite/scripts/lib/packer_constants.sh

fixes the following at the merge ami stage:
https://buildkite.com/grapl/grapl-merge/builds/54#b1d4a25f-f2f6-4d18-8a30-ca103b009e03
```
.buildkite/scripts/lib/packer_constants.sh: line 26: readonly: `=': not a valid identifier
.buildkite/scripts/lib/packer_constants.sh: line 26: readonly: `.packer-manifest.json': not a valid identifier
```

I screwed up some shell stuff in the AMI merge step

---

.buildkite/pipeline.merge.ami-build.yml

In a previous iteration, the build step was defined with a key of
"ami-build". However, that was removed for other reasons.
Instead of using a key, here we can just use a wait step.

Ensure that the Record AMI ID step waits properly

---

.buildkite/pipeline.merge.ami-build.yml
.buildkite/pipeline.verify.ami-test.yml
packer/nomad-server-client/image.pkr.hcl

I recently discovered a number of long-lived Packer Builder instances
still running. Tagging them with some extra metadata should help make
it easier to figure out what's going on.

Add tags to Packer Builder instances for tracking

---

pants.ci.toml
pants.toml

For as-yet-undiagnosed reasons, the caching plugin stopped working
properly, preventing Pants from being able to run. It appears to have
something to do with a recent update to the Python `requests` library.
The engineers at Toolchain Labs are aware of the issue and are working
on a fix. In the meantime, and to unblock our pipelines, we're just
going to disable the plugin. Jobs may take a bit longer to run, but
they will at least be running.
As soon as we can re-enable the plugin, we will.

Temporarily disable Pants caching plugin

---

Makefile
src/python/Dockerfile
test/docker-compose.integration-tests.yml
test/docker-compose.typecheck-tests.yml

This prevents us from having to repeatedly `source venv/bin/activate`
absolutely everywhere.
See https://pythonspeed.com/articles/activate-virtualenv-dockerfile/
for additional background.

Ensure virtualenv is active for all Python containers

---

.buildkite/pipeline.merge.yml

In this `grapl/merge` build:
https://buildkite.com/grapl/grapl-merge/builds/67#b36055fa-e73f-4da9-a136-67139eb99e7a
```
Download ' grapl-nomad-consul-client.artifacts.json' artifacts file | 0s
-- | --
  | 2021-07-13 21:13:44 INFO   Searching for artifacts: " grapl-nomad-consul-client.artifacts.json"
  | 2021-07-13 21:13:44 FATAL  Failed to download artifacts: No artifacts found for downloading
  | No file found
```
**Note the space in front of grapl-nomad.... ugh...**
getting rid of `\`s and using the `>` (which is tailor made for multi-line commands, it turns out) should theoretically solve this issue.
other approach: trim strings in `merge_artifact_files.sh` (i'd rather not) (apparently the best bash way to trim strings? xargs!)
- got the string output of `yaml load`ing it
- copy paste …

Multiline issues in our yaml caused merge_artifacts issues.

---

.buildkite/pipeline.merge.ami-build.yml
.buildkite/pipeline.merge.yml
.buildkite/pipeline.verify.ami-test.yml

Switches our `pulumi` and `packer` queue usage to the new `pulumi-staging` and `packer-staging` queues, allowing us to retire the old queues.

Use new queues in CI

---

.buildkite/scripts/lib/artifacts.sh
.buildkite/scripts/lib/extract_ami_id_dict.jq
.buildkite/scripts/lib/extract_ami_id_dict_test.sh
.buildkite/scripts/record_artifacts.sh
Makefile

```jq stuff - basically turn
{ 
"some-ami-name": {
"us-east-1": "ami-1234"
}
}
into
{ "some-ami-name.us-east-1": "ami-1234" }
```
see https://grapl-internal.slack.com/archives/C017DKYF55H/p1626220139413700 for more context
i'm tackling this by changing the input, not the receiving side

Flatten the AMI IDs map, so that create_rc can use it to do pulumi config set stuff

---

.buildkite/scripts/build_and_upload_containers.sh

This should be a temporary state as we continue working toward
streamlining our Docker build process.

Ensure we build Python wheels before building containers in CI

---

.buildkite/pipeline.merge.yml
.buildkite/scripts/create_new_rc.sh
.buildkite/scripts/lib/artifacts.sh
.buildkite/scripts/upload_lambda_artifacts.sh
packer/hax_change_this_to_trigger_ami_build.txt

This would've helped me debug "why is my merge receiving a `{}`?" quicker.
Downloading failing is an acceptable state with defaults, but we should make it obvious to the viewer that's what happened.
https://github.com/grapl-security/issue-tracker/issues/618

Buildkite: Use pulumi-cicd for create_rc; expand sections when downloading fails

---

.buildkite/pipeline.merge.yml
.buildkite/pipeline.verify.yml
.buildkite/scripts/build_and_upload_ux.sh
Makefile
pulumi/bin/prepare_grapl_ux_dependency.sh
pulumi/grapl/__main__.py
pulumi/infra/ux.py

A new makefile target, `ux-tarball`, has been added, which creates a
`tar.gz` file containing the UX assets. This is then used in our CI
merge pipeline when we generate artifacts, pushing it to Cloudsmith
and adding the version to our Pulumi stack(s) as we do with our other
artifacts.
The Pulumi code has been modified slightly to take this into
account. One wrinkle is that Pulumi has no native way to expand a
tarball into an S3 bucket, which is how our frontend is currently
deployed. To get around this, a helper script
`pulumi/bin/prepare_grapl_ux_dependency.sh` has been added. When given
the name of a Pulumi stack, it will prepare the UX assets as
appropriate. If a version pin for the UX is present in the stack, that
version will be downloaded from Cloudsmith and expanded into …

Build UX tarball in the merge pipeline

---

packer/nomad-server-client/image.pkr.hcl

https://github.com/grapl-security/issue-tracker/issues/599
https://github.com/grapl-security/issue-tracker/issues/600
I was making the pulumi resource for the servers and got
```
aws:ec2:Instance (ec2-inst-nomad-servers-quorum-0-1):
error: 1 error occurred:
* Error launching source instance: AuthFailure: Not authorized for images: [ami-0a6df91454eef493c]
status code: 400, request id: ecb76a36-c7a5-468e-ba7f-44dadd414619
```
woops!!
cant run packer locally, so, our CI

Make our AMIs public

---

.buildkite/pipeline.merge.yml

The UX artifact build was not triggered when #1015 merged. This commit
should trigger a build, and with increased logging on the
`monorepo-diff` plugin to help sort out why.

Trigger a UX artifact build, with debug logging

---

.buildkite/pipeline.merge.yml
.buildkite/pipeline.verify.yml

There's not a lot of additional output, but it's helpful context to
have when debugging things. Seems worthwhile to just always have it.
Also fixes a misconfiguration of the diff plugin for generating the UX artifact.

Enable debug logging for all instances of the monorepo-diff plugin

---

.buildkite/pipeline.merge.ux-build.yml
.buildkite/pipeline.merge.yml

This was failing because `yarn` isn't present on the worker.

Update UX artifact build step

---

.buildkite/pipeline.provision.yml
.buildkite/pipeline.testing.yml
.buildkite/shared/lib/json_tools.sh
.buildkite/shared/steps/pulumi_preview.sh
.buildkite/shared/steps/pulumi_up.sh
Makefile

After a successful `merge` pipeline run, this pipeline will kick off, provisioning our testing stack into our Staging AWS environment. A "dummy" testing pipeline has also been added, to be fleshed out later.
(Note: we can ultimately add as many different deployments and testing pipelines here as we like; we're just starting with one for simplicity.)

Create a provisioning and testing pipeline

---

build-support/manage_virtualenv.sh

Now that we're using shared scripts to manage our Pulumi operations in
CI, it's even more important that we adhere to the common conventions
of those scripts.
Here, that means using the same name for the Python virtual
environment in our `manage_virtualenv.sh` script. It doesn't need to
be "grapl-venv" anymore (you can probably assume it's for Grapl since
it's in the `grapl` repository, after all).
You'll want to run `build-support/manage_virtualenv.sh populate` after
this lands, and activate the new one. As always, following the
instructions output by the script will help you out with this.

Change name of managed virtualenv to simply "venv"

---

build-support/editor_setup.py

NA
update `build-support/editor_setup.py` to emit a pyright config which ideally should make pyright aware of the generated protobuf stubs emitted by pants with `./pants export-codegen ::`
checked that `dist/codegen` is in the `"extraPaths"` for the `"src/python"` execution environment

add dist/codegen to pyrightconfig.json

---

.buildkite/pipeline.provision.yml
pulumi/infra/config.py
pulumi/infra/fargate_service.py
pulumi/infra/policies.py

Makes a few tweaks to ensure we can deploy Grapl from our provisioning pipeline.
The main new thing here is ensuring that we have version pins for all artifacts whenever we're deploying a Pulumi stack that we "care about" in CI.
Read individual commits for further details.

Fix provisioning pipeline

---

.buildkite/scripts/build_and_upload_containers.sh
docker-compose.build.yml

These two services are the only Lambda ZIP-deployed services that we
are not actually running as Lambdas in Local Grapl; for that
environment, these run as separate container services.
Unfortunately we were erroneously building these containers in CI and
uploading them to our artifact repository. As a result, the version
pins for these Lambda services in our Pulumi stack configurations were
frequently getting masked by the new container versions (we're still
building the Lambda versions in CI, but only when their code changes;
we don't have as good tooling to do that with the containers yet, so
they get built every time through the pipeline.)
As a result of this, Pulumi updates will fail because Cloudsmith does
not have a "raw" artifact for these service/version pairs. It does
have a …

Stop container builds of graphql-endpoint and model-plugin-deployer

---

.buildkite/pipeline.testing.yml
.buildkite/pipeline.verify.yml
Makefile
test/docker-compose-with-error.sh

Kafka and ZK's docker images retain data from run to run, even with `--force-recreate`. 
This flag cleans up that data.

Add --renew-anon-volumes to all docker-compose ups

---

src/rust/Dockerfile

This means that our containers will behave as though they were the
individual Rust binary, rather than being passed as an argument to
whatever ENTRYPOINT may be set by our base container.
(This doesn't change any behavior right now, but makes things a bit
safer and explicit moving forward.)
See the following for details:
- https://docs.docker.com/engine/reference/builder/#cmd
- https://docs.docker.com/engine/reference/builder/#entrypoint

Use ENTRYPOINT instead of CMD for Rust containers

---

.buildkite/pipeline.merge.ami-build.yml
.buildkite/pipeline.merge.yml
.buildkite/scripts/build_packer_ci.sh
.buildkite/scripts/lib/aws.sh

This is a stop-gap measure to ensure that our manifest files are going
to the proper place (our private artifact bucket). It is
emphatically *not* intended to be a permanent solution.
I'm continuing to research alternatives, and am in communication with
Buildkite Support; for now, this seems to be the most straightforward
solution.
Read documentation comments for further background on this, as well as
grapl-security/issue-tracker#620

Drop IAM role after building AMIs, before uploading artifacts

---

Makefile
docs/queryable.md

`docker-compose up` does not propagate exit code, even when it's a single job. Woops!
Also it was formatting `queryable.md` oddly before (it was treating the `_` in `process_name` funkily - so I just reformatted that section of documentation.

Fix linter exit code stuff

---

Dockerfile.pulumi
docker-compose.yml

There are a few things going on here, but it's all in service of being
more strict, clear, and extensible with what is going on in our Pulumi
container. These approaches should also be extended to our other
Docker Compose services, but this deals just with the Pulumi container.
First, we set an explicit `ENTRYPOINT` for our Pulumi container,
rather than passing a command starting with `/bin/bash -c`. This
protects us in case our base container ever changes and sets its own
`ENTRYPOINT` (our current one happens to not have one, though).
(With the changes to the command that we're making, we also _have_ to
set an entrypoint, because the long string we're generating is not
going to be an executable that exists in the container.)
We also get a bit more leeway to tighten up exactly how we …

Clean up and clarify Pulumi container commands in docker-compose.yml

---

docker-compose.yml
pulumi/grapl/__main__.py
pulumi/infra/analyzer_executor.py
src/python/analyzer_executor/src/analyzer_executor_lib/analyzer_executor.py
src/python/grapl_analyzerlib/grapl_analyzerlib/plugin_retriever.py
test/docker-compose.integration-tests.yml

Rather than composing the names of our buckets using logic internal to the `analyzer-executor`, we will now pass the full name directly to the service using environment variables.
This will lay the groundwork for ultimately getting rid of concretely-managed bucket names in Pulumi.

Pass bucket names to analyzer-executor directly

---

docker-compose.yml
pulumi/infra/analyzer_dispatcher.py
src/rust/Dockerfile
src/rust/analyzer-dispatcher/src/main.rs

Same principle as https://github.com/grapl-security/grapl/pull/1044.
Of particular note is the switch to `distroless/cc:debug` as the base container for our Rust containers. Read the individual commit messages for further details.

Pass buckets to analyzer-dispatcher

---

.buildkite/pipeline.cargo-audit.sh

Forgot that this also gets run in `grapl/merge`, since that pipeline
re-runs the contents of `grapl/verify`!
Since `grapl/cargo-audit` is the only run that we want to fail, we'll
just base the test around that pipeline name.

Invert the logic for deciding when to soft-fail a cargo audit run

---

pulumi/infra/model_plugin_deployer.py
src/python/grapl-model-plugin-deployer/grapl_model_plugin_deployer.py

None
Previously when uploading a plugin in prod, you'd get
```
2021-07-27T12:06:18.160-07:00 | [INFO] 2021-07-27T19:06:18.159Z 4c312216-6074-4eeb-9cb8-2e4e9de3c8d4 Merge the schemas with what exists in the graph
-- | --
  | 2021-07-27T12:06:18.483-07:00 | Exception in thread Thread-1:
  | 2021-07-27T12:06:18.483-07:00 | Traceback (most recent call last):
  | 2021-07-27T12:06:18.483-07:00 | File "/var/lang/lib/python3.7/threading.py", line 926, in _bootstrap_inner
  | 2021-07-27T12:06:18.483-07:00 | self.run()
  | 2021-07-27T12:06:18.483-07:00 | File "/var/lang/lib/python3.7/threading.py", line 870, in run
  | 2021-07-27T12:06:18.483-07:00 | self._target(*self._args, **self._kwargs)
  | 2021-07-27T12:06:18.483-07:00 | File "/var/task/grapl_model_plugin_deployer.py", line 156, in …
```

Fix Model Plugin Deployer permissions (and a threading issue)

---

pulumi/infra/analyzer_dispatcher.py
pulumi/infra/fargate_service.py
pulumi/infra/graph_merger.py
pulumi/infra/node_identifier.py
pulumi/infra/osquery_generator.py
pulumi/infra/sysmon_generator.py

Previously, we were simply passing a single string as a command to
most of our Fargate containers.
However, with the recent change of our Rust containers to have an
entrypoint, rather than a command, these will no longer work; we would
be executing `/analyzer-dispatcher /analyzer-dispatcher`, for example.
We now remove our existing uses of `command` in our Fargate services,
because now they just aren't needed.
Though strictly not necessary at the moment, the type of `command` was
changed from `Optional[str]` to `Optional[List[str]]`, to better
reflect the underlying primitives. Additionally, a corresponding
`entrypoint` argument was also added, in case we should ever need to
make use of that in the future.

Fix up FargateService abstraction w/r/t entrypoint and command

---

pulumi/infra/secret.py

Otherwise it's difficult to create and destroy sandbox stacks because
the leftover secret remains around for 7 days by default.

Delete the TestUserPassword immediately

---

docker-compose.yml
test/docker-compose.e2e-tests.yml
test/docker-compose.integration-tests.yml

This just continues work that was introduced in
- https://github.com/grapl-security/grapl/pull/1044
- https://github.com/grapl-security/grapl/pull/1045
- https://github.com/grapl-security/grapl/pull/1046
- https://github.com/grapl-security/grapl/pull/1047

Use explicit entrypoints in the rest of our docker-compose services

---

src/python/e2e-test-runner/e2e_test_runner/test_model_plugin_deployer.py

https://github.com/grapl-security/issue-tracker/issues/626
Remove xfailed tests that we have no short-term plan to reintroduce.
Feel free to revert this commit once those broken routes are implemented.
it's a removal of tests.

Remove perma-xfailed tests from e2e model plugin deployer

---

bin/.gitignore
bin/BUILD
bin/graplctl-pulumi.sh
docs/setup/aws.md
pulumi/infra/dgraph_cluster.py
pulumi/infra/swarm.py
src/aws-provision/dgraph/dgraph_deploy.py
src/aws-provision/dgraph/dgraph_deploy.sh
src/aws-provision/dgraph/dgraph_init.py
src/python/graplctl/graplctl/dgraph/commands.py
src/python/graplctl/graplctl/dgraph/lib.py
src/python/graplctl/graplctl/swarm/commands.py
src/python/graplctl/graplctl/swarm/lib.py

Most of the work here is removing _some_ (not all) of `graplctl`'s use of a "deployment name" to construct the names of infrastructure resources it must interact with. It is mainly focused on the Dgraph and Swarm configuration buckets, as well as the Dgraph AWS logs group. Now, these pieces of data are plumbed through to the CLI itself, allowing users to directly specify the values.
To make it easier to interact with these additional required arguments, a wrapper script has been added that is a drop-in replacement for `graplctl`, but one that knows how to inject Pulumi stack outputs into the environment, such that `graplctl` can automatically pick up the values for these new required arguments.
This has been tested in AWS.
The PR is broken up into two commits; one does the plumbing, the …

Begin passing some infrastructure values to graplctl directly

---

.buildkite/pipeline.verify.yml

I don't think we've seen a legitimate transient failure of these steps
in a long time.

Remove retries from verify pipeline

---

docker-compose.yml
test/docker-compose.integration-tests.yml

Now, our Pulumi outputs mount is attached to `/mnt/pulumi-outputs`, to
emphasize its "volume-ness". Additionally, we extract the mount
definition itself to a reusable YAML chunk to reduce repetition.

Revise Pulumi mounts in docker-compose files

---

src/python/analyzer_executor/tests/test_cache_integration.py

When `stub_env=False`, `fake_os_env` just returns the OS environment
map; `fake_os_env(stub_env=False)` is just another way of saying
"give me a fake OS environment, but actually give me the real OS
environment".
Furthermore, calling `AnalyzerExecutor.from_env()`, with no arguments,
just uses the OS environment anyway, so we can just simplify things.
Now, you only call `fake_os_env` when you actually need something
that's not the raw OS environment.

Remove stub_env argument to fake_os_env

---

pulumi/infra/api.py
pulumi/infra/engagement_edge.py
pulumi/infra/engagement_notebook.py
src/python/engagement_edge/engagement_edge/engagement_edge.py
src/python/engagement_edge/engagement_edge/env_vars.py
test/docker-compose.integration-tests.yml

This was being used to generate a notebook name, but we can now just pass that in through the environment.
Removes some unused variables, as well; please read the individual commits for further details.

Remove DEPLOYMENT_NAME from engagement-edge

---

src/js/graphql_endpoint/modules/env_helpers.ts
src/js/graphql_endpoint/modules/jwt.ts
src/js/graphql_endpoint/modules/schema_client.ts

This is a PR I've had on my disk for a while.
Basically, bring the `env_helpers` stuff we use in python/rust to TS as well.
We don't have a shared code library like `grapl-common` for TS yet - there's only 2 services right now, might not even be worth it - but that'd be our next step.

Unified env_helpers.ts for our typescript stuff

---

src/python/e2e-test-runner/e2e_test_runner/test_model_plugin_deployer.py
src/python/grapl-common/grapl_common/retry.py
src/python/grapl-common/grapl_common/time_utils.py
src/python/grapl-model-plugin-deployer/grapl_model_plugin_deployer.py
src/python/grapl-tests-common/grapl_tests_common/wait.py
src/python/grapl_analyzerlib/grapl_analyzerlib/grapl_client.py
src/python/grapl_analyzerlib/grapl_analyzerlib/provision/provision_common.py

We found the [following bug](https://grapl-internal.slack.com/archives/C0176MS6LBY/p1627481777056000) in #bugs today:
```
2021-07-28T15:02:17.765310873Z Traceback (most recent call last):
2021-07-28T15:02:17.765318545Z   File "/home/grapl/app/app.py", line 279, in inner_route
2021-07-28T15:02:17.765326666Z     return route_fn()
2021-07-28T15:02:17.765334384Z   File "/home/grapl/app/app.py", line 366, in deploy
2021-07-28T15:02:17.765342459Z     upload_plugins_resp = upload_plugins(s3, plugins)
2021-07-28T15:02:17.765350371Z   File "/home/grapl/app/app.py", line 346, in upload_plugins
2021-07-28T15:02:17.765358382Z     completed_future.result()
2021-07-28T15:02:17.765366067Z   File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
2021-07-28T15:02:17.765374125Z …
```

GraphClient alter now does retries on alters

---

src/rust/Dockerfile

The addition of the rdkafka crate to Rust[1] required the addition of some system packages so rdkafka can build libkafka. However, some of these packages are not used given the current rdkafka crate features configured, and one package, `python3` would never be used. This PR removes the unused packages.
[1] https://github.com/grapl-security/grapl/commit/41968243c464fd130c7ae27674285dd98756c8e1#diff-fced7b1d032ab8c938ca99a5697d58f745f962904b5a63ad6960f67a8eaec189
I built the Rust sources locally with these changes.

Remove unused apt packages from Rust Dockerfile

---

src/rust/Dockerfile

I'd merged https://github.com/grapl-security/grapl/pull/1064 to main without rebasing, as I should have, considering it branched from ~a month prior, and it broke main. Oops.
The error message was:
```
#75 5.148   = note: /usr/bin/ld: cannot find -lz
```
This PR adds zlib (`zlib1g-dev`) back into the Rust Dockerfile.
Ran the integration tests, which I'd previously broke.

Add zlib back to the Rust Dockerfile

---

Makefile
docker-compose.formatter.yml
etc/formatter/Dockerfile

Unfiled: The following is a no-op: https://github.com/grapl-security/grapl/blob/86533bd12ae5b66be3f73f992368d4e6ba36af00/etc/formatter/Dockerfile#L17. It effectively resets USER to root.
This removes the no-op mentioned above and does what I believe was the original intention was, and what I believe should be done: Set the user id and group id in the container to match that of the host user invoking these containers. Previously these commands were running as root.
I made a simple change to test:
```
--- a/docker-compose.formatter.yml
+++ b/docker-compose.formatter.yml
@@ -16,7 +16,7 @@ services:
lint-prettier:
<<: *formatter-image
-    command: /bin/bash -c 'cd /mnt/grapl_repo_rw/src/js; bin/format.sh --check'
+    command: /bin/bash -c 'cd /mnt/grapl_repo_rw/src/js; bin/format.sh …
```

Fix issue in etc/formatter/Dockerfile

---

Makefile

Unfiled.
The `build-test-typecheck` Make target was calling `docker buildx bake` directly instead of using `DOCKER_BUILDX_BAKE`, which is useful when someone wants to pass additional arguments to invocations of `buildx bake`.
I ran `make test-typecheck`, which uses the changed target.

Quick fix for 'build-test-typecheck' Make target

---

src/js/engagement_view/Dockerfile

NA
This makes a number of changes to the Engagement View Dockerfile, most notably:
- Use cache mount for package installation instead of relying on image fs layer.
- Change the base image from `node:alpine3.10` to `node:16-buster-slim`, which will put the base image more inline with other Dockerfiles we have and will now explicitly set the node version to use. The `node:alpine3.10` image is no longer in the list of supported images: https://hub.docker.com/_/node.
Using CI tests.

Various Engagement View Dockerfile improvements

---

Makefile

This just removes the `dist` Makefile target. It looks like it's no longer useful because the directory should always exist with `dist/.gitkeep` in git.
It looks like this target isn't used, I'll rely on CI tests.

Makefile: remove the 'dist' target as it shouldn't be needed because we

---

.buildkite/pipeline.provision.yml

Having a manual gate here doesn't really buy us anything, and was more
of a demonstration of what was possible in Buildkite.

Remove manual unblocking of Pulumi deploy in provision pipeline

---

pulumi/infra/ec2_cluster.py

The way we were managing things before this PR was causing problems
when the EC2 instances needed to be replaced (because we updated the
AMI they were using, for instance). The replacement instance would
come up, and then try to attach the specified network
interface. Unfortunately, this was still attached to the old instance,
which was still running.
One approach would be to use a [NetworkInterfaceAttachment][1] to
decouple the interface from the instance. However, this appears only
to be useful for managing secondary network interfaces, and not
primary ones.
That may be fine; however, we're opting to go for a simpler approach
here, and just configure the primary interface at the instance
level. This means that the interface just won't be shared at all.
I've confirmed that this code …

Stop explicitly managing network interfaces for our EC2 instances

---

.buildkite/pipeline.verify.yml
pulumi/infra/ux.py

If we messed up our Pulumi code, it'd be better to know it before we
get to the provisioning stage of the pipeline!
As stated in the comments, this is more of a "smoke test" than any
real exhaustive exercising of the code.

Perform a `pulumi preview` in the verify pipeline

---

Makefile

The `lint-prettier` and `format-prettier` targets create new containers for every run. Previously made containers are never reused. This diff cleans up after every run by removing the containers after use.
I verified new containers were being created by each run of these targets, and I verified that was no longer the case with this change.

Clean up containers for linting and formatting Makefile targets

---

pulumi/infra/model_plugin_deployer.py
src/python/grapl-model-plugin-deployer/grapl_model_plugin_deployer.py

Remove DEPLOYMENT_NAME from model-plugin-deployer

---

.buildkite/pipeline.merge.yml
.buildkite/pipeline.verify.yml
Makefile
docker-compose.build.yml
docker-compose.lambda-zips.js.yml
docker-compose.lambda-zips.rust.yml
src/js/graphql_endpoint/Dockerfile
src/rust/Dockerfile
test/docker-compose.unit-tests-js.yml

NA
This does a number a few things for clarifying and simplifying the build process:
- Consolidate the Docker image build steps that were in docker-compose.lambda-zips.js.yml and docker-compose.lambda-zips.rust.yml to docker-compose.build.yml, where the other image build specs are.
- Use `docker run` instead of docker-compose to create the containers used to pull AWS Lambda zips out of previously built Docker images.
- Delete docker-compose.lambda-zips.js.yml and docker-compose.lambda-zips.rust.yml as they are no longer needed.
- Rename the `lambdas` Make targets we had to names that speak more to what they're doing. `lambdas-python` -> `build-python-lambda-zips`, `lambdas-rust` -> `extract-lambda-zips-rust`, ...
- Clean up Make target dependencies accordingly
Using the test suite we …

Rearrange and clarify Make targets, and use docker run to extract from images

---

.buildkite/scripts/validate_codeowners.sh
.github/CODEOWNERS

Adds ownership for all files in the repository, enabling us to now fail the build if any files ever get added _without_ someone owning them.

Enforce codeownership for all files in the repository

---

src/python/graplctl/graplctl/cli.py
src/python/graplctl/graplctl/common.py
src/python/lambdas.Dockerfile
test/docker-compose.e2e-tests.yml

By not requiring a profile, we make graplctl more flexible. The
underlying Boto library can recognize environmentally-configured
credentials already, so if a particular profile is desired, a user can
just set `AWS_PROFILE` in their environment as usual.
It also recognizes the EC2 instance metadata service, making it easy
to run in our CI/CD environment.

Remove `--aws-profile` option for graplctl

---

docker-compose.yml
pulumi/infra/fargate_service.py
pulumi/infra/queue_policy.py
pulumi/infra/service_queue.py
src/python/analyzer_executor/src/run.py
src/rust/analyzer-dispatcher/src/main.rs
src/rust/generators/graph-generator-lib/src/lib.rs
src/rust/grapl-config/src/lib.rs
src/rust/node-identifier/src/lib.rs

Our "service queue" abstraction has the following structure:
main queue --> retry queue --> dead-letter queue
Our services are split into two paired variants: the main service and the retry service.
The main service should pull from the main queue and write failed messages to the retry queue. On the other hand, the retry service should read from the _retry_ queue, and write failed messages to the _dead-letter_ queue.
In reality, our services in AWS were actually configured to be passed all three queues, and they all had read and write access to all three queues. In Local Grapl, the identities of many queues were incorrect (retry queues were passed in with an unused `RETRY_QUEUE_URL` environment variable, while dead-letter queues were _always_ passed in with `DEAD_LETTER_QUEUE_URL` …

Fix up and better formalize our SQS queue usage

---

.buildkite/pipeline.merge.ami-build.yml
.buildkite/pipeline.merge.ux-build.yml
.buildkite/pipeline.merge.yml
.buildkite/scripts/build_and_upload_containers.sh
.buildkite/scripts/lib/artifacts.sh
.buildkite/scripts/lib/artifacts_test.sh
.buildkite/scripts/lib/packer_constants.sh
.buildkite/scripts/merge_artifact_files.sh
.buildkite/scripts/record_artifacts.sh
.buildkite/scripts/upload_lambda_artifacts.sh
.buildkite/scripts/upload_ux_assets.sh

Rather than concern ourselves with the specific names of each JSON artifacts file we create in our merge pipeline, we generalize our handling of this information to be more decoupled and open to future expansion.
Now, rather than having a concrete name for each such file we create, and requiring the identity of this file to be known in the final artifact merge step, we create the names programmatically. When given a descriptive "slug" (say, "containers"), we generate a filename that includes the unique Buildkite job ID, along with a special file extension, `grapl-artifacts.json`. This yields artifact files with names like `containers-e44f9784-e20e-4b93-a21d-f41fd5869db9.grapl-artifacts.json`. The nice thing about this is that the incorporation of the job ID eliminates the possibility of …

Generalize artifact handling code

---

.buildkite/pipeline.testing.yml
.buildkite/scripts/e2e_in_aws.sh

Uses `graplctl` and the testing lambda to run tests against the
infrastructure we provision in our testing pipeline.
Also adds a minute of sleep between provisioning and executing the
tests while we sort out why the timing through the pipeline seems to
be so variable in AWS.

Run e2e tests against AWS infrastructure in CI/CD pipeline

---

.buildkite/pipeline.verify.yml
pants.toml

Currently works for our Python unit tests.
Also pushes statistics to coverage.io in CI.

Enable Python test coverage gathering with Pants

---

.buildkite/scripts/e2e_in_aws.sh
pulumi/infra/e2e_test_runner.py
src/python/e2e-test-runner/e2e_test_runner/test_main.py

Rather than providing a fixed timeout in our AWS e2e tests (to account
for the different times it takes to run there), we'll instead provide
a way to change the timeout values within the code based on an
environment variable.
This will be a better approach, because it takes some of the guesswork
out of the problem, and also allows the tests to take only as long as
they need.
It does allow our LensView query to run longer (300 vs 120 seconds) in
our Docker Compose environment, but I felt the simplicity of having
one timeout value outweighed the complexity of multiple timeouts, or
computing relative timeouts.
Apart from that, this should behave identically in our Docker Compose
setup.

Provide a TIMEOUT_SECS variable to adjust timeouts for e2e tests

---

Makefile
nomad/grapl-core.nomad

Adds back the missing `lint-hcl` make and fixes the nomad formatting as it was not formatted properly.

Fixed missing nomad lint and linted nomad job

---

.buildkite/scripts/e2e_in_aws.sh

We suspect there may be some nondeterministic shenaniganery between
various analyzer upload, data upload, and test kickoff steps that is
accounting for the variation in how long the e2e tests can take in
AWS.
Rather than simply cranking up the timeouts again, we'll add a little
time up front to try and get a better indication of where the issue
may be.
This is obviously not a Real Solution.

Add some sleeps between various provisioning steps in e2e test

---

pulumi/infra/e2e_test_runner.py

Accept defeat and max out our timeouts for e2e tests in AWS

---

docker-compose.yml
pulumi/infra/service_queue.py
src/rust/node-identifier/src/bin/node-identifier.rs
src/rust/node-identifier/src/lib.rs

https://github.com/grapl-security/issue-tracker/issues/431
Oh boy. There's a lot!
- We only try in Default Queue 1x before sending to Retry Queue
- Localstack now uses `elasticmq` for its SQS mock, which supports redrive policies natively.
- Node Identifier / Node Identifier Retry now accurately have different behaviors.
- Document the hell out of `should_default`. 
e2e; I noted that a message did make it to try retry service's logs.

Issue 431: Node Identifier and Retry should be different

---

.buildkite/pipeline.verify.yml
docker-compose.build.yml
src/js/engagement_view/Dockerfile
src/js/graphql_endpoint/package.json
test/docker-compose.unit-tests-js.yml

Does what #1108 did, but for our JavaScript / TypeScript code.
Run `make test-unit-js` to see it work.
Did a bit of tidying up of the relevant Docker setup while I was here; please read individual commits for details.

Add code coverage for JS/TS code

---

.github/stale.yml

This enables the Stale bot (https://github.com/probot/stale) to close
PRs that have not had activity in a while.
As configured, a PR must have one week (7 days) of inactivity before
being marked as "stale". If it experiences one more day without any
interaction, it will be closed.
This is in the interest of keeping our PR list up to date, and make it
easy to see what is currently being worked on and reviewed.

Configure the Stale bot to close old PRs

---

.github/CODEOWNERS
LOCAL_UI_WORKFLOW.md
Makefile
docker-compose.local-dev.yml
test/docker-compose.e2e-tests.yml

There have been a lot of changes in how Grapl runs on a local
workstation. This commit introduces a few new makefile targets and
supporting code to help automate as much as possible to make it easier
to iteratively develop the Grapl UI locally.
Documentation is added in the new `LOCAL_UI_WORKFLOW.md` file.

Add some makefile targets to aid UX development against Local Grapl

---

.buildkite/pipeline.verify.yml
src/rust/Dockerfile
test/docker-compose.unit-tests-rust.yml

Does what #1108 and #1116 did, but for Rust code, using [tarpaulin](https://crates.io/crates/cargo-tarpaulin)

Gather Rust unit test coverage statistics

---

.buildkite/pipeline.verify.yml
.buildkite/scripts/format_nomad.sh
.buildkite/scripts/lint_nomad.sh
.buildkite/scripts/lint_packer.sh
Makefile
docker-compose.check.yml

This has the added benefit of removing a few scripts. It also makes it
more clear that we're doing the exact same thing in CI that we do
locally.

Use our hcl-formatter image to lint and format all HCL files

---

.buildkite/pipeline.verify.yml

Ultimately this will lead to more flexibility in piecing together our
pipeline jobs, as well as sharing the logic across multiple
repositories.
The default configuration of the plugin is to pull all XML files from
`dist/coverage/**`, which is where we put all our coverage statistics,
following the pattern established by Pants' default configuration.
Currently, the plugin is pinned to the current commit on the `main`
branch at
https://github.com/grapl-security/codecov-buildkite-plugin. Look there
for further details about how the plugin works.

Use our codecov Buildkite plugin for coverage collection

---

pants.toml

https://app.zenhub.com/workspaces/grapl-6036cbd36bacff000ef314f2/issues/grapl-security/issue-tracker/630
https://github.com/grapl-security/issue-tracker/issues/630
Adds support for shellcheck on mac. Until this is added running make lint (or really gmake lint on mac) will error out
gmake lint # when you run bew install make on mac it gets named gmake to signify that its gnu make
Test Results:
Before:
```
Exception message: 1 Exception encountered:
UnknownVersion: No known version of shellcheck v0.7.2 for darwin found in ('v0.7.2|linux|70423609f27b504d6c0c47e340f33652aea975e45f312324f2dbf91c95a3b188|1382204',)
```
After
```
18:01:20.16 [INFO] Completed: lint - shfmt succeeded.
18:01:21.39 [INFO] Completed: lint - Shellcheck succeeded.
✓ Shellcheck succeeded.
✓ shfmt succeeded.
```

Add support for shellcheck to mac

---

Makefile
pants.toml
src/python/analyzer_executor/src/analyzer_executor_lib/BUILD
src/python/analyzer_executor/src/analyzer_executor_lib/analyzer_executor.py
src/python/grapl-tests-common/grapl_tests_common/BUILD
src/python/grapl_analyzerlib/grapl_analyzerlib/BUILD

Getting much closer, now the issue is
src/python/analyzer_executor/src/analyzer_executor_lib/analyzer_executor.py:41: in <module>
from python_proto.envelope import Envelope, Metadata
E   ModuleNotFoundError: No module named 'python_proto.envelope'

Fix pants/protos stuff for jesse

---

pulumi/infra/ec2_cluster.py

https://github.com/grapl-security/issue-tracker/issues/649
https://app.zenhub.com/workspaces/grapl-6036cbd36bacff000ef314f2/issues/grapl-security/issue-tracker/649
Automatically sets a Name tag for ec2 servers. This will be the name passed to the server and the instance number. For example, when we spin up 3 Nomad servers we'll see nomad-servers-cluster-0, nomad-servers-cluster-1, nomad-servers-cluster-2
Tested using pulumi up and seeing the diff, and then manually checked upon creation

Set Name tag automatically for ec2 servers

---

Makefile

https://github.com/grapl-security/issue-tracker/issues/651
https://app.zenhub.com/workspaces/internal-engineering-611d4aa8493fe3001b564b01/issues/grapl-security/issue-tracker/651
This removes make package-python-libs since its an exact duplicate of make build-python-wheels. Since build-python-wheels is more in line with our naming conventions and is already in the build section, we're keeping it.
N/A removing a make command

Remove make package-python-libs in favor of make build-python-wheels

---

docker-compose.build.yml
docker-compose.yml
localstack/Dockerfile

- Whenever we bring up a Localstack container, it goes and downloads `elasticmq.jar` - a 32M download every time we `up` localstack!
- Downloading ElasticMQ to the container causes an unspecified error when running under Nomad. 
- I'm trying to just avoid that issue entirely.
This mysterious URL is the exact one that Localstack uses: 
https://github.com/localstack/localstack/blob/c2fa7bb5dba64d9318c7a5bbe295ac96ad3f2a02/localstack/constants.py
We can stop doing this all the moment we have Kafka.

Localstack fork: Preload ElasticMQ to reduce load times and enable Nomad

---

Makefile
docker-compose.yml
nomad/grapl-core.nomad
nomad/local/integration-tests.nomad
nomad/local/run_integration_tests.sh
pulumi/grapl/__main__.py
pulumi/infra/config.py
pulumi/infra/nomad_job.py

Instead of deploying via `run_integration_tests.sh`, we do it in Pulumi.
Seems nice and functional and not awful.

Nomad integration tests are now deployed by Pulumi (this is going into origin/nomad-integ-tests)

---

nomad/grapl-core.nomad
nomad/local/grapl-local-infra.nomad
nomad/local/integration-tests.nomad

https://github.com/grapl-security/issue-tracker/issues/602
This registers all remaining services in consul if they were not already registering.
This sets specific names for the services so we don't end up with integration-tests-rust-integration-tests-rust-integration-tests as the name for services.
export KEEP_TEST_ENV=1
In your browser go to http://localhost:8500/
Confirm that there are no long names using the default job-group-task mechanism but instead are short-names

Register nomad services in consul with better names

---

.buildkite/pipeline.verify.yml
Makefile
docker-compose.build.yml
local-grapl.env
nomad/grapl-core.nomad
nomad/local/grapl-local-infra.nomad
nomad/local/integration-tests.nomad
nomad/local/run_integration_tests.sh
nomad/local/start_detach.sh

https://github.com/grapl-security/issue-tracker/issues/676
This removes all the local registry pieces since apparently Nomad doesn't need that.
Nomad will pick up local images as long as they are not tagged with latest, who knew?
You'll notice that test-integration runs in about 7 minutes and change instead of the 30+ minutes previously 🥳 
Nomad should run through everything without any docker pull related failures (tests may still fail since integration test suites are not passing yet)

Remove local registry

---

nomad/grapl-core.nomad
nomad/local/integration-tests.nomad
pulumi/grapl/__main__.py

turns out we never specified aws_access_key_id/secret_key in Pulumi-Nomad
This change:
- fixes that
- removes some defaults
- helps us catch it (the new `subset_keys` check is better than the & - it fails if we specify a key that wasn't there before)

Nomad - remove more defaults from grapl-core.nomad; ensure keys exist when copying keys to integration tests

---

.buildkite/pipeline.verify.yml

Until we track down the cause of intermittent timing-related failures
in the e2e tests, we'll allow Buildkite to automatically retry
failures on our behalf.

Enable automatic retries on e2e tests for now

---

src/python/python-proto/python_proto/tests/strategies.py

NA
This PR restricts the size of list data (e.g. repeated fields) in the python-proto hypothesis strategies. The goal here is to keep test data generation fast.
automated tests

restrict the list sizes in generated test data

---

build-support/manage_virtualenv.sh

Previously, if the script was executed from another
directory (particularly `build-support` itself), it would fail, but
leave behind an extra `venv` directory, which caused subsequent
problems with Pants.
Now, all the logic takes place from the repository root, eliminating
these issues.

Ensure that manage_virtualenv.sh runs from the repository root

---

.gitignore
BUILDING.md
nomad/local/start_detach.sh

None.
Jesse ran into this silent failure
and i thought it'd be nice to spend 10m to help prevent people from running in to it in the future.
- Check for bridge networking when on chrome os
- gitignore something that should have been gitignored
- remove some CDK instructions from building.md
tested on my machine with
valid module file
module file sans bridge.ko
no module file

Check for bridge networking hack when on cros (and fix a missed gitignore)

---

nomad/local/nomad_run_local_infra.sh

none
I'm not sure why this isn't necessarily a failure case for `nomad job run`, but, yeah - this will exit early if local infra fails in some way.
(Pulumi-deployed jobs seem to fail automatically as one would expect.)
I mucked with a health check on a local-infra task, and it exited as expected due to `check_for_task_failures_in_job`.

Nomad: Exit early if local infra failed to deploy

---

.github/CODEOWNERS
nomad/local/integration-tests.nomad
src/python/Dockerfile
src/python/graphql_endpoint_tests/test_graphql_endpoint.py
src/python/grapl-tests-common/grapl_tests_common/setup_tests.py
src/python/grapl_analyzerlib/tests/test_process_node.py
test/run/BUILD
test/run/integration-tests-from-docker-container.sh

https://github.com/grapl-security/issue-tracker/issues/706
- Python integration tests now use a mounted Docker volume for caching. This will improve runtime in CI and locally (after an initial "slow" populate-stuff run.)
- Some slower Hypothesis tests were reduced from 100 examples to 25 examples.
- Modified behavior of stdout/stderr getting printed during integration-test time.
`make test-integration`

python integration tests now use a named-docker-volume for the Pants cache. Improve runtime of some hypothesis tests.

---

nomad/grapl-core.nomad
nomad/local/integration-tests.nomad

Some of our images in nomad files were missing the container_repo variable. This caused them to fail to be pulled in Nomad in AWS. I've also added them to the integration tests since we may want to run those in AWS at some point. Notably local-grapl does not have this nor do containers pulled from outside of cloudsmith such as dgraph (if we chose to mirror these containers we would need to add them)
Did a test deploy to Nomad in AWS

Add container_repo to images

---

.buildkite/pipeline.verify.yml
.github/CODEOWNERS
codecov.yml

We've noticed a little flapping in our code coverage statistics around
our Rust protobuf generation, where unrelated changes appear to reduce
coverage. With the default settings, _any_ decrease in coverage
results in a "failure" in Github. We don't gate PR merges on coverage
changes at this point, so these "failures" end up being noise.
Until we sort out this flapping, we'll make the code coverage
reporting more advisory by losening the failure threshold to 1%. This
should reduce spurious failure statuses in Github.
A linting step has also been added in CI.

Loosen failure threshold for Codecov reporting

---

.buildkite/pipeline.verify.yml

By using the metahook plugin, we can run the setup steps that are
needed to preview our Grapl deployments, while still allowing us to
use our Pulumi plugin for the main logic.
This, in turn, will allow us to remove the Pulumi scripts from our
`buildkite-common` repository.

Use our Pulumi plugin to preview Grapl deployment

---

nomad/grapl-core.nomad
nomad/grapl-ingress.nomad

Okay, so let me preface this by saying: I'm not really sure how this worked before.
Previously the ingress gateway said its upstream (the service it serves) would be "grapl-web-ui"; that never actually existed, this service is called web-ui!
This also solves a mystery I had, where for some reason the `web-ui`'s ports had to be specified and exactly the same as the ingress.
Anyway - all the weirdness is removed, web-ui has a dynamicly assigned port now, and the ingress gateway correctly sends stuff to it.

Nomad ingress on port 1234 has the correct upstream.

---

pulumi/grapl/__main__.py
pulumi/infra/api_gateway.py
pulumi/infra/cache.py

https://github.com/grapl-security/issue-tracker/issues/665
This PR depends on https://github.com/grapl-security/platform-infrastructure/pull/43
We construct an API Gateway route that forwards HTTP traffic all the way to grapl-web-ui; documentation on this pipeline is
in the api_gateway.py file.
also checked graphql endpoint:
```
curl -I -X POST https://n87ev5n1dg.execute-api.us-east-1.amazonaws.com/graphQlEndpoint/
HTTP/2 401 
date: Wed, 03 Nov 2021 23:41:48 GMT
content-type: text/plain; charset=utf-8
content-length: 38
set-cookie: actix-session=CwUZ2zRRO8F3ByybXBzBUCbB9MRuoGL8QxQZfkSo; HttpOnly; Secure; Path=/
apigw-requestid: IQGpeiDOIAMEJ2g=
```
correctly gives me a 401 unauth

Grapl Pulumi constructs an API Gateway route to `grapl-web-ui`

---

.github/CODEOWNERS
nomad/README.md
src/rust/.cargo/audit.toml

For the time being, we'll ignore the warnings and vulnerabilities that
are currently being flagged by `cargo-audit`. Many of them we can't
really do anything about anyway, given that there either is no fix, or
they are coming in from our dependencies.
The ones we do have control over have corresponding issues to ensure
we fix them.

Add cargo audit configuration file

---

.buildkite/scripts/build_and_upload_containers.sh
Makefile
nomad/local/e2e-tests.nomad
nomad/local/integration-tests.nomad
pulumi/grapl/__main__.py
pulumi/infra/nomad_job.py
pulumi/integration_tests/README.md
pulumi/integration_tests/__main__.py
test/docker-compose.e2e-tests.build.yml
test/docker-compose.integration-tests.build.yml

grapl-security/issue-tracker#770
- Introduce the "optional-ness" of aws_endpoint / access_key / secret_key, which we already do in `grapl-core.nomad`
- Introduce artifacts tags.
- Disable integration tests against AWS for now - it needs some work.
- Publish E2E tests to Cloudsmith
- Sunset e2e-tests.build, add that to integration-tests.build 
locally:
make test-e2e
against my sandbox:
followed my initialization steps
pulumi up
manually run a `dispatch job`, upon which it fails because it doesn't know how to grab e2e tests with that `dev` tag (obviously)

A few steps closer to e2e tests in AWS

---

.buildkite/scripts/build_and_upload_containers.sh

pretty self explanatory
this has bitten me twice today:
```
> [e2e-tests e2e-tests 1/7] COPY ./dist/e2e-tests.pex /home/grapl/:
  | ------
  | error: failed to solve: rpc error: code = Unknown desc = failed to compute cache key: "/dist/e2e-tests.pex" not found: not found
```
https://buildkite.com/grapl/grapl-merge/builds/286#b315e182-e379-41fa-807e-9e7f41345e4b
and
```
  | ------
  | > [e2e-tests 7/7] COPY --chown=grapl ./bin/graplctl /home/grapl/bin/graplctl:
  | ------
  | error: failed to solve: rpc error: code = Unknown desc = failed to compute cache key: "/bin/graplctl" not found: not found
  | 🚨 Error: The command exited with status 1
```
https://buildkite.com/grapl/grapl-merge/builds/285#196019be-5d12-41de-a1b7-3ad5cc2618fc
so, enough is enough, I'm ripping this bandaid off.
The …

Move build_and_upload_containers.sh to just use make commands, not pure docker buildx bake

---

Makefile
local-grapl.env

well, this was annoying.
I've now *actually tested* this locally by commenting out the `docker push` in build_and_upload_containers; the tags now actually work.

WITH_LOCAL_GRAPL_ENV overrides the TAG= specified in build_and_upload_containers

---

Makefile
local-grapl.env
nomad/grapl-core.nomad
nomad/grapl-provision.nomad
nomad/local/e2e-tests.nomad
nomad/local/grapl-local-infra.nomad
nomad/local/integration-tests.nomad
nomad/local/nomad_run_local_infra.sh
pulumi/grapl/__main__.py
pulumi/infra/docker_image_tag.py
pulumi/integration_tests/__main__.py

ongoing attempt to solve grapl/merge
the current issue is that we'd build Docker images with a TAG of `ci-pipeline`, but Nomad assumed some things were still `:dev`.
- It never inspected `$TAG` at all
- e2e and integration tests were straight-up hardcoded to `dev`
This changes every place we consume a tag to use `def version_tag` (ctrl-f for it). 
ran `make test-integration` and `make test-e2e` and also variants with `TAG=derp make test-integration`
seemed to work

Propagate $TAG into Nomad

---

pulumi/grapl/Pulumi.testing.yaml

⚠️ NOTE: THIS PR IS AGAINST THE `rc` BRANCH, *NOT* `main` ⚠️ 
We don't currently have an automated way to *remove* unused artifacts
from our Pulumi stack. With all the internal revisions that have
occurred lately, we were left with quite a number of obsolete
packages.
Once this is merged into the `rc` branch, this will trigger a new run
of the `grapl/provision` pipeline.

Remove old pinned artifacts

---

.buildkite/pipeline.merge.yml
.buildkite/scripts/build_and_upload_containers.sh
docker-compose.build.yml
docker-compose.yml
nomad/grapl-core.nomad
nomad/grapl-provision.nomad
nomad/local/e2e-tests.nomad
nomad/local/grapl-local-infra.nomad
nomad/local/integration-tests.nomad
pulumi/grapl/Pulumi.testing.yaml
pulumi/grapl/__main__.py
pulumi/infra/config.py
test/docker-compose.integration-tests.build.yml

First, we add a promotion step to our merge pipeline; if all our
containers build successfully, we'll use our new Cloudsmith Buildkite
plugin to promote the new artifacts out of the `raw` repository into
the `testing` one. Anything left in the `raw` repository will be
deleted over time, because anything that remains in there more than a
few minutes is by definition part of a failing commit.
Then, we parameterize our Pulumi stack with the value of this
repository, so we can instruct Nomad where to pull the containers
from. Previously, we specified this using a combination of "registry"
and "repo". However, because of how the naming in Cloudsmith works, we
always had to interject a `grapl/` into the resulting address. (That
is, `registry` was `docker.cloudsmith.io` and `repository` was …

Pull Pulumi artifacts from testing repository

---

.buildkite/pipeline.provision.yml

Once packages make it through the testing pipeline, we can copy them
into the "validated" repository, which will be a holding place for
packages that can plausibly be released to production.
This repository has retention rules set up (out of band; not in this
PR) so that we only keep the 5 most recent versions of each package.
Additionally, we promote the packages via copy and not move because
once we're able to selectively build based on "what changed", we'll be
introducing subsets of new packages. If we were to move them all out,
then nothing would be available for the next run-through of the
pipelines.
In the future, we may be able to incorporate the "extract the current
artifacts from the Pulumi stack" logic into the Pulumi plugin, or
probably the artifacts plugin; for now, though, …

Promote packages to the "validated" repository in Cloudsmith

---

.buildkite/pipeline.merge.yml
.buildkite/pipeline.provision.yml

This picks up a bugfix that we need:
https://github.com/grapl-security/cloudsmith-buildkite-plugin/pull/5

Bump cloudsmith plugin to v0.1.2

---

.buildkite/pipeline.merge.yml
.buildkite/pipeline.provision.yml

This picks up
https://github.com/grapl-security/cloudsmith-buildkite-plugin/pull/8.
This will let us promote `node-identifier` and `node-identifier-retry`
as separate artifacts. Previously, it was pulling back both for a
query of `name:node-identifier version:XXX`, which failed, because the
plugin expects only a single package to be returned from a query.

Update Cloudsmith Buildkite plugin to v0.1.3

---

.buildkite/pipeline.provision.yml

This is a wretchedly ugly hack but is currently the most
straightforward way to upload the resulting file to our artifacts
bucket.
The problem comes from our use of the assume-role plugin to inject AWS
credentials that have access to the staging account; this then gets in
the way of access to our artifacts S3 bucket, which resides in our CD
account.
(The irony is that we don't even need to interact with AWS for this at
all, but we need access to Pulumi in order to extract data from the
stack. I'll continue looking into better solutions, but for now, this
ought to work.)

Unset AWS credentials before trying to upload artifacts file

---

.buildkite/pipeline.provision.yml
.buildkite/scripts/extract_artifacts.sh

I think we're running into issues with how the environment is set
across plugins. For now, we'll just do everything in a self-contained
script.

Shift all artifact extraction to a script

---

pulumi/grapl/Pulumi.testing.yaml

⚠️ NOTE: THIS PR IS AGAINST THE rc BRANCH, NOT main ⚠️
This was an old dependency that no longer exists. This was caught when
trying to promote all the packages from the release candidate to the
new `validated` repository.
See https://github.com/grapl-security/grapl/pull/1271 for additional context.

Remove e2e-test-runner from testing stack

---

src/rust/graph-merger/src/lib.rs
src/rust/graph-merger/src/main.rs
src/rust/graph-merger/src/reverse_resolver.rs
src/rust/graph-merger/src/service.rs
src/rust/graph-merger/src/upsert_util.rs
src/rust/graph-merger/src/upserter.rs
src/rust/node-identifier/src/sessions.rs

None, this was just a quick win I Saw.
Previously the graph-merger and node-identifier had `#![allow(dead_code, unused_imports)]` and I removed that and fixed any of the issues that caused.
No additional testing. This is primarily a cosmetic change, very little code has changed.

Reenable warnings on node-identifier and graph-merger

---

src/rust/.cargo/audit.toml

This recent advisory was flagged by `cargo audit`, but we don't
believe that it's not a concern for our codebase.

Ignore RUSTSEC-2021-0073

---

etc/formatter/Dockerfile
nomad/grapl-core.nomad
nomad/grapl-provision.nomad
nomad/local/e2e-tests.nomad
nomad/local/integration-tests.nomad
nomad/local/start_detach.sh
pulumi/grapl/__main__.py
pulumi/infra/docker_images.py
pulumi/infra/nomad_job.py
pulumi/integration_tests/__main__.py

https://github.com/grapl-security/issue-tracker/issues/697
Previously we'd feed a `container_repository` and `tag`s into the Nomad file and do some variable interpolation inside Nomad to build the Docker Image ID ("okay, where do we find the docker image?")
I'm lifting this work up to the Pulumi level per the attached issue.
Main motivation for picking this up now: we will soon potentially be in a situation where some images come from the `grapl/raw` cloudsmith repo, and some come from the `grapl/$USERNAME` repo (if I wanted to upload 1 image for testing). This is much easier to reason about at the Pulumi level. 
against CI

Feed fully qualified Docker Image URLs into the Nomad file instead of piecemeal tags and container_repos

---

.buildkite/scripts/build_and_upload_containers.sh

wimax  3:57 PM
Ah, shoot, looks like my PR failed
https://buildkite.com/grapl/grapl-provision/builds/175#a5604b6b-b156-4fc3-a932-ce337e2100a1
because we don't currently upload the python-integration-tests image to dockerhub; let me get on that
the good news is, it does correctly insert the artifacts in origin/rc!
https://github.com/grapl-security/grapl/blob/rc/pulumi/integration_tests/Pulumi.testing.yaml
```
File "../infra/docker_images.py", line 76, in build_with_tag
  | image_name, artifacts=self.artifacts, require_artifact=self.require_artifact
  | File "../infra/docker_images.py", line 45, in _version_tag
  | f"Expected to find an artifacts entry for {key} in Pulumi config file"
  | KeyError: 'Expected to find an artifacts entry for python-integration-tests in Pulumi config file'
``` …

Upload [the currently unused in prod testing] integration-test containers to Cloudsmith

---

.buildkite/pipeline.testing.yml

Solves the following
```
Running commands | 8s
-- | --
  | $ trap 'kill -- $' INT TERM QUIT; .buildkite/scripts/grapl_testing_stack/run_parameterized_job.sh e2e-tests 6
  | warning: A new version of Pulumi is available. To upgrade from version '3.18.1' to '3.19.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
  | error: PULUMI_ACCESS_TOKEN must be set for login during non-interactive CLI sessions
  | 🚨 Error: The command exited with status 255
  | user command error: exit status 255
```
at 
https://buildkite.com/grapl/grapl-testing/builds/97#2bcd7730-538b-48f0-963a-75d6f546d64d

pipeline.testing.yml: log in to Vault

---

.buildkite/scripts/grapl_testing_stack/run_parameterized_job.sh
Makefile
etc/ci_scripts/dump_artifacts/cli.py

Relates to https://github.com/grapl-security/issue-tracker/issues/770
e2e tests worked fine, but dump_artifacts still tried to download agent logs. Turns out I was literally feeding in a string "False".

Coerce --dump-agent-logs from str to bool, woops

---

.buildkite/pipeline.provision.yml
.buildkite/scripts/grapl_testing_stack/destroy_stateful_resources.sh
pulumi/grapl/__main__.py

https://github.com/grapl-security/issue-tracker/issues/793
Between e2e tests runs, we want to clean up state.
This script, when enabled, will destroy grapl-provision, grapl-core, and dynamodb tables. 
a `pulumi update` will re-add them (and, yes, reprovision them!)
I did this on my personal sandbox.

Add a script to destroy/recreate stateful resources during grapl/provision (currently disabled)

---

.buildkite/pipeline.provision.yml
.buildkite/pipeline.testing.yml

Satisfies and closes out https://github.com/grapl-security/issue-tracker/issues/793
In doing so, may also close out https://github.com/grapl-security/issue-tracker/issues/770
- Uncomment the "stateful resources destroy" buildkite step, now that its precursor has been fulfilled (a certain pulumi output exists)
- (oops, forgot to add a thing about artifacts)
they weren't

Enable the stateful resources destroy step in E2E-in-AWS

---

.buildkite/pipeline.provision.yml
.buildkite/pipeline.testing.yml

This reverts commit 016ac1f8ec5dba68e4117d10052107ef2213ef99, reversing
changes made to 8d7e612115787d2c699c3f7199f3f9c89079a2de.
Reverts https://github.com/grapl-security/grapl/pull/1303
The reasoning is due to the state described in this Pulumi ticket:
https://github.com/pulumi/pulumi/issues/8562
The plan here is:
remove the delete and then run an update and then re-add the delete
I'll get a successful `provision` run with this revert, and then revert-revert.

Revert "Merge pull request #1303 from grapl-security/reenableE2eTesting"

---

.buildkite/pipeline.provision.yml
.buildkite/pipeline.testing.yml
.buildkite/scripts/grapl_testing_stack/destroy_stateful_resources.sh

Step 2 of the plan described in https://github.com/grapl-security/grapl/pull/1304
The plan here is:
remove the delete and then run an update and then re-add the delete
this is the re-add.
also I added a `--refresh` because thomas asked nicely.

Revert revert "Merge pull request #1303 from grapl-security/reenableE2eTesting"

---

.buildkite/pipeline.testing.yml
.buildkite/scripts/extract_artifacts.sh
.buildkite/scripts/unset_aws_creds_for_artifact_upload.sh

https://github.com/grapl-security/issue-tracker/issues/770
Continue using a hack around AWS creds for artifacts, until it's solved more holistically.
See https://grapl-internal.slack.com/archives/C02JCBKS97V/p1639004522015500 for further discussion
they weren't :) :)

Unset AWS creds for artifact upload after prod aws-e2e-tests

---

build-support/editor_setup.py

NA
This PR fixes the editor setup script to emit a configuration which uses the `build-support/venv` instead of the defunct `build-support/grapl-venv`
```
. build-support/venv/bin/activate
./build-support/editor_setup.py generate
```

use venv instead of grapl-venv for the pyright config

---

Makefile
docs/setup/aws.md

this is a holdover from the days when Pulumi would upload local Docker images and lambda zips to AWS

Remove pulumi-prep and update some documentation

---

pulumi/grapl/Pulumi.testing.yaml
pulumi/integration_tests/Pulumi.testing.yaml

⚠️ THIS IS A PR AGAINST THE `rc` BRANCH, NOT `main`! :warning:
At one point we were uploading these artifacts to Cloudsmith and
adding them to Pulumi stack configuration files. However, these don't
actually need to be promoted through our pipeline. Their presence now
causes downstream promotions to fail (because these artifacts have
since been removed from Cloudsmith), so they must now be removed
manually.

Remove integration testing artifacts

---

.buildkite/scripts/build_and_upload_containers.sh
docker-compose.build.yml
src/rust/plugin-registry/Cargo.toml

Precursor work to https://github.com/grapl-security/grapl/pull/1312
but due to https://grapl-internal.slack.com/archives/C02J5JYS92S/p1639524803254000 we have to do this first

Introduce a new plugin-registry image to cloudsmith - but don't include it in nomad/pulumi just yet

---

nomad/grapl-core.nomad
nomad/local/grapl-local-infra.nomad
nomad/local/integration-tests.nomad
nomad/local/nomad_run_local_infra.sh
pulumi/grapl/__main__.py
src/rust/Cargo.lock
src/rust/Dockerfile
src/rust/plugin-registry/src/client.rs
src/rust/plugin-registry/src/lib.rs
src/rust/plugin-registry/src/main.rs
src/rust/plugin-registry/src/server.rs
src/rust/plugin-registry/tests/test_smoketest.rs

This is precursor work for https://app.zenhub.com/workspace/o/grapl-security/issue-tracker/issues/719
Just a very basic skeleton of a test framework, so that people can add real, valuable tests later.
- Add a `nomad job validate` that would have unblocked an issue Colin had.
- Build plugin-registry with make build
- add plugin-registry as a service to nomad
- add a smoketest integration test for plugin-registry
- add a fake implementation of GetGeneratorsForEventSourceRequest so that we can run this integration test against something. 

Hook Plugin Registry up to Nomad, and plumb through a very basic integration smoke-test.

---

.buildkite/pipeline.merge.yml
.buildkite/pipeline.verify.yml

This will once again allow us to create release candidates after we
switched CI over to using shallow git clones.

Update to grapl-rc plugin v0.1.2

---

pants.toml

We no longer create lambdas, so there's no need for this.

Remove AWS Lambda backend for Pants

---

pulumi/grapl/__main__.py
pulumi/infra/nomad_job.py

The default is 5m.
Sometimes, the update step in pipeline.provision.yml fails, e.g. https://grapl-internal.slack.com/archives/C024C7TMJ2J/p1640036760073400
Unfortunately we don't really have the setup right now to debug why it's failing.
- the `pulumi update` happens in the Buildkite plugin
- This makes it difficult to do a "finally" step after the `pulumi update` - in this case, the finally step would be to run a "for dump artifacts" step like .buildkite/scripts/grapl_testing_stack/run_parameterized_job.sh does
- there's some talk about this here https://github.com/buildkite/feedback/issues/133
I'm taking a conservative step by bumping it to 8m for now

Increase grapl-core nomad job timeout conservatively for aws-deploys

---

.buildkite/scripts/grapl_testing_stack/destroy_stateful_resources.sh

I noticed an issue starting around https://buildkite.com/grapl/grapl-provision/builds/201
My suspicion of what happened:
- a previous `pulumi update` did not succeed in creating grapl-core
- now, running destroy_stateful_resources on target urns [resource1, resource2, grapl-core] fails because, well, grapl-core never even came up beforehand
As such, I am making destroy_stateful_resources *best effort*. This is a short term solution until we have multitenancy IDs anyway.

Destroy stateful resources one-by-one, and allow for failures.

---

pants.toml

Due to https://github.com/pantsbuild/pants/issues/14053
Previous update for comparison: https://github.com/grapl-security/grapl/pull/1315

Update Toolchain Plugin to 0.17.0 

---

src/rust/Cargo.lock
src/rust/grapl-web-ui/Cargo.toml
src/rust/grapl-web-ui/src/main.rs

None, this is a hotfix for a CVE.
Disables our usage of compression in grapl-web-ui, which removes our dependency on the vulnerable brotli2 crate.
I'm also slipping in a patch update for the lru crate, which has a UAF (that we are not impacted by, I don't believe).
No tests.

Remove brotli compression from grapl-web-ui

---

src/rust/Cargo.lock

None filed, just `cargo audit` warnings.
I ran `cargo update`:
```
Updating actix-web v3.3.2 -> v3.3.3
Removing ansi_term v0.11.0
Updating anyhow v1.0.49 -> v1.0.52
Updating argon2 v0.3.1 -> v0.3.2
Updating async-trait v0.1.51 -> v0.1.52
Adding atomic-shim v0.2.0
Updating blake2 v0.9.2 -> v0.10.0
Adding block-buffer v0.10.0
Updating clap v2.33.3 -> v2.34.0
Updating const_fn v0.4.8 -> v0.4.9
Updating crc32fast v1.2.2 -> v1.3.0
Adding crypto-common v0.1.1
Removing crypto-mac v0.8.0
Removing derivative v2.2.0
Updating derive_more v0.99.16 -> v0.99.17
Adding digest v0.10.1
Updating dirs v3.0.2 -> v4.0.0
Updating encoding_rs v0.8.29 -> v0.8.30
Updating fixedbitset v0.4.0 -> v0.4.1
Updating futures v0.3.18 -> v0.3.19
Updating futures-channel v0.3.18 -> v0.3.19
Updating futures-core v0.3.18 -> …
```

Updating Rust dependencies to resolve audit warnings for 'futures' crates

---

src/rust/Cargo.toml

None, just a quick experiment.
Sets the opt level for dev to 1, which is a minimal optimization level that barely increases compilation time but can significantly increase test performance.
`time make test-integration`
My experiments show that opt-level=1 is twice as fast overall for make test-integration.

opt-level=1 for dev

---

nomad/grapl-core.nomad
nomad/grapl-provision.nomad
nomad/local/integration-tests.nomad
pulumi/grapl/__main__.py

I went through some of our logs and found some loud modules I wanted to keep quiet.

Exclude some modules from rust log debug

---

.buildkite/pipeline.merge.yml

I'm using an unmerged PR for the grapl-rc plugin for the time being,
just to help thoroughly test it. Once we're satisfied it's working as
expected, we'll use a proper release tag.

Update rc plugin to work with shallow clones

---

etc/chromeos/lib/installs.sh
etc/chromeos/setup_chromeos.sh

I'm fixing some issues I discovered with a fresh ChromeOS install. 
- Number one is that issues silently fail due to lack of -euo pipefail.
- nvm didn't install correctly
- pyenv didn't install correctly
- added a docker-compose install via pip

setup_chromeos: fix nvm and pyenv installs on base chromeos; enable -euo pipefail

---

etc/hooks/pre-commit.sh

`./pants fmt <a file with no BUILD>` would previously spit out something like
```
wimax@penguin:~/src/repos/grapl$ git commit -m "Add a wraper around the generated nomad client"
11:38:41.91 [INFO] Starting: Resolving plugins: toolchain.pants.plugin==0.17.0
11:38:44.31 [INFO] Completed: Resolving plugins: toolchain.pants.plugin==0.17.0
11:38:44.41 [WARN] Error loading access token: AuthError('Failed to load auth token (no default file or environment variable). Run `./pants auth-acquire` to set up authentication.')
11:38:44.48 [WARN] Error loading access token: AuthError('Failed to load auth token (no default file or environment variable). Run `./pants auth-acquire` to set up authentication.')
11:38:44.48 [WARN] Auth failed - BuildSense plugin is disabled.
11:38:44.54 [ERROR] 1 Exception …
```

Precommit will ignore files that are not pants-managed

---

etc/hooks/README.md

For some reason, `make format` formats my README differently from origin/main. Prettier is pinned. Very spooky.

etc hooks README is formatted differently by my formatter for some reason

---

Dockerfile.pulumi
etc/formatter/Dockerfile
src/js/engagement_view/build-env.Dockerfile
src/js/graphql_endpoint/Dockerfile
src/python/Dockerfile
src/rust/Dockerfile

Also updates many of our `apt` dependencies. 
Tested with `make test-integration`. CI will exercise `make test-e2e`.

Update many of our Docker images from Buster to Bullseye (deb10 to deb11)

---

pulumi/grapl/__main__.py

Porting something I did for local to aws
https://github.com/grapl-security/grapl/pull/1326
```
cm  6:15 PM
:thinking_face: This keeps failing :point_up: but can be fixed by a retry. The failure is:
creating urn:pulumi:testing::grapl::grapl:NomadJob$nomad:index/job:Job::testing-grapl-core-job: error waiting for job 'grapl-core' to schedule/deploy successfully: error waiting for evaluation: timeout while waiting for state to become 'deployment_successful' (last state: 'monitoring_deployment', timeout: 5m0s)
Have you run into this before @wimax?
wimax  6:16 PM
Let me see if I can debug
cm  6:17 PM
(I manually retried it and it completed successfully)
```
they will be tested in CI after landing 🙄

Add the 8m timeout to aws grapl-core as well

---

Dockerfile.pulumi
nomad/local/integration-tests.nomad
pants.toml
src/rust/Dockerfile
test/docker-compose.integration-tests.build.yml
test/docker-compose.unit-tests-rust.yml

Instead of running these tests via cargo, which requires the presence of
the Rust target/ directory, we copy the test binaries to a small base
image and run the directly. This results in a much smaller container image
size (~770MB) and ensures that we can't accidentally recompile at test runtime.
CI

Change how the Rust integration test container image is made

---

nomad/local/consul-agent-conf.hcl
nomad/local/grapl-local-infra.nomad
nomad/local/nomad-agent-conf.nomad

https://github.com/grapl-security/issue-tracker/issues/811
This enables metric endpoints for consul and nomad in dev.
This is part of the setup for having observability in dev and will allow us to see any memory usage issues
make up
GET http://localhost:4646/v1/metrics?format=prometheus
GET http://localhost:8500/v1/agent/metrics?format=prometheus

Enable metrics for consul and nomad

---

.github/stale.yml

We didn't like that this could allow Dependabot PRs to "disappear",
particularly over long holidays like Christmas.
While we should ensure proper assignment of such PRs to individuals,
this is an easy step we can take to ensure nothing falls through the
cracks.

Don't close Dependabot PRs as stale

---

.buildkite/pipeline.merge.yml

This picks up the changes from
https://github.com/grapl-security/grapl-rc-buildkite-plugin/pull/9,
which should be a more robust fix. Once proven, we'll use a release
tag instead.

Use new RC logic

---

pulumi/grapl/Pulumi.testing.yaml
pulumi/integration_tests/Pulumi.testing.yaml

After processing this file through `pulumi config`, the quotes around
string values are removed. This, in turn, introduces diff noise when
generating a release candidate with our `grapl-rc` plugin.

Remove quotes to reduce diff noise when creating RCs

---

.buildkite/pipeline.provision.yml
.buildkite/pipeline.testing.yml
.buildkite/scripts/grapl_testing_stack/dump_artifacts.sh
.buildkite/scripts/grapl_testing_stack/run_parameterized_job.sh

For some reason, the pulumi update in `pipeline.provision.yml` times out beyond 8m. Moreover, we have zero visibility into _why_ this happens. We previously tried fixing this by bumping from 5 to 8 minutes in https://github.com/grapl-security/grapl/pull/1326
Now, thanks to metahook, we can execute a cleanup command  - `dump_artifacts` - after the command. Hooray!  We'll now be able to see which task within `grapl-core` may be slowing us down.

Grapl Testing Stack dump_artifacts is now a Metahook post-command. Enabled on "pulumi update" in provision.

---

.buildkite/pipeline.verify.yml

Somehow, our Rust unit tests weren't being given the Codecov API
token. Also, our Python typechecking job _did_ have the token, despite
the fact that it doesn't need to interact with Codecov.

Ensure Codecov token is everywhere it's expected

---

.buildkite/pipeline.merge.yml

Update grapl-security/grapl-rc Buildkite plugin version to v0.1.4

---

.github/stale.yml
Makefile
bin/generate_nomad_rust_client.sh
etc/ci_scripts/dump_artifacts/cli.py
nomad/grapl-core.nomad
nomad/local/integration-tests.nomad
src/rust/Cargo.lock
src/rust/Dockerfile
src/rust/nomad-client-gen/src/apis/acl_api.rs
src/rust/nomad-client-gen/src/apis/allocations_api.rs
src/rust/nomad-client-gen/src/apis/deployments_api.rs
src/rust/nomad-client-gen/src/apis/enterprise_api.rs
src/rust/nomad-client-gen/src/apis/evaluations_api.rs
src/rust/nomad-client-gen/src/apis/jobs_api.rs
src/rust/nomad-client-gen/src/apis/metrics_api.rs
src/rust/nomad-client-gen/src/apis/namespaces_api.rs
src/rust/nomad-client-gen/src/apis/nodes_api.rs
src/rust/nomad-client-gen/src/apis/plugins_api.rs
src/rust/nomad-client-gen/src/apis/regions_api.rs
src/rust/nomad-client-gen/src/apis/scaling_api.rs
src/rust/nomad-client-gen/src/apis/search_api.rs
src/rust/nomad-client-gen/src/apis/system_api.rs
src/rust/nomad-client-gen/src/apis/volumes_api.rs
src/rust/plugin-registry/Cargo.toml
src/rust/plugin-registry/src/lib.rs
src/rust/plugin-registry/src/nomad_client.rs
src/rust/plugin-registry/tests/test_nomad_client.rs

For the DeployPlugin stuff [ https://github.com/grapl-security/issue-tracker/issues/722 ], we need to be able to interface with Nomad from one of our own Nomad services. 
This PR is a barebones proof of concept, where we prove we can create a new namespace (one of the steps required for deploying a plugin. see https://github.com/grapl-security/grapl-rfcs/blob/main/text/0000-plugins.md#deployplugin-details )
Also, just some general usability changes throughout, because I'm awful at doing standalone PRs. 
- We print out less junk during `make` (that's what the @s are)
- our test artifacts are slightly more readable
- rust-integration-tests prints out stdout and stderr inline (it's weird when it's split!!!)
---
How I tested:
1. well, I trusted in the power of "the rust test didn't fail when …

Successfully create a Nomad namespace from new NomadClient in rust-integration-tests

---

.buildkite/pipeline.merge.yml

Update grapl-security/grapl-rc Buildkite plugin version to v0.1.5

---

etc/chromeos/lib/installs.sh

We need the SSM extension for anything having to do with prod, for the time being.

Install AWS SSM extensions by default in setup_chromeos

---

src/js/graphql_endpoint/package-lock.json

We have a number of reports and dependabot PRs for vulnerable versions of packages in graphql_endpoint. This is a single PR that should cover all issues found by `npm audit`.
This updates packages in the graphql_endpoint that were reported to have issues by `npm audit`. This diff comes from running `npm audit fix`.
CI

'npm audit fix' for graphql_endpoint.

---

pulumi/infra/postgres.py

turns out our understanding of `name=` was not what I thought it was

Try to fix the postgres database name issue where it was not alphanumeric

---

pulumi/integration_tests/Pulumi.testing.yaml

Followup to https://github.com/grapl-security/grapl/issues/1396
I changed the reader for `container_repository()` to expect `-` not `_`

Change a _ to a -

---

.buildkite/pipeline.verify.yml

It's been a while since these tests were experiencing transient
failures. If they pop up again, we can revisit this.

Remove automatic retries for e2e tests

---

src/rust/Cargo.lock

No issue. Just a hotfix.
I've updated two dependencies.
1. thread_local for RUSTSEC-2022-0006
2. sha2, which was yanked
cargo check

Update sha2 and thread_local to satisfy cargo-audit

---

src/rust/Cargo.toml

None.
One line change. We should use opt-level=1 for all of dev profile, not just test. This way we avoid recompiling.
No additional testing.

We should use opt-level 1 for all of dev

---

etc/ci_scripts/dump_artifacts/cli.py
etc/ci_scripts/dump_artifacts/nomad_artifacts.py

Previously:
~/src/repos/grapl/test_artifacts/ **_grapl-integration_tests__** 2022-01-24T16-47-27/ **_nomad_** /grapl-local-infra
now:
~/src/repos/grapl/test_artifacts/2022-01-20T15-59-34/grapl-local-infra

Make test artifact paths shorter

---

.buildkite/pipeline.verify.yml

As part of a larger push to lock down our CI/CD environment, we are
removing jobs from our verify pipeline that interact with AWS
infrastructure. This pipeline is the only one that runs prior to a
merge (and is thus gated by human reviewers), and the `pulumi preview`
job is the only one that interacts with AWS.

Remove pulumi preview job from verify pipeline

---

src/python/e2e-test-runner/e2e_test_runner/test_main.py

None AFAIK, this was a one off fix.
Rather than making flaky assertions about the graph in the e2e tests this change makes a more general assertion. The suspcious svchost signature always produces at least 3 nodes, which means that's the lower bound we expect, so that's the only assertion we make.
Normal e2e tests.

Change e2e assertion to only look for >= 3 vs a specific number

---

.buildkite/pipeline.merge.yml
.buildkite/pipeline.provision.yml

We recently retired the artifact-uploaders queue, since it was used
for uploading lambda zip files to Cloudsmith, and we no longer use
lambda functions.
However, they were also being used for promoting artifacts from one
repository to another. For that, we can just use the `docker` queue,
which also has access to the Cloudsmith API key, which is the main
thing we care about here.

Switch from artifact-uploaders queue to docker for promotions

---

etc/chromeos/lib/installs.sh
etc/chromeos/setup_chromeos.sh
nomad/local/nomad-agent-conf.nomad
nomad/local/start_detach.sh

This is needed for DeployPlugin stuff, which uses the Firecracker driver.

Install Nomad firecracker (+ CNI plugin) with setup_chromeos.sh

---

etc/ci_scripts/dump_artifacts/nomad_artifacts.py
src/rust/plugin-registry/src/static_files/plugin.nomad
src/rust/plugin-registry/tests/test_create_plugin.rs
src/rust/plugin-registry/tests/test_nomad_client.rs

Relates to grapl-security/issue-tracker#722
Previously we only dumped artifacts in the "default" namespace. Now we do every namespace!

Update dump_artifacts to account for multiple Nomad namespaces (plugins)

---

src/rust/plugin-registry/src/db_client.rs
src/rust/plugin-registry/src/deploy_plugin.rs
src/rust/plugin-registry/src/lib.rs
src/rust/plugin-registry/src/server.rs
src/rust/plugin-registry/tests/test_deploy_plugin.rs

Followup to grapl-security/issue-tracker#722
Previously, the Plugin Registry postgres queries were baked into the main controller `server.rs`; this has now been refactored out to a `PluginRegistryDbClient` so that other pieces of the PluginRegistry can reuse it.
Previously, DeployPlugin was just deploying a job with garbage standin data.
Now, it consumes the PluginRegistryDbClient to populate a job with real data from a previous CreatePlugin call.
Integration tests!!!

Refactor PluginRegistry SQL queries into a DbClient. DeployPlugin now consumes DbClient.

---

nomad/e2e-tests.nomad
src/python/Dockerfile

At some point I asked for a shortened E2E input and I totally forgot to integrate it into the e2e tests. 
Seems to run in less time but double checking against CI

Use the shorter, 36-line E2E test input

---

src/rust/Dockerfile

None. Hotfix.
Adds a lock to the cache mounts in src/rust/Dockerfile.
I've added the lock everywhere because, as far as I know, none of the cases where we use cache mounts are safe to share. Plus, even if they are, like in some cases with cargo build, it should be any more efficient to let cargo do the waiting vs docker.
Just rebuild.

Lock cache mounts

---

etc/formatter/Dockerfile
postgres/Dockerfile
src/rust/Dockerfile

We've seen a few build failures with:
```
#121 4.269 E: Could not get lock /var/lib/apt/lists/lock. It is held by process 0
```
We figure this is due to the fact that a Dockerfile `RUN --mount=type=cache` uses the `target` for an id, which is shared across all other Dockerfiles, and that we have multiple Dockerfiles mounting `/var/lib/apt/lists` when running `apt`. So they were fighting for the apt lock file.
This gives each `RUN --mount=type=cache` a unique `id` per Dockerfile and per base image within that Dockerfile. Note the Rust Dockerfile has two different runs of `apt`, from two different bases images.
The motivation is twofold:
- help prevent lock contention
- isolate apt caches from different builds do they can't pollute each other's filesystem. Ex: formatter cache can't affect …

Give Dockerfile apt mount caches unique ids

---

pants.toml

Followup to https://github.com/grapl-security/grapl/pull/1427/files
```
extra_type_stubs = [
"mypy_boto3_cloudwatch",
"mypy_boto3_dynamodb",
```
famous last words

Pin mypy_boto3 versions

---

test/run/integration-tests-from-docker-container.sh

its a 2 line change
relates to this weird transient error
```
2:04
18:34:54.82 [ERROR] 1 Exception encountered:
ValueError: Failed to create directory /mnt/grapl-root/dist/coverage/python: Failed to create dir "/mnt/grapl-root/dist/coverage/python" due to Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
```
@ https://grapl-internal.slack.com/archives/C02JCBKS97V/p1643742241129789

Disable coverage in integration tests

---

.gitattributes
src/rust/plugin-registry/Cargo.toml
src/rust/plugin-registry/sqlx-data.json
src/rust/plugin-registry/src/db/client.rs

Now we no longer have any bare, macro-less sqlx in plugin-registry.

Use the sqlx::query! macro on plugin-registry

---

.buildkite/pipeline.verify.yml

Update grapl-security/codecov Buildkite plugin version to v0.1.1

---

etc/chromeos/lib/installs.sh
nomad/lib/nomad_cli_tools.sh

Basically adds `--proto "=https" --tlsv1.2` to all the `curl`
invocations I could find.
Also translates short options to long options for readability.

Invoke `curl` in a more secure way

---

nomad/e2e-tests.nomad
pulumi/grapl/__main__.py
pulumi/infra/kafka.py
pulumi/integration_tests/__main__.py
src/python/e2e-test-runner/e2e_test_runner/test_kafka.py

https://github.com/grapl-security/issue-tracker/issues/824
These changes update the kafka e2e tests to be a little more robust in a scenario where we have more than one writer to the logs and metrics topics (expected), multiple partitions (expected), and consumer groups (expected). Additionally, I've updated the e2e testing and confluent cloud infrastructure to work with kafka running in confluent cloud when the e2e tests are run in aws.
Corresponding confluent cloud infrastructure changes are here: https://github.com/grapl-security/confluent-cloud-infrastructure/pull/2
Ran e2e tests locally and in my aws sandbox.

updates to make the kafka e2e tests run in aws

---

nomad/local/grapl-local-infra.nomad
pulumi/grapl/__main__.py
pulumi/infra/postgres.py
src/js/engagement_view/src/components/dashboard/Dashboard.tsx

none
fixes pulumi code for abstracting over a postgres database, before it was emitting stuff like this in the grapl stack outputs:
```
"plugin-work-queue-db-port": "<pulumi.output.Output object at 0x7ebfe8beaf50>"
```
now it outputs a port instead:
```
Previewing update (grapl/jgrillo-sandbox)
View Live: https://app.pulumi.com/grapl/grapl/jgrillo-sandbox/previews/4b3fd2eb-c923-4a8e-b39c-a381d9cf72d4
Type                   Name                                 Plan       Info
pulumi:pulumi:Stack    grapl-jgrillo-sandbox                           
├─ grapl:NomadJob      grapl-core                                      
~   │  └─ nomad:index:Job  jgrillo-sandbox-grapl-core-job       update     [diff: 
└─ grapl:NomadJob      grapl-provision                                 
~      └─ …
```

some pulumi fixes

---

.buildkite/pipeline.merge.promote.yml
.buildkite/pipeline.merge.yml
.buildkite/scripts/build_and_upload_containers.sh
.buildkite/scripts/lib/artifacts.sh
.buildkite/scripts/upload_promotion_step_if_needed.sh

Due to what appears to be a Cloudsmith bug, we seem to be losing
images (tags, really) when we promote containers from our `raw`
repository to the `testing` repository. Cloudsmith detects that the
bytes of the image exist in the destination and thinks its job is
done; it doesn't seem to carry tags over, however. This manifests by
us not being able to find images in the `testing` repository, even
though it looks like Cloudsmith promoted them.
What we'll do now is add an additional check to help us assemble our
final list of artifacts to be promoted. We'll query the `testing`
repository to see if an image with the same sha256 sum as the one we
just built already exists there. If it does, then we must be dealing
with a service that hasn't changed since it was last pushed. In this
case, we'll …

Only promote artifacts if they're not in the destination already

---

.buildkite/scripts/build_and_upload_containers.sh

We only need to run `make build-test-e2e`, since `build` is already
declared as a prerequisite of that target.

Simplify invocation to build all images in CI

---

.buildkite/scripts/build_and_upload_containers.sh
.buildkite/scripts/lib/artifacts.sh
.buildkite/scripts/lib/artifacts_test.sh

We've now got Bash 5 in CI, so we don't need to jump through these
awkward hoops for possibly-empty arrays anymore.
This is a follow-on to https://github.com/grapl-security/issue-tracker/issues/773

Remove Bash 4.x-ism processing arrays

---

.buildkite/pipeline.merge.yml

We build several PEXes for our Python containers; we may as well take
advantage of the remote cache to improve the overall speed of our
builds.

Add TOOLCHAIN_AUTH_TOKEN when building images

---

src/rust/plugin-registry/Cargo.toml
src/rust/plugin-registry/migrations/20220202225101_create_plugin_deployment_table.sql
src/rust/plugin-registry/sqlx-data.json
src/rust/plugin-registry/src/db/client.rs
src/rust/plugin-registry/src/db/mod.rs
src/rust/plugin-registry/src/db/models.rs
src/rust/plugin-registry/src/server/deploy_plugin.rs
src/rust/plugin-registry/src/server/service.rs
src/rust/plugin-registry/tests/test_deploy_plugin.rs
src/rust/plugin-registry/tests/test_nomad_client.rs

https://github.com/grapl-security/issue-tracker/issues/722
Satisfies the "[If success, mark plugin as being deployed in plugins table" ](https://github.com/grapl-security/grapl-rfcs/blob/main/text/0000-plugins.md#nomad-job) requirement.
I'm not really that convinced that this is _useful_, since we just track that a deployment was successfully attempted - not that it is healthy - but I can see it being useful as an audit-log.

Add a `plugin_deployment` table. Register DeployPlugin success/fail in the table. 

---

.buildkite/pipeline.deploy.yml
.buildkite/pipeline.merge.yml
.buildkite/pipeline.provision.yml
.buildkite/pipeline.verify.yml

Update grapl-security/grapl-release Buildkite plugin version to v0.1.1
---

Update grapl-release Buildkite Plugin to v0.1.1

---

.buildkite/pipeline.verify.yml

I think with this, we could actually remove Rust from our CI builder
nodes, since the rest of our Rust interactions in CI occur in
containers already.

Use Rust image for formatting and linting in CI

---

nomad/grapl-core.nomad
pulumi/grapl/__main__.py
src/rust/plugin-registry/src/nomad/cli.rs
src/rust/plugin-registry/src/server/deploy_plugin.rs
src/rust/plugin-registry/src/server/service.rs
src/rust/plugin-registry/src/static_files/plugin.nomad

Previously we had a static image `grapl/plugin-execution-sidecar` image, this now plumbs it in from
Pulumi => grapl-core.nomad => plugin registry env vars => `plugin.nomad`

Plumb the plugin-bootstrap/plugin-execution container images from `grapl-core.nomad` container_images= into `plugin.nomad`

---

Makefile
src/python/analyzer_executor/src/BUILD
src/python/engagement-creator/engagement_creator/BUILD
src/python/provisioner/provisioner/BUILD

Just a tiny quality-of-life improvement I spotted in the course of larger refactorings.

Use Pants tags to declaratively maintain the list of service PEXes

---

Makefile

This is a vestige of the early Nomad days when we were also running a
local registry.

Remove unused `push` Makefile target

---

etc/chromeos/lib/installs.sh

This ensures that both the old and new versions of Docker Compose are
present on our workstations.
We still use the old Docker Compose (invoked as `docker-compose`) in
our Makefiles, scripts, etc., but this will enable us to start
migrating over to the new Docker Compose (invoked as `docker compose`;
note the space).

Install Docker Compose v2 CLI plugin

---

pulumi/infra/config.py

No more lambdas, no more lambda tags.

Remove unused GLOBAL_LAMBDA_ZIP_TAG

---

.buildkite/pipeline.verify.yml
docker-compose.build.yml
docker-compose.yml
pulumi/infra/docker_images.py
test/docker-compose.integration-tests.build.yml
test/docker-compose.unit-tests-js.yml
test/docker-compose.unit-tests-rust.yml

Another change made in service of ultimately revising our image build and management processes.
We had multiple places that could be injecting default or fallback values for our `TAG` environment variable, making it tricky to find any single source of truth for that information.
Now, all the fallback values are removed, with the exception of one in the `Makefile`. This will make things easier to reason about.

Make source of TAG values more obvious

---

.buildkite/pipeline.verify.yml

Update grapl-security/codecov Buildkite plugin version to v0.1.2
---

Update grapl-security/codecov Buildkite Plugin to v0.1.2

---

nomad/e2e-tests.nomad
nomad/grapl-core.nomad
nomad/grapl-provision.nomad
nomad/local/integration-tests.nomad
pulumi/grapl/__main__.py
pulumi/integration_tests/__main__.py

Some simplifications:
- Unify the 3 environment variables as one; previously we had this weird behavior of "uh yeah if 1 of them exists we use all 3"
- As such, I moved the template string up to the Pulumi level
- Export the fully templated variable so other stacks can use it (i.e. pulumi/integration_tests)
- Remove any defaults from Nomad, and pull them up to Pulumi (this makes exporting it easier)

Also simplify the aws-local-only-env-vars

---

.buildkite/pipeline.verify.yml

I just discovered that Codecov tokens are per-repository, and not
per-organization. Previously, our `grapl` repository token was stored
in our secrets engine under simply `CODECOV_TOKEN`.
Now, we use a similar pattern to how we manage
`TOOLCHAIN_AUTH_TOKEN`s, by putting the `CODECOV_TOKEN` in a directory
that corresponds to its repository.

Update Vault address for CODECOV_TOKEN

---

pulumi/grapl/__main__.py

specified this for local, not aws.
there are more robust ways to catch this scenario outlined here
https://grapl-internal.slack.com/archives/C02J5JYS92S/p1643152387102800?thread_ts=1643150212.095800&cid=C02J5JYS92S
but I didn't do that here because this is a midnight change

fix pulumi/grapl for prod, missed a nomad var

---

.buildkite/pipeline.verify.yml
codecov.yml

The annotates lines of a PR that are introduced but not covered by
tests. Currently, this causes a lot noise, particularly for Pulumi
code.
I don't see a way to keep `codecov/patch` enabled, but for it to
ignore everything under `pulumi`; if we could sort that out, it may be
a preferable solution. For the time being, however, we'll just stop
doing the patch status checks.
It would be good to re-enable them in the future, however. Time for
more research!

Disable the `codecov/patch` status check

---

pulumi/grapl/__main__.py
pulumi/infra/hashicorp_provider.py
pulumi/infra/upstream_stacks.py
pulumi/integration_tests/__main__.py

This further reduces chance of https://github.com/grapl-security/grapl/pull/1486 type whifs by unifying the if-else branch for local and prod
you'll likely want to go through it commit-by-commit cm style

Pull some variables and resources out of pulumi/grapl's `if local {} else prod {}`, further unifying these two cases. 

---

.buildkite/pipeline.verify.yml
.buildkite/scripts/build_and_upload_containers.sh
Makefile
nomad/bin/run_parameterized_job.sh
nomad/local/nomad_run_local_infra.sh
src/js/engagement_view/Makefile
src/python/Dockerfile
src/python/e2e-test-runner/e2e_test_runner/BUILD
src/python/graplctl/graplctl/BUILD

In the course of reworking some Docker-related stuff, it became apparent that our existing Makefile targets were a bit more complicated than necessary. They have now been rearranged to better reflect the true underlying dependency structure.
I also added some additional logging output for the benefit of our Buildkite runs of our integration and e2e tests, as well as enabled our remote build cache for those tests, which should help speed things up a bit.
Read the individual commits for further details.

Assorted Makefile cleanups and refactorings

---

.buildkite/pipeline.cargo-audit.sh

Use the same Rust version for `cargo audit` as the rest of our code

---

.buildkite/pipeline.verify.yml
src/rust/analyzer-dispatcher/src/dispatch_event.rs
src/rust/bin/format
src/rust/generators/sysmon-generator/src/models/process/create.rs
src/rust/rust-toolchain.toml

Update Rust Version

---

Makefile

This looks like a refactoring I missed in #1496.

Fix the `up` Makefile target

---

src/rust/Dockerfile

`libssl-dev` and `pkg-config` are only required for compiling
`cargo-tarpaulin` (and nothing else), so we'll move those
installations to the `tarpaulin` target to localize them better.
`build-essential` and `zlib1g-dev` appear to be superfluous at this
point, so they have been removed.
Finally, the reason why we install the rest of the packages is shared
in a comment.

Clarify which packages we must install in Rust Dockerfile, and why

---

src/rust/Cargo.lock
src/rust/grapl-graphql-codegen/Cargo.toml
src/rust/plugin-bootstrap/Cargo.toml
src/rust/plugin-registry/Cargo.toml
src/rust/plugin-sdk/generator-sdk/Cargo.toml
src/rust/plugin-work-queue/Cargo.toml

Since our usage of Structopt is limited to servers, which won't be
invoked by humans, we don't actually need several crates that Clap
uses under the hood for nice UX, such as ANSI color codes and
suggestions for mistyped commands. By disabling Structopt's default
features, we can eliminate these crates, shaving a bit off our compile
times (it won't be a ton, but every little bit helps).
(See https://docs.rs/structopt/latest/structopt/#features for
details.)

Slim down our Structopt crate usage

---

.github/CODEOWNERS

Slight rearrangement of the CODEOWNERS file so that I get tagged for
any `Makefile` updates.

`@christophermaier` owns Makefiles

---

.buildkite/pipeline.verify.yml

Our verify pipeline was getting a bit scattered and
disorganized. Buildkite also recently released a new "groups" feature
for pipelines to help with this exact scenario.
Thus, we now have groups :)
See https://buildkite.com/blog/announcing-the-new-group-step-type for
additional details.
(The only "bad" thing about this is with the audit jobs... due to how
the `chronotc/monorepo-diff` plugin currently works, group membership
cannot be propagated into the jobs that are ultimately uploaded to the
pipeline. This makes sense, though, because the groups functionality
is new. An issue has been filed, though:
https://github.com/chronotc/monorepo-diff-buildkite-plugin/issues/82. Despite
this, I still think that the organizational benefits gained are worth
it. As an alternative, we could just run …

Reorganize "verify" Buildkite pipeline with the new "groups" feature

---

.buildkite/pipeline.cargo-udeps.sh
.buildkite/pipeline.verify.yml

It's good to periodically check to ensure we're using all our Rust
dependencies.
It runs each time `Cargo.toml` or `Cargo.lock` files are changed; any
failures are purely advisory. Like our `cargo audit` job, it also runs
on a weekly basis with non-advisory failures.

Add `cargo udeps` job to CI

---

.buildkite/pipeline.verify.yml
Makefile
src/rust/BUILD

We now lint our Pants BUILD files in Buildkite.
Because this was missing, we had a single BUILD file that wasn't
properly formatted.

Lint BUILD files

---

Makefile

I previously missed this hidden dependency in a recent Makefile
refactoring. Now, we'll always ensure the directory is present before
trying to build a kernel.

Add `dist` as an order-only prerequisite for Firecracker kernel

---

src/rust/Cargo.lock
src/rust/sysmon-parser/Cargo.toml
src/rust/sysmon-parser/benches/benches.rs

The sysmon-parser crate had a benchmark against the 'sysmon' crate that it replaced, which had a git dependency in the Cargo.toml. This comparison is no longer necessary and was increasing Rust build times.
This remove the git dependency from sysmon-parser's Cargo.toml and removes the benchmark against the previous 'sysmon' crate.
I ran `cargo bench` under `src/rust/sysmon-parser`.

Remove the sysmon-parser benchmark against the previous sysmon crate.

---

Makefile
nomad/lib/nomad_cli_tools.sh
src/rust/Dockerfile

None. Adhoc request from Andrea.
Add a utility function that makes it easy to rebuild and redeploy Engagement View changes to a currently running `make up` session.
Time to run with no changes: 7s (mostly existing tech debt in engagement-view Makefile that always reruns a .PHONY)
Time to run with changes: 2m32s, mostly rust compilation
*Over 1 minute of that time-to-run may disappear ASAP*: See [this thread.](https://grapl-internal.slack.com/archives/C02J5JYS92S/p1646876969973139)
For comparison, a full up/down (with no code changes) is 5m5s + 17s
Make a small UI change to engagement-view
Run `make restart-web-ui`
go to localhost:1234 to see it reflected there.

Add 'make restart-web-ui' to make frontend dev loop quicker than full down/up

---

.gitignore
Makefile
src/js/engagement_view/.gitignore
src/js/engagement_view/.yarn/state/.gitignore
src/js/engagement_view/Makefile
src/js/engagement_view/build-env.Dockerfile

Rather than building the build container image before every operation,
we'll use some empty target files and some finer-grained prerequisites
to better capture the true dependencies.
Of particular note:
- The `ASSET_FILTER`/`ASSET_FILES`/`ASSET_DIRS` macros were too
permissive. Rather than filtering out files we don't care about, now
we just specify the files we _do_ care about in the `FILES` macro.
- More complete cleanup is done in the `clean` target.
- No more `.gitkeep` files to preserve `.yarn/state` and
`node_modules`. The `.gitignore` rules for these files didn't actually
work, and in any event, it's easier to ensure these directories exist
by creating targets for them. This also allows us to easily clean
these directories from the `clean` target.
- A new `shell` target is added to …

Update engagement-view Makefile

---

.dockerignore

This updates the top-level .dockerignore file to match not just `src/rust/target`, but all directories named `target` under `src/rust`, which can happen when building one of the crates individually.
I realized I had large (hundreds of MB) context transfers for Rust Dockerfile stages, which didn't seem right. Turns out this was due to a directory `src/rust/generators/sysmon-generator/target` I had from working with that crate directly.
With this change I noticed these context transfer sizes were much closer to the size of the sources under proto and rust.

Update .dockerignore to match all sub-directories under src/rust named 'target'

---

firecracker/packer/scripts/install_dependencies.sh
src/js/graphql_endpoint/Dockerfile
src/rust/Dockerfile
src/rust/build-env.Dockerfile

Resolves the following Slack post I made:
```
Potential deps issue:
src/rust/Dockerfile specifies libssl-dev
libssl-dev=1.1.1k-1+deb11u1 \
i got this error in ci:
#9 2.635 Some packages could not be installed. This may mean that you have
#9 2.635 requested an impossible situation or if you are using the unstable
#9 2.635 distribution that some required packages have not yet been created
#9 2.635 or been moved out of Incoming.
#9 2.635 The following information may help to resolve the situation:
#9 2.635
#9 2.635 The following packages have unmet dependencies:
#9 2.682  libssl-dev : Depends: libssl1.1 (= 1.1.1k-1+deb11u1) but 1.1.1k-1+deb11u2 is to be installed
https://buildkite.com/grapl/grapl-verify/builds/2889#06ee30e2-1d1f-4257-97fd-01003e75164f
```
our theory is deb11u1 was yanked

Upgrade libssl in some dockerfiles to 1.1.1k-1+deb11u2

---

.buildkite/pipeline.verify.yml

This is a temporary stopgap measure for https://github.com/grapl-security/issue-tracker/issues/880 that allows other devs to continue to run grapl CI without blocking them. 
I opted for `soft_fail` instead of straight-up removal so I could continue to collect different failure modes; I was kind of shocked when it failed once-after-another in 2 different ways.

Soft-fail rootfs builds in CI until we figure out what's going on

---

.buildkite/pipeline.verify.yml
Makefile
firecracker/packer/build-rootfs.pkr.hcl

https://github.com/grapl-security/issue-tracker/issues/880
- Resolve the issues in https://github.com/grapl-security/issue-tracker/issues/880 - there were startup commands happening I didn't know about that were conflicting with our `apt` commands.
- Change to server-minimal; results in slightly shorter build time (fewer things occurring at AMI startup)
- Change to us-east-2; the less hardcoded us-east-1 the better
- Document a CLI command to get latest AMI
thanks thomas for pointing out this possibility!
I'm reasonably convinced this resolves the nondeterminism. I ran it 10x in a row:
```
set -euo pipefail
for i in {1..10}
do
echo "Attempt ${i}"
make dist/firecracker_rootfs.tar.gz || \
(echo "Attempt ${i} failed!" && exit 1)
rm dist/firecracker_rootfs.tar.gz
done
```
I also tested and …

Resolve apt failures with a 'cloud-init status --wait', change to server-minimal us-east-2 AMI

---

nomad/local/grapl-local-infra.nomad

This was originally an attempt to bring down the time to boot Localstack (currently 1 minute on our Chromebooks for s3 to become healthy). 
Didn't really change anything, but cleans stuff up :+1:

Remove unused services from Localstack

---

firecracker/generate_firecracker_kernel.sh
firecracker/packer/scripts/create_rootfs_image.sh

https://github.com/grapl-security/issue-tracker/issues/866
Previously if you untar'd the archive it'd be super duper nested in like 5 folders; this fixes it.
Ran the make for the kernel
ran tar -xvf
it extracted the kernel right into the directory :+1:

Fix 866 - Firecracker kernel .tar.gz was super nested

---

src/rust/Cargo.lock
src/rust/grapl-web-ui/Cargo.toml
src/rust/grapl-web-ui/src/authn/user.rs
src/rust/grapl-web-ui/src/config.rs
src/rust/grapl-web-ui/src/main.rs
src/rust/grapl-web-ui/src/routes/login.rs
src/rust/grapl-web-ui/src/services/graphql.rs
src/rust/grapl-web-ui/src/services/mod.rs
src/rust/grapl-web-ui/src/services/model_plugin_deployer.rs

This upgrades to actix-web 4 for the grapl-web-ui, which allows us to get rid of some ugly hacks where we had to mix tokio runtimes.
This has a nice side benefit of reducing the number of duplicate dependencies in our Rust workspace. The number of dependencies goes from 677 to 652. Still a lot, but as d0nut would say "we take those".
There's a bunch of other cleanup I want to do, like clean and improve the errors, but I'll save for another PR.
CI

Upgrade to actix-web 4

---

.buildkite/pipeline.cargo-udeps.sh
src/rust/Makefile
src/rust/bin/udeps

The main logic is extracted into a script and then run in our build
container via a make target.
I didn't bother plumbing this through to the top-level Makefile since
it's not generally something that needs to be run by developers on a
regular basis (they _can_, of course, but it's really more of a CI
thing).
This is to make things more robust as we add new system dependencies
that are necessary for compiling our Rust code.
(A bonus `shell` target was added for debugging, as well.)

Run cargo-udeps in our build container

---

src/rust/Cargo.lock
src/rust/sysmon-parser/Cargo.toml
src/rust/sysmon-parser/src/event.rs
src/rust/sysmon-parser/src/event_data.rs
src/rust/sysmon-parser/src/event_data/file_create.rs
src/rust/sysmon-parser/src/event_data/network_connect.rs
src/rust/sysmon-parser/src/event_data/process_creation.rs
src/rust/sysmon-parser/src/event_data/process_terminated.rs
src/rust/sysmon-parser/src/system.rs
src/rust/sysmon-parser/src/system/correlation.rs
src/rust/sysmon-parser/src/system/event_id.rs
src/rust/sysmon-parser/src/system/execution.rs
src/rust/sysmon-parser/src/system/provider.rs
src/rust/sysmon-parser/src/system/security.rs
src/rust/sysmon-parser/src/system/time_created.rs

This adds a create feature for including serde derive Serialize and Deserialize for the types provided by the sysmon-parser crate. This new feature is included by default.
We aren't making use of these derived methods at the moment in Grapl and there are no immediate plans for that yet, but this library intends to be useful outside of use in Grapl, and effectively (eventually?) replace the public `sysmon` crate that Colin wrote a while ago (that we were previously using): https://crates.io/crates/sysmon. These are generally helpful for public types and I wanted to knock this out now while I was working with it.
The feature flag for this was added because I want it to be generally usable publicly, putting serde behind a flag seems like a decent feature to _optionally_ include, as many …

Add a 'serde' feature flag to derive Serialize and Deserialize for

---

.gitignore

Generated artifacts and coverage reports get dumped into this
directory and should not be committed.
(I'm fairly certain I forgot to add this change during my recent
change to how we manage the `dist` directory in our Makefile; mea
culpa.)

Ignore `dist` directory

---

src/rust/generators/sysmon-generator/src/generator.rs
src/rust/generators/sysmon-generator/src/models.rs
src/rust/generators/sysmon-generator/src/models/file/create.rs
src/rust/generators/sysmon-generator/src/models/network/inbound.rs
src/rust/generators/sysmon-generator/src/models/network/outbound.rs
src/rust/generators/sysmon-generator/src/models/process/create.rs
src/rust/generators/sysmon-generator/src/serialization.rs

This improves logging in the Sysmon generator in a number of small ways:
- add new tracing instrumentation.
- provide additional logging.
- skip instrumenting `body` param for impl for PayloadDecoder. that was blowing up logs and wasn't helpful.
- remove redundant event filtering.
Inspecting logs from the Sysmon generator before and after these changes while debugging the generator.

Improve logging in Sysmon generator

---

.github/CODEOWNERS
buf.yaml
etc/chromeos/lib/installs.sh
src/proto/graplinc/common/v1beta1/types.proto
src/proto/graplinc/grapl/api/pipeline_ingress/v1beta1/pipeline_ingress.proto
src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/Dockerfile
src/rust/Makefile
src/rust/build-env.Dockerfile
src/rust/kafka/Cargo.toml
src/rust/kafka/src/lib.rs
src/rust/rust-proto-new/Cargo.toml
src/rust/rust-proto-new/build.rs
src/rust/rust-proto-new/src/graplinc/common/v1beta1.rs
src/rust/rust-proto-new/src/graplinc/grapl/api/pipeline_ingress/v1beta1.rs
src/rust/rust-proto-new/src/graplinc/grapl/pipeline/v1beta1.rs
src/rust/rust-proto-new/src/graplinc/grapl/pipeline/v1beta2.rs
src/rust/rust-proto-new/src/lib.rs
src/rust/rust-proto-new/tests/integration_test.rs

https://github.com/grapl-security/issue-tracker/issues/580
This PR updates some ergonomics in `rust-proto-new`, particularly `SerDe::serialize()` now returns an owned `Bytes` instead of mutating a reference to a buffer.
Additionally, we have added a `kafka` library to encapsulate the `rust-rdkafka` dependency in such a way that the library types `Consumer<T>`, `Producer<T>`, and `StreamProcessor<T, U>` transparently handle serializing and deserializing our `rust-proto-new` types.
- The `rust-proto-new` changes are well covered by automated tests.
- *TBD:* The `kafka` library will be exercised in integration tests (not written yet).

internal 580 kafka library

---

src/rust/grapl-graphql-codegen/src/main.rs

None, this is a one line fix.
Avoids generating a glob import, which is unnecessary. Imports the types it needs explicitly instead.
I ran flake8 and mypy on the generated code.

Avoid glob import

---

src/js/graphql_endpoint/Dockerfile
src/rust/Dockerfile
src/rust/build-env.Dockerfile

Noticed the following in our weekly maintenance build:
```
#7 3.729 The following packages have unmet dependencies:
#7 3.840  libssl-dev : Depends: libssl1.1 (= 1.1.1k-1+deb11u2) but 1.1.1n-0+deb11u1 is to be installed
#7 3.861 E: Unable to correct problems, you have held broken packages.
```
~ https://buildkite.com/grapl/grapl-verify/builds/3061

Update libssl-dev to 1.1.1n-0+deb11u1

---

.buildkite/scripts/build_and_upload_images.sh

We're still occasionally seeing failures to pull manifests after a
container image upload to Cloudsmith. We'll try sleeping a bit longer
:(

Bump container image upload sleep from 30 to 60 seconds

---

.buildkite/pipeline.merge.yml

https://buildkite.com/grapl/grapl-merge/builds/573#a57b6130-9723-42ce-be57-a4cb8eb97432 failed due to
```
0.4s
--
  | ./firecracker/rootfs/build.sh
  | Installed plugin github.com/hashicorp/amazon v1.0.8 in "/var/lib/buildkite-agent/.config/packer/plugins/github.com/hashicorp/amazon/packer-plugin-amazon_v1.0.8_x5.0_linux_amd64"
  | Error: Datasource.Execute failed: Error querying AMI: UnauthorizedOperation: You are not authorized to perform this operation.
  | status code: 403, request id: f0695d2a-643f-4eba-9977-318074592a73
  |  
  | on firecracker/rootfs/build-rootfs.pkr.hcl line 80:
  | (source code not available)
```
Makes sense, the "docker" queue wasn't the right tool for this ("packer" has more AWS perms). 
I'm reasonably sure we do not need the "docker" queue for building the …

Try switching the "build firecracker packages" to packer queue

---

.buildkite/pipeline.merge.yml
.buildkite/scripts/lib/artifact_metadata.sh
.buildkite/scripts/upload_firecracker_packages.sh

https://github.com/grapl-security/grapl/pull/1578 didn't work, so this is a more robust solution.
- Previously we were building and uploading our FIrecracker packages all in one Buildkite step.
- Turns out, that's really finicky, since our different agents have different keys granted to them.
- So now we split up the building and the uploading into different steps.
hah, good joke

Split up 'build_and_upload_firecracker_packages' into two build steps and one upload step

---

nomad/grapl-core.nomad
pulumi/grapl/Pulumi.local-grapl.yaml
pulumi/grapl/__main__.py
pulumi/infra/firecracker_assets.py
src/rust/plugin-registry/src/server/deploy_plugin.rs
src/rust/plugin-registry/src/server/service.rs
src/rust/plugin-registry/src/static_files/plugin.nomad

https://github.com/grapl-security/issue-tracker/issues/742
Relates to https://github.com/grapl-security/issue-tracker/issues/857
Upload the Firecracker rootfs asset to S3 in both prod and local (this decision can be re-litigated later; see the above 857 issue).
This is the same thing we currently do for the kernel.
~then~ we pipe the s3url all the way from:
Pulumi -> grapl-core.nomad -> plugin-registry -> plugin.nomad
the plugin task group still fails because it tries to download the artifact for plugin, but that's something I'll solve in a later PR.

Firecracker Rootfs asset: upload to S3, and pipe all the way through to plugin.nomad

---

.buildkite/pipeline.merge.yml
.buildkite/pipeline.provision.yml
.buildkite/pipeline.verify.yml

Update grapl-security/grapl-release Buildkite plugin version to v0.1.2
This is to pick up better logging functionality.
---

Update grapl-security/grapl-release Buildkite Plugin to v0.1.2

---

pulumi/grapl/Pulumi.local-grapl.yaml

These have the newly renamed artifacts in them.

Update which prebuilt rootfs/kernel we use for local-grapl

---

.buildkite/pipeline.verify.yml

Update grapl-security/codecov Buildkite plugin version to v0.1.6
---

Update grapl-security/codecov Buildkite Plugin to v0.1.6

---

.buildkite/pipeline.verify.yml
.gitignore
Makefile
src/js/engagement_view/.gitignore
src/js/engagement_view/Makefile
src/js/engagement_view/package.json
src/js/engagement_view/src/components/graphDisplay/GraphDisplay.tsx
src/js/engagement_view/yarn.lock

None
- Instead of the full react-force-graph which contains like WebGL WebVR lots of 3D useless stuff - just include the 2D version. Built JS goes from 15MB to 5MB.
- Use `source-map-explorer` in CI to generate a report of what's using how much space. It'll be uploaded as an artifact.
A note: We just upload it as an artifact in e2e/integration-test CI; there's no better spot for it currently. 
Tested locally with make build-code; let's see how it behaves in CI.

Switch from React-Force-Graph to React-Force-Graph-2D. Report the source-map-explorer results to CI. 

---

etc/chromeos/lib/installs.sh

On origin/main, when this script had previously been already run, it took 8m36s *and* some confirmation prompts (for the timing I did it *as soon* as the prompt showed up on screen) to rerun
Now, when there's a previous run, it takes 35s and is zero touch.
I did not hit _every_ dependency, just the ones that take long (especially the cargo install compilations)

etc/chromeos/lib/installs.sh - stop reinstalling existing stuff unless FORCE_REINSTALL=1 

---

etc/chromeos/lib/installs.sh

slash, any other distro that doesn't have XDG_CONFIG_HOME set up. The existing code assumes the NVM dir will be ~/.config/nvm; we now *declare* that to be so.
Compare with https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh

Make etc/chromeos nvm install work in gitpod

---

src/rust/grapl-graphql-codegen/src/node_type.rs

This fixes an issue we found in the GraphQL schema -> Python codegen: a Node's Viewable was missing the `node_schema` override.
1. I first made the desired change in my generated Python, and verified it resolved the issue I had. I then,
2. Verified this diff produced code similar to that change I'd tested previously.

[GraphQL->Python codegen] Add node schema method to Node Viewable.

---

.github/CODEOWNERS
devbox/devbox-do.sh
devbox/devbox-sync.sh
devbox/lib.sh
src/rust/bin/run_in_container.sh
src/sh/BUILD
src/sh/shell_color.sh

This is strictly a readability thing.

Refactor a rudimentary library for shell colors out of rust/run_in_container.sh into its own library + use it in devbox

---

Makefile
nomad/consul-intentions/dgraph-alpha-0-http.json
nomad/e2e-tests.nomad
nomad/grapl-provision.nomad
pulumi/grapl/__main__.py
src/python/Dockerfile

https://github.com/grapl-security/issue-tracker/issues/904
Relates to https://github.com/grapl-security/grapl/pull/1615
Add a step to `grapl-provision` that will RPC to dgraph and tell it to drop all data.
With the addition of persistent volumes, we need to handle this case somehow.
Currently, it will -always- do that, but it's hooked up to an env{} flag for easy orchestration down the line.
I will try to play with these changes on top of the dgraph PR and see how it behaves.

Add a step to `grapl-provision` that will nuke dgraph data

---

Makefile
docker-compose.yml
docs/development/integration_tests.rst
etc/ci_scripts/dump_artifacts/cli.py
nomad/grapl-core.nomad
src/python/grapl-tests-common/grapl_tests_common/setup_tests.py

https://github.com/grapl-security/issue-tracker/issues/900
This has Nomad use a Docker volume for storing Dgraph data, allowing it to persist across container resets, which can happen from time to time. This prevents data loss observed during local grapl development. By decoupling Dgraph storage from the execution, I no longer notice when Nomad jobs reset.
Note to reviewers: I'm looking for input on two things:
1. Is there a better way to define these volumes mounts once and refer to them in each task stanza?
2. I'm just piggy-backing off of the auto-label used by the Makefile, which should probably be given a better name (key) and the comments should be updated.
I tested similar changes in my `inickles/dropper` branch.

Store DGraph data in Docker volumes, instead of leaving in container fs.

---

devbox/README.md
devbox/forward_common_ports.sh
devbox/ssh.sh

It's a shortcut for our most commonly consumed ports, 4646, 8500, 1234

Add devbox/forward_common_ports.sh

---

pulumi/grapl/__main__.py

NA
This fixes a bug in the testing pipeline where we try to look up a nonexistent consumer group name in the `ccloud-bootstrap` stack outputs
Automated tests (post merge :sob:)

Fix testing pipeline

---

etc/chromeos/lib/installs.sh

This adds pyton3-dev to apt installs for chromeos setup script.
Without this, running `./build-support/manage_virtualenv.sh populate` was failing with:
```
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/inickles/src/grapl/build-support/venv/include -I/usr/include/python3.9 -c src/python-zstd.c -o build/temp.linux-x86_64-3.9/src/python-zstd.o -O2 -DVERSION=1.5.1.0 -DDYNAMIC_BMI2=0 -DZSTD_MULTITHREAD=1 -Izstd/lib -Izstd/lib/common …
```

Add sudo python3-dev pkg to apt install.

---

nomad/local/nomad_run_local_infra.sh

1. add ctrl-c support with --foreground
2. make it multiline now that i understand how cat eof fully works
3. add a [1/45] attempt counter

Improvements around "waiting for nomad agent..."

---

etc/ci_scripts/dump_artifacts/analysis/BUILD
etc/ci_scripts/dump_artifacts/analysis/pipeline_message_flow.py
etc/ci_scripts/dump_artifacts/analysis/pipeline_message_flow_test.py
etc/ci_scripts/dump_artifacts/cli.py
etc/ci_scripts/dump_artifacts/docker_artifacts.py

Long story short, all dumps to `test_artifacts/{timestamp}` will now contain a 
`analysis/pipeline_message_flow.txt`
```
File sysmon-generator.stdout.dcf2ec63.log: received 2
File osquery-generator.stdout.ad035f8d.log: received 0
File node-identifier.stdout.df01981c.log: received 2
File node-identifier-retry.stdout.01528ef9.log: received 2
File graph-merger.stdout.326e6168.log: received 4
File analyzer-dispatcher.stdout.afb9a66b.log: received 4
File analyzer-executor.stdout.3852f406.log: received 8
File engagement-creator.stdout.5ecec833.log: received 12
```
The idea here is that it'd be bone simple to zero-in on "oh, why does graph-merger receive 0? something must have screwed up at node-identifier-retry" without having to peruse through every service's logs

Add a pipeline_message_flow analysis to dump_artifacts, to easily figure out "why are my e2e tests failing?"

---

nomad/grapl-core.nomad
nomad/integration-tests-new.nomad
nomad/local/integration-tests.nomad
pulumi/grapl/__main__.py
pulumi/infra/kafka.py
pulumi/integration_tests/__main__.py
src/rust/pipeline-ingress/tests/integration_test.rs

NA
This PR updates the infrastructure configurations to account for the changes in https://github.com/grapl-security/confluent-cloud-infrastructure/pull/3.
The upshot of this is now we have Kafka credentials specifically for the integration test consumers, and we use them instead of trying to piggy-back on e.g. the pipeline-ingress credentials.

wire up the new integration test creds

---

src/rust/sysmon-parser/src/error.rs
src/rust/sysmon-parser/src/event.rs
src/rust/sysmon-parser/src/events.rs
src/rust/sysmon-parser/src/lib.rs
src/rust/sysmon-parser/tests/multi_event_line_comments.rs
src/rust/sysmon-parser/tests/parse_events.rs

The sysmon-parser would incorrectly return an error when parsing multiple events is there was an XML comment that included the ending element tag of an event.
This uses a single xmlparser::Tokenizer for processing multiple events from a single input. I hadn't previously noticed `xmlparser::Tokenizer::from_fragment` that allows for this.
I reproduced the issue by first adding new test case to sysmon-parser. I then used that to verify this fix.

Use single tokenizer across all input for Sysmon parser iterator.

---

pulumi/integration_tests/__main__.py

NA
Previously we were trying to look up the `e2e-test-runner` consumer group with the wrong key. Now we use the right one.

use the correct key to lookup the consumer group

---

Makefile
nomad/bin/run_parameterized_job.sh
nomad/lib/nomad_cli_tools.sh

We had this happen in slack today, where 1 e2e test resulted in 2 invokes. We have no idea how or why this happened.
Ideally this logging will at least give us some more info
https://buildkite.com/grapl/grapl-testing/builds/261#b4d7cc4d-5536-479b-94d3-6a5c3080209e/157
```
if you look at artifacts on colin's link
there's actually two e2e runs in there
e2e-tests.events.8c9d0e94.log
and
e2e-tests.events.905b3860.log
i have no idea how that's happening
```

Add debugging around allocation IDs on run_parameterized_job

---

src/rust/sysmon-parser/Cargo.toml
src/rust/sysmon-parser/src/event.rs
src/rust/sysmon-parser/src/event_data.rs
src/rust/sysmon-parser/src/event_data/file_create.rs
src/rust/sysmon-parser/src/event_data/network_connect.rs
src/rust/sysmon-parser/src/event_data/process_creation.rs
src/rust/sysmon-parser/src/event_data/process_terminated.rs
src/rust/sysmon-parser/src/system.rs
src/rust/sysmon-parser/src/system/correlation.rs
src/rust/sysmon-parser/src/system/event_id.rs
src/rust/sysmon-parser/src/system/execution.rs
src/rust/sysmon-parser/src/system/provider.rs
src/rust/sysmon-parser/src/system/security.rs
src/rust/sysmon-parser/src/system/time_created.rs

The sysmon-parser was using a crate renaming hack to work around shortcomings of Cargo features and interactions with optional dependencies. That has been resolved with Rust 1.60 and means we can ditch that hack.
https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features
More details are available in the comment that is now removed with this PR:
```
```
CI tests.

[sysmon-parser] Undo opt dep + crate name hack now that Rust 1.60 has better support

---

src/rust/sysmon-parser/CHANGELOG.md
src/rust/sysmon-parser/README.md
src/rust/sysmon-parser/src/event.rs
src/rust/sysmon-parser/src/event_data.rs
src/rust/sysmon-parser/src/event_data/file_create_stream_hash.rs
src/rust/sysmon-parser/src/lib.rs

NA
This adds parsing of the FileCreateStreamHash events to the sysmon-parser, which is very similar to the FileCreate event. We have some of the events in our sample data.
I grabbed example of one of these events from our sample event data and used that for writing a unit test to parsing (just the EventData section).

Add FileCreateStreamHash event to sysmon-parser.

---

Makefile

For some reason, docker volume ls lets you filter by name, but docker volume prune does not.
I'm changing this to a two-step phase:
1. docker volume ls with the folder
2. run the results through docker volume rm
```
docker volume ls --filter name=grapl-data
DRIVER    VOLUME NAME
local     grapl-data-dgraph
local     grapl-e2e_tests_grapl-data-dgraph
local     grapl-integration_tests_grapl-data-dgraph
local     grapl_grapl-data-dgraph
docker volume prune --filter name=grapl-data
WARNING! This will remove all local volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Error response from daemon: Invalid filter 'name'
```

Fix 'make clean-docker-data-volumes'

---

firecracker/rootfs/scripts/install_dependencies.sh
src/rust/plugin-registry/src/nomad/client.rs
src/rust/plugin-registry/src/static_files/hax_docker_plugin.nomad
src/rust/plugin-registry/tests/BUILD
src/rust/plugin-registry/tests/small_test_binary.sh
src/rust/plugin-registry/tests/test_deploy_plugin.rs

`test_deploy_plugin` will now deploy a plugin that just runs `python3 -m http.server`; this will in the _very_ near future be replaced with a grpc server implementing the plugin sdk, but in the meantime, this really helps me validate that the proxy stuff is working correctly.
---
To use it:
KEEP_TEST_ENV=1 make test-integration-new
PLUGIN_SERVICE="plugin-5fe1d97a-3d86-6e04-0193-8b121dba1a26"
consul connect proxy -service respresenting-devbox-1 -upstream ${PLUGIN_SERVICE}:9999
```
$ curl http://localhost:9999
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Directory listing for /</title>
...
```

Proof-of-concept http (not grpc) grapl plugin to experiment with consul proxy stuff

---

.buildkite/scripts/build_and_upload_images.sh
.buildkite/scripts/lib/retry.sh

Further digging into the issue originally raised in https://github.com/grapl-security/grapl/pull/1679
we are experimenting with retries and de-parallelizing our docker uploads to cloudsmith

Un-parallelize our docker push to Cloudsmith, and add some retries

---

nomad/local/nomad_run_local_infra.sh
nomad/local/start_detach.sh

So I saw the following in one of Thomas's PRs:
https://buildkite.com/grapl/grapl-verify/builds/3365#55569814-1b58-4d26-99f3-05078faf1cb7
```
nomad/local/start_detach.sh
--
  | Starting nomad and consul locally. Logs @ /tmp/nomad-agent.log and /tmp/consul-agent.log.
  | Deploying Nomad local infrastructure
  | ==> Error loading configuration from nomad/local/nomad-agent-conf.nomad: Error loading nomad/local/nomad-agent-conf.nomad: unexpected keys ui
  | Waiting for nomad-agent [1/45]
  | Waiting for nomad-agent [2/45]
  | Waiting for nomad-agent [3/45]
  | Waiting for nomad-agent [4/45]
  | Waiting for nomad-agent [5/45]
```
Now, obviously, we should bail if the nomad pid ever exits, right?
ALSO, I decided the "wait for the nomad agents to be healthy" logic should be in start_detach, not …

start_detach: Capture cases where nomad agent or consul agent fail

---

.gitignore
Makefile
docker-bake.hcl
localstack/Dockerfile
src/python/Dockerfile
src/rust/Dockerfile
src/rust/build-env.Dockerfile

Currently we are shoving `engagement-view` artifacts in `src/rust` when we don't really need to.
Right now we have the following:
```.PHONY: build-engagement-view
build-engagement-view: ## Build website assets to include in grapl-web-ui
[...] 
This cache-busts the Rust build `FROM rust:1-slim-bullseye AS base` because of
`COPY rust rust`
That `frontend/` artifact is not _actually_ used in `rust-base` build at all; it's only used in
```##### web-ui
FROM rust-dist AS grapl-web-ui-deploy
COPY --from=build /outputs/grapl-web-ui /
COPY rust/grapl-web-ui/frontend /frontend
ENTRYPOINT ["/grapl-web-ui"]```
*SOLUTION*
We shove `/frontend` into `dist/` 
We use `dist/` as a named secondary context

Refactor frontend artifacts so they're dumped to dist/ not src/rust/grapl-web-ui

---

.buildkite/pipeline.merge.yml

This uses the commit of the merged
https://github.com/grapl-security/grapl-rc-buildkite-plugin/pull/27
PR.
Provided this behaves as we expect (i.e., removes all the files on the
`rc` branch that we've deleted from the `main` branch), we'll cut a
formal release of that plugin and use _that_, rather than a raw commit
SHA.

Test out new `grapl-rc` plugin

---

devbox/devbox-sync.sh
src/sh/shell_color.sh

none
add a VERBOSE_DEVBOX_SYNC=1 option which shows you which files are being synced (and which are being deleted, which is a thing that happens)
add a warning if <5GB remains on devbox
I bumped the limit to 20GB and got

devbox-sync: add a VERBOSE_DEVBOX_SYNC=1 option; add a warning if <5GB remains on devbox

---

.buildkite/pipeline.merge.yml

This is the same as we were using previously, but pinned to a tag
rather than a raw commit SHA.

Update `grapl-rc` plugin to `v0.1.7`

---

Makefile

Found the commit where the rule was removed by doing
```
git log -c -S'lint-proto-format:' Makefile
```
result: b5194b479b2ef4dc785393df27b538709817b193
https://github.com/grapl-security/grapl/pull/1682

Remove a leftover 'lint-proto-format' dependency; that rule was removed

---

.buildkite/pipeline.merge.yml
.buildkite/scripts/build_and_upload_images.sh

https://github.com/grapl-security/issue-tracker/issues/931
Previously: Buildx --push
Then, a [workaround](https://github.com/grapl-security/grapl/pull/1681): manually push each image
Now: Upon first attempt, do PReviously behavior; on Buildkite retries, do workaround behavior
i'm testing on my devbox as we speak

Revert MANIFEST_UNKNOWN workaround

---

Makefile
docker-bake.hcl
src/rust/Dockerfile

So, we actually _already had this functionality_ for plugin-bootstrap-init, but I wanted to genericize the approach. 
I realized we'd need this because I'll soon be shuttling a Generator plugin binary out into `dist/`.
There's no real reason to separate this into separate images (i.e. one for the generator binary, one for the plugin-bootstrap-init binary).
- All of the binaries are built together all at once
- Nothing directly consumes the image, it's just an implementation detail of pulling stuff out into dist/

'shuttle-rust-to-dist': a way to pull binary artifacts out of `rust-build` into `dist/`.

---

etc/chromeos/lib/installs.sh
etc/chromeos/setup_chromeos.sh

This simplifies our setup script by offloading the upstream repository
configuration to our proxy.

Use Cloudsmith Apt repo proxy to install workstation tooling

---

devbox/devbox-sync-back.sh

My laptop's `format-prettier` stopped working, so I cooked up a script that will let me:
- format-prettier on my devbox
- rsync a specified set of files back from my devbox to my host OS
the rsync command is heavily based on / shared with the one in devbox-sync.sh but there's enough disparity to separate them.

devbox-sync-back: claw back specified files from devbox

---

src/rust/plugin-registry/tests/test_deploy_plugin.rs

Relates to https://github.com/grapl-security/issue-tracker/issues/937
Read the PR, it's pretty self-documenting

Disable 'test_deploy_plugin', I may need to make the gRPC bidi change ASAP

---

src/rust/Cargo.lock
src/rust/grapl-graphql-codegen/Cargo.toml
src/rust/grapl-graphql-codegen/src/main.rs
src/rust/organization-management/Cargo.toml
src/rust/organization-management/src/lib.rs
src/rust/organization-management/src/main.rs
src/rust/organization-management/tests/test_create_organization.rs
src/rust/organization-management/tests/test_create_user.rs
src/rust/plugin-bootstrap/Cargo.toml
src/rust/plugin-bootstrap/src/lib.rs
src/rust/plugin-bootstrap/src/plugin_bootstrap_service.rs
src/rust/plugin-registry/Cargo.toml
src/rust/plugin-registry/src/main.rs
src/rust/plugin-registry/src/nomad/client.rs
src/rust/plugin-registry/src/server/service.rs
src/rust/plugin-sdk/generator-sdk/src/server.rs
src/rust/plugin-work-queue/Cargo.toml
src/rust/plugin-work-queue/src/lib.rs
src/rust/plugin-work-queue/src/main.rs

https://github.com/grapl-security/issue-tracker/issues/868
Change from structopt to clapv3. Structopt is in maintenance mode and suggests people use this instead.
One major note: adding `long` along with `env` tells clap to stop doing some unnecessary-for-us command line specific validation, which we just don't care about. 
Including `long` is not necessary in much of our code, _but_ is a pattern I want to cargo-cult to future consumers (think of it as a good habit).
CI

Change all usage of structopt to clapv3

---

nomad/grapl-core.nomad
src/rust/plugin-registry/src/static_files/hax_docker_plugin.nomad

Namely, the services that we've ported to the repeatable pattern established in rust-proto-new.

Add gRPC health checks to a few of our services.

---

.buildkite/scripts/build_and_upload_images.sh

To determine if Cloudsmith has addressed the underlying promotion bug,
we'll remove our workaround from the first time we run this "build and
upload images" job. This is not perfect, as we can't really know
whether the fix works from within this job, but it preserves the
workaround logic for now.
Tip for reviewers: view this PR with whitespace changes suppressed.
Fixes https://github.com/grapl-security/issue-tracker/issues/932

Conditionally remove workaround for Cloudsmith promotion bug

---

scylladb/Dockerfile
src/js/graphql_endpoint/Dockerfile
src/rust/Dockerfile
src/rust/build-env.Dockerfile

`1.1.1n-0+deb11u1`, which we were using, is no longer available.

Update `libssl-dev` to version `1.1.1n-0+deb11u2`

---

.buildkite/pipeline.provision.yml

Update grapl-security/pulumi Buildkite plugin version to v0.1.4
This picks up the ability to specify a local policy pack for Pulumi runs.
---

Update `pulumi` Buildkite plugin to `v0.1.4`

---

src/rust/plugin-registry/src/error.rs

error(transparent) is great for pass-through error types.
Issue raised in https://grapl-internal.slack.com/archives/C02J5JYS92S/p1652891301728649 where, in prod, S3 puts in create_plugin aren't working. We can't debug why.

Make a bunch of plugin registry error types transparent

---

nomad/grapl-core.nomad
pulumi/grapl/__main__.py
src/rust/plugin-registry/src/server/deploy_plugin.rs
src/rust/plugin-registry/src/server/service.rs

> [4:06](https://grapl-internal.slack.com/archives/C017F10727P/p1652904407194439)
```
plugins_bucket = Bucket("plugins-bucket", sse=True)
pulumi.export("plugins-bucket", plugins_bucket.bucket)
plugin_buckets = [
analyzers_bucket,
model_plugins_bucket,
]
the variable plugins_bucket is not in plugin_buckets
```
> [cm] [4:07 PM](https://grapl-internal.slack.com/archives/C017F10727P/p1652904470386639)
> That's a thorny bit of code from a naming perspective... plugins_bucket, model_plugins_bucket, plugin_buckets

Add correct perms to plugin_registry bucket; clean up naming around it in Pulumi, Nomad, rust

---

Makefile
etc/ci_scripts/dump_artifacts/analysis/pipeline_message_flow.py

1. test-with-env printed out a bunch of useless commands; `.SILENT` quiets them.
2. `dump_artifacts` would print out a stack trace when grapl-core/ didn't exist for analysis, gross!

Make 'make test-with-env' not print out a bunch of useless commands; make 'dump_artifacts' fail gracefully

---

nomad/local/start_detach.sh

[wimax](https://app.slack.com/team/U0175EMAA5U)  [2:07 PM](https://grapl-internal.slack.com/archives/C02JCBKS97V/p1653070056555209)
I'm seeing CI having trouble with nomad_local_infrastructure. Not 100% sure why, but I just found the following in the logs:
```
2022-05-20T15:44:20Z: Task Group "plugin-work-queue-db" (failed to place 1 allocation):
* Constraint "${attr.consul.version} semver >= 1.7.0": 1 nodes excluded by filter
2022-05-20T15:44:20Z: Task Group "organization-management-db" (failed to place 1 allocation):
* Constraint "${attr.consul.version} semver >= 1.7.0": 1 nodes excluded by filter
etc etc
```
[wimax](https://app.slack.com/team/U0175EMAA5U)  [2:45 PM](https://grapl-internal.slack.com/archives/C02JCBKS97V/p1653072305270219)
i can repro locally after updating to nomad …

Ensure Consul agent is up before Nomad starts

---

pulumi/grapl/__main__.py
pulumi/infra/firecracker_assets.py

Per Jesse:
> [can confirm commenting out all that firecracker_assets stuff speeds up the build considerably
](https://grapl-internal.slack.com/archives/C02JCBKS97V/p1653083673716289
)
Since Firecracker is currently on the backburner, let's temporarily feature gate this stuff away.
Relates to https://github.com/grapl-security/issue-tracker/issues/908
Once we switch back to Firecracker we need to remove this feature gate.
Hide a big S3 upload behind an `if false` basically
CI

Stop uploading Firecracker assets in Pulumi, because it seems to slow down localstack/pulumi a lot?

---

docker-bake.hcl

Now that `buildx` 0.8.0 has been released, we can safely create
multiple layers of inheritance for the configuration of our image
builds. At the moment, this means placing all our standard image
labels on a `_grapl-base` target that all other targets inherit from,
rather than "manually" attaching the labels to each target
individually.
(Note that any targets can add additional labels they want, and these
will be properly propagated to any child targets.)

Create a `_grapl-base` target for all images to inherit from

---

etc/chromeos/lib/installs.sh

See https://github.com/hashicorp/nomad/releases/tag/v1.3.1

Update Nomad to 1.3.1 to address a CVE

---

src/python/e2e-test-runner/e2e_test_runner/test_consul_dns.py

https://github.com/grapl-security/issue-tracker/issues/944
Skip the consul dns test.
There's a fix for this behavior in an upcoming Nomad release, but this
is currently causing e2e tests to fail in AWS. Since this is coming
soon, we should skip the test for now

Skip consul dns test

---

etc/chromeos/lib/installs.sh

This just removes a redundant version setting, now that we have a
`.python-version` file that does the same thing.

Drive Python installation from `.python-version` file

---

docs/build_docs.sh

[wimax](https://app.slack.com/team/U0175EMAA5U)  [11:09 AM](https://grapl-internal.slack.com/archives/C02JCBKS97V/p1653750582427179)
Somewhere along the line, grapl/verify has stopped working for the very-very-legacy Makefile target make build-docs. It doesn't use pants or pyenv or anything, just a python3 -m venv to manage its requirements. This is due to how RtD works, it executes pre-defined commands.
https://docs.readthedocs.io/en/stable/builds.html
https://buildkite.com/grapl/grapl-verify/builds/3627#01810b0d-323a-4b2b-a7f2-dbfc018b73ae

Fix ReadTheDocs builds by using Pants-driven virtualenv instead of a homespun one

---

devbox/provision/deprovision.sh
devbox/provision/provision.sh
etc/chromeos/lib/installs.sh

none
1. Provisioning, then deprovisioning, then provisioning would fail because we'd preserve the previous SSH key. That's fixed.
2. We had a "downgrade" in our Vault versions (by adding a x.y.z-hyphenated version) to some of our Hashicorp products. Updated the script to allow for this edge case with an --allow-downgrades.
3. Harden the provisioning step where there's an SSH invoke afterwards

An assortment of small fixes around Devbox and chromeos/setup.sh

---

Makefile
docker-bake.hcl
src/rust/Cargo.toml
src/rust/Dockerfile

Introduced a new Cargo build profile, `dev-local-grapl`, that's basically the same as debug but without debuginfo.
- Symbols are still there.
- But you basically can't use `gdb` on it.
You can get debuginfo back by running with RUST_BUILD=debug.

Strip debuginfo in default local-grapl rust builds.

---

Makefile

Not all our Makefile targets were using our `DOCKER_BUILDX_BAKE_HCL` macro; now they do.
Additionally, since according to https://github.com/docker/buildx/issues/936 we don't actually need to specify our `docker-bake.hcl` file explicitly, we rename the macro to simply `DOCKER_BUILDX_BAKE`.

Ensure consistent use of `DOCKER_BUILDX_BAKE` Make macro

---

nomad/grapl-core.nomad
nomad/local/grapl-local-infra.nomad
nomad/local/integration-tests.nomad
pulumi/grapl/__main__.py
pulumi/infra/local/postgres.py
pulumi/infra/nomad_job.py
pulumi/infra/nomad_service_postgres.py
pulumi/infra/postgres.py
pulumi/integration_tests/__main__.py

Where once we had 4 Nomad vars per database, now we have 1.
That also means we can `pulumi.export` just 1 thing.

Simplify postgres database stuff by passing it around Pulumi/Nomad as a structured Object

---

nomad/grapl-core.nomad
pulumi/grapl/__main__.py
pulumi/infra/kafka.py
pulumi/infra/nomad_job.py

none
Drastically reduces the number of variables passed into Nomad having to do with Kafka from
num kafka services * 3 (username, password, consumer_group_name)
to
2.
Centralizes where they are made, making it very simple to add new services that consume Kafka. 
make test-integration-new

Centralize Kafka credential and consumer-groups creation/access in Pulumi<->Nomad.

---

scylladb/Dockerfile
src/js/graphql_endpoint/Dockerfile
src/rust/Dockerfile
src/rust/build-env.Dockerfile

`1.1.1n-0+deb11u2` is no longer available.

Update `libssl-dev` to `1.1.1n-0+deb11u3`

---

.buildkite/pipeline.provision.yml

NA
This PR fixes the provision pipeline to point to the new `rust_integration_tests` folder instead of the previous (and now nonexistent) `integration_tests` folder.
Automated tests (post-merge).

use rust_integration_tests in the provision pipeline

---

nomad/grapl-core.nomad
nomad/grapl-provision.nomad
pulumi/grapl/__main__.py
pulumi/infra/observability_env_vars.py
src/rust/grapl-tracing/src/setup_tracing.rs
src/rust/plugin-registry/src/server/deploy_plugin.rs
src/rust/plugin-registry/src/server/service.rs
src/rust/plugin-registry/src/static_files/hax_docker_plugin.nomad

none, followup to https://github.com/grapl-security/grapl/pull/1817
We were seeing in CI that grapl-core failed to deploy due to 
> OpenTelemetry trace error occurred. Exporter jaeger encountered the following error(s): thrift agent failed with not open
This gates the rust opentelemetry stuff behind "does the OTEL_EXPORTER_JAEGER_AGENT_HOST env var exist?"
I then standardized how we feed in the otel jaeger/zipkin stuff into services. It'll populate those env vars in local but not in prod, just like aws_env_vars_for_local. 
I overrode `observability_env_vars_for_local` locally so it'd look like prod; stuff started up!

Remove opentelemetry during prod, in Rust

---

src/rust/Dockerfile

```
[wimax]()
[11:35 AM]()
Has anybody found a way to get either docker buildx or cargo to spit out more information when you encounter the following during a make build-test-integration?
#34 43.33 error: could not compile `generator-dispatcher` due to 3 previous errors
progress=plain doesn't do it; I'm hoping a make docker-clean-all + progress=plain will
[11:36](https://grapl-internal.slack.com/archives/C0174A8QV2S/p1658504161441869)
¯\_(ツ)_/¯
[wimax]()
[11:50 AM]()
actually, i may have an idea
```

Rust dockerfile will expose error messages at integration test time

---

nomad/local/grapl-local-infra.nomad

While doing some unrelated version bumps elsewhere, I discovered that
a new release of Localstack had been made, allowing us to pin to a
specific tag, rather than a SHA256 checksum.

Update Localstack to `localstack-light:1.0.1`

---

src/rust/generator-dispatcher/Cargo.toml
src/rust/generator-dispatcher/tests/generator_dispatcher_integration_tests.rs
src/rust/plugin-work-queue/Cargo.toml
src/rust/plugin-work-queue/src/lib.rs
src/rust/plugin-work-queue/src/psql_queue.rs
src/rust/plugin-work-queue/src/test_utils.rs

Also, change the feature to "test-utils"; Depending on another package's "integration_tests" was an antipattern that was causing code to unexpectedly run.

Move 'scan_for_plugin_message_in_pwq()` to PluginWorkQueue's test-utils

---

src/rust/Cargo.lock
src/rust/grapl-web-ui/Cargo.toml
src/rust/grapl-web-ui/src/config.rs
src/rust/grapl-web-ui/src/graphql.rs
src/rust/grapl-web-ui/src/lib.rs
src/rust/grapl-web-ui/src/main.rs
src/rust/grapl-web-ui/src/routes/api/graphql.rs
src/rust/grapl-web-ui/tests/api/config.rs

This migrates to using clap for env var argument processing for both the main app and the integration tests, which makes for less code here and makes it more consistent with other grapl packages.
The Rust integration tests should cover these changes.

[grapl-web-ui] Migrate to clap for argument processing.

---

Dockerfile.pulumi
scylladb/Dockerfile
src/python/Dockerfile
src/rust/Dockerfile
src/rust/build-env.Dockerfile

seeing this on firecracker_rootfs
#0 1.457 The following packages have unmet dependencies:
#0 1.503  curl : Depends: libcurl4 (= 7.74.0-1.3+deb11u1) but 7.74.0-1.3+deb11u2 is to be installed
just updating it everywhere i see deb11u1

Upgrade to a different curl

---

src/rust/grapl-config/src/lib.rs

While working on https://github.com/grapl-security/grapl/pull/1855 I noticed a number of exports in grapl-config that are no longer used and probably won't/shouldn't be used.
Rust integration tests.

Remove unused exports in grapl-config

---

nomad/grapl-core.nomad
nomad/rust-integration-tests.nomad
src/rust/Cargo.lock
src/rust/event-source/Cargo.toml
src/rust/event-source/src/config.rs
src/rust/event-source/src/db.rs
src/rust/event-source/src/db/client.rs
src/rust/event-source/src/error.rs
src/rust/event-source/src/main.rs
src/rust/event-source/src/server.rs
src/rust/generator-dispatcher/Cargo.toml
src/rust/generator-dispatcher/tests/test_utils/context.rs
src/rust/grapl-config/Cargo.toml
src/rust/grapl-config/src/lib.rs
src/rust/grapl-config/src/postgres.rs
src/rust/organization-management/Cargo.toml
src/rust/organization-management/src/lib.rs
src/rust/organization-management/src/server.rs
src/rust/organization-management/tests/test_create_organization.rs
src/rust/organization-management/tests/test_create_user.rs
src/rust/plugin-registry/src/db/client.rs
src/rust/plugin-registry/src/server/service.rs
src/rust/plugin-work-queue/Cargo.toml
src/rust/plugin-work-queue/src/lib.rs
src/rust/plugin-work-queue/src/psql_queue.rs
src/rust/plugin-work-queue/src/server.rs

This relates to https://github.com/grapl-security/issue-tracker/issues/990 and is a follow up to https://github.com/grapl-security/grapl/pull/1848.
This has all services using Postgres use a secrets type for safer handling of Postgres credentials.
Additionally, this provides a Postgres client trait that intends to reduce boilerplate with some default implementations. A trait is used in-part so users can override the default functionality.
This also introduces a trait, `ToPostgresUrl`, to be used with Postgres service configs. The need for this trait is somewhat unfortunate, and we can probably move away from it and allow all services to use a common Postgres config type if/when clap::Praser derive macro supports supplied prefixes when `flatten`ing configs. The following code comment in …

Postgres client abstraction that safely handles credentials, removes boilerplate

---

pulumi/infra/observability_env_vars.py

This was lost in the running during my merging of colin's stuff. I've chosen a nice 'less than 1/10th butr a 2^n" number for starters and will look at logs to see how it works out

otel_bsp_max_export_batch_size

---

firecracker/rootfs/build-rootfs.pkr.hcl
firecracker/rootfs/scripts/create_rootfs_image.sh

The `debootstrap` in this image is unfortunately pretty flaky when downloading.
Example:
https://buildkite.com/grapl/grapl-verify/builds/4004#01825af7-73b1-4c0a-b4da-d30a54c0c90d
Common failure scenarios that are totally retriable:
```
  | amazon-ebs.grapl-build-rootfs: I: Validating liblzma5 5.2.5-2.1~deb11u1
  | amazon-ebs.grapl-build-rootfs: I: Retrieving zlib1g 1:1.2.11.dfsg-2+deb11u1
  | amazon-ebs.grapl-build-rootfs: I: Validating zlib1g 1:1.2.11.dfsg-2+deb11u1
  | amazon-ebs.grapl-build-rootfs: E: Couldn't download packages: apt
  | ==> amazon-ebs.grapl-build-rootfs: Provisioning step had errors: Running the cleanup provisioner, if present...
```
```
  | amazon-ebs.grapl-build-rootfs: I: Retrieving liblzma5 5.2.5-2.1~deb11u1
  | amazon-ebs.grapl-build-rootfs: I: Validating liblzma5 …
```

Make build-rootfs packer do retries for debootstrap

---

.github/CODEOWNERS
postgres/Dockerfile
postgres/postgres.conf

We've been getting Postgres signal 9s that may be internal OOMKillers. What if we tune it so we don't get OOM?
I found a guide - https://www.enterprisedb.com/postgres-tutorials/how-tune-postgresql-memory - and basically followed their suggestions.

Potentially defend against postgres OOMkiller

---

Makefile
etc/ci_scripts/dump_artifacts/cli.py
etc/ci_scripts/dump_artifacts/nomad_artifacts.py

This optionally allows consul connect logs to show up in test-artifacts. It's far too noisy for day-to-day use (roughly doubling the number of things that show up in test_artifacts/), but I may need to use this to debug something in https://github.com/grapl-security/grapl/pull/1872

Option to dump Nomad Consul Connect Proxy logs

---

src/rust/Cargo.toml

This doesn't work as intended, removing.

Revert "Remove ANSI codes in rust logs (#1874)"

---

pulumi/python_integration_tests/__main__.py
pulumi/rust_integration_tests/__main__.py

The bucket was removed, but the references remained.

Remove `sysmon-log-bucket` references in integration tests

---

nomad/grapl-core.nomad
pulumi/grapl/__main__.py
src/rust/plugin-registry/src/server/deploy_plugin.rs
src/rust/plugin-registry/src/server/service.rs
src/rust/plugin-registry/src/static_files/hax_docker_plugin.nomad
src/rust/plugin-registry/src/static_files/plugin.nomad

Previously the generator image was hardcoded; now we'll switch it around based on if the plugin type is Analyzer or Generator.

Use different images for analyzer and generator sidecars. (analyzer exec sidecar not done yet!)

---

etc/ci_scripts/dump_artifacts/cli.py

Now, along with each file separately, each CI run will generate an ALL_ARTIFACTS.zip file

Dump a zip file of all artifacts

---

pulumi/grapl/__main__.py
pulumi/infra/kafka.py

The `grapl/ccloud-bootstrap/ccloud-bootstrap` stack has been renamed
to `grapl/confluent-cloud/production`, for more consistency with our
other Pulumi stacks.

Update references to Confluent Cloud Pulumi stack

---

.buildkite/pipeline.provision.yml

We're running into errors doing a refresh because we're trying to pull
in information from the now-renamed
`grapl/ccloud-bootstrap/ccloud-bootstrap` stack.
We can re-enable this after we successfully get a Pulumi update through.

Temporarily disable Pulumi refreshes in provision pipeline

---

.buildkite/pipeline.provision.yml

This reverts commit 41f70132d36823016d54e99fe0b957eaed9def31.
See #1897.

Revert "Temporarily disable Pulumi refreshes in provision pipeline"

---

.buildkite/scripts/build_and_upload_images.sh

The logic for determining which images are actually new was behind a
retry gate (it would only run if the step was being retried in
Buildkite due to a failure). This unnecessarily coupled it to our
workaround for the fact that `docker buildx bake --push` seems to
sometimes cause issues for Cloudsmith, at least when many images are
being pushed at a time.
Our "is it new?" logic actually should **always** run. The bug that
caused us to add it in the first place appears to have been fixed, but
beyond that, the workaround is actually **better** for us, because it
means that we'll only end up updating running services when they
actually need to change, rather than every single time somebody merges
new code. The proper time to remove this logic is when we can a priori
determine which Rust-based …

Clarify workarounds in image build and upload logic

---

src/rust/Dockerfile

For the Rust integration tests, redirect std err to std out.
The Rust integration tests would previously capture stderr and stdout to two separate files. If multiple tests wrote to their stderr, it might not be immediately obvious what the error text corresponds to. The benefit of keeping these separate is less convenient than keeping them together, where the value of keeping them separate is unclear.
Additionally, this add a verbose flag to `parallel`, which prints the job command line to stdout for each job. This should help in debugging and help clarify the boundaries between jobs.
Ex"
```
/tests/schema_manager_integration_test-1e7cf03e1eca45e3 2>&1
running 1 test
test test_deploy_schema ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in …
```

Rust integration tests: redirect stderr to stdout.

---

nomad/local/grapl-local-infra.nomad

I removed the 1024 from PWQ's db by accident last time:
https://github.com/grapl-security/grapl/pull/1930
it should have 1024, not plugin-registry.

Give plugin-work-queue db 1024 memory

---

nomad/grapl-core.nomad
nomad/local/grapl-local-infra.nomad
src/rust/plugin-registry/src/static_files/hax_docker_plugin.nomad

NA
This PR reduces the placement requirements for (almost) every nomad task to 50 CPU shares. This ensures we don't run into placement constraint violations when running everything locally. Additionally, I changed all current usages of `memory` in the `resources` stanzas to `memory_max` because the latter is what was actually intended.
Automated integration tests.

set CPU to 50 shares

---

src/rust/plugin-execution-sidecar/src/plugin_executor.rs
src/rust/plugin-execution-sidecar/src/work/plugin_work_processor.rs
src/rust/plugin-work-queue/tests/pwq_integration_test.rs

https://github.com/grapl-security/issue-tracker/issues/1007
I misunderstood how we're using PWQ. 
Acknowledging a generator message as failed (with an empty graph) means this message is permanently dead and never recoverable.
Never acknowledging means the message will become visible again in 10 seconds.
I added an integration test to PWQ to test the visibility stuff. I haven't really changed how we test the PWQ->Execution Sidecar->PWQ border; that _is_ testable but that's not done as part of this PR. I'm happy to go down that rabbithole if people want!

Fix PWQ by not ack'ing retriable errors

---

Makefile

The plural versions of the target (e.g., `python_sources`, rather than `python_source`) are actually _generators_; the individual files themselves are the singular version of the target.
This ensures that we are operating on the proper resources.

Fix Pants filter targets

---

src/rust/plugin-execution-sidecar/analyzer-execution-sidecar.rs
src/rust/plugin-execution-sidecar/src/work.rs
src/rust/plugin-execution-sidecar/src/work/analyzer_work_processor.rs
src/rust/plugin-execution-sidecar/src/work/plugin_work_processor.rs

Resurrects PR https://github.com/grapl-security/grapl/pull/1980
https://app.zenhub.com/workspaces/grapl-6036cbd36bacff000ef314f2/issues/grapl-security/issue-tracker/1013
https://github.com/grapl-security/issue-tracker/issues/1013
This PR adds an analyzer execution sidecar (more or less like the generator execution sidecar)
This isn't super well exercised, however I (as in wimax, not jesse) do exercise it in my grapl-analyzerlib PR: https://github.com/grapl-security/grapl/pull/1969/files

Internal 1013: add Analyzer Executor Sidecar

---

build-support/BUILD
etc/ci_scripts/dump_artifacts/BUILD
pants.toml

Pants can `run` Python sources directly now, without a `pex_binary` intermediate. This is preferred for internal tooling which doesn't need to be packaged and distributed.

Remove (some) `pex_binary` Pants targets

---

src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/event-source/Cargo.toml
src/rust/graph-schema-manager/Cargo.toml
src/rust/grapl-config/Cargo.toml
src/rust/organization-management/Cargo.toml
src/rust/plugin-registry/Cargo.toml
src/rust/plugin-work-queue/Cargo.toml
src/rust/uid-allocator/Cargo.toml

Just centralize where we defined sqlx. Updated the cargo.lock for it

Make sqlx a workspace dependency, and upgrade to 0.6.2

---

nomad/local/grapl-local-infra.nomad
src/rust/plugin-work-queue/migrations/1640037910_plugin_work_queue_migration.sql

None
We were seeing some serious issues with the plugin work queue running locally (it'd OOM), and we can't quite figure out why. Based on the `explain` there appeared to be a serious number of partitions utilized by the `get_generator_messages` (and analyzer) query in psql_queue.rs. 
This is an experiment: to see if we get better behavior by removing the partitioning.
CI

Remove partitioning from plugin work queue

---

src/sh/log.sh

If you have `-euo pipefail` set while calling this function, but do not specify EXIT_CODE, it fails.
`-v` checks if such a variable exists. 
Yes, the syntax is, in fact, correct! No quotes, no $

Fix a minor shell bug in log.sh

---

pulumi/infra/kafka.py

We are transitioning to using the new official Confluent Cloud Pulumi provider, rather than our home-grown dynamic-resource-based TypeScript project.
This begins to pull configuration from the new project. Once we're successfully pulling the configuration from there, we'll rename the project to `confluent-cloud` (`confluent-cloud-py` is just to differentiate from the old project while both exist).

Pull Kafka configuration from new Python project

---

pulumi/infra/kafka.py

These data aren't actually used. I removed them from the output of the upstream stack, but forgot to remove them from this import code.

Remove topics from Kafka bootstrap ingestion

---

pulumi/infra/grapl_stack.py
pulumi/python_integration_tests/__main__.py
pulumi/rust_integration_tests/__main__.py

Essentially the same code was being used for both the Python and Rust integration tests. Rather than duplicating things, we can now just use a canonical implementation, ensuring access to anything from the underlying `StackReference` that is needed.

Extract `GraplStack` to a shared class

---

Makefile

I noticed that we were reading our `.python-version` file directly, rather than using the `python_version.sh` script that we use elsewhere. Even though the results will be the same, it's good to use the same code everywhere.

Use our `python_version.sh` script everywhere

---

pulumi/infra/kafka.py

We're ready to delete the old project and rename the new one.

Rename `confluent-cloud-py` to `confluent-cloud`

---

src/rust/Cargo.lock
src/rust/graph-mutation/Cargo.toml
src/rust/graph-mutation/src/reverse_edge_resolver.rs
src/rust/graph-mutation/src/write_dropper.rs

Satisfies the last bits of https://github.com/grapl-security/issue-tracker/issues/1028 
Switch ReverseEdgeResolver from a DashMap<key, a full Response> to a moka Cache<key, edge name>
this is exercised in integration tests currently, whenever we create an edge

Remove the last traces of dashmap from graph-mutation

---

pulumi/grapl/__main__.py

These timeouts were a legacy thing from when we had Dgraph in our `grapl-core`. in prod. We no longer do, and as such, no longer need the custom timeouts.
If a job takes 5 minutes to deploy (the default).... that's probably an issue. 
As of a recent pulumi update it started pushing warnings about this, like:
```
python-integration-tests-pulumi-1  \| Diagnostics:
--
  | python-integration-tests-pulumi-1  \|   grapl:NomadJob (grapl-core):
  | python-integration-tests-pulumi-1  \|     warning: The option 'customTimeouts' has no effect on component resources.
  | python-integration-tests-pulumi-1  \|
  | python-integration-tests-pulumi-1  \|   pulumi:pulumi:Stack (grapl-local-grapl):
  | python-integration-tests-pulumi-1  \|     error: update failed
  | python-integration-tests-pulumi-1  \|
  …
```

Remove CustomTimeouts for our nomad jobs in pulumi

---

nomad/grapl-core.nomad
src/rust/plugin-registry/src/server/deploy_plugin.rs
src/rust/plugin-registry/src/server/service.rs
src/rust/plugin-registry/src/static_files/hax_docker_analyzer.nomad
src/rust/plugin-registry/src/static_files/hax_docker_generator.nomad

After this discussion in Slack:
https://gist.github.com/wimax-grapl/7f2565e1f6d988a19dde3fc617f515bb
https://grapl-internal.slack.com/archives/C03JNJ57A9G/p1666020843029249
We decided to remove all metrics from the plugin runtime and, instead, to do metrics from their upstream (plugin-work-queue).

Remove OTEL from plugins

---

etc/ci_scripts/dump_artifacts/nomad_artifacts.py

Our pipelines started suddenly failing when our "dump artifacts" code started dying when fetching Nomad logs. Apparently some allocations for the `rust-integration-tests` job were "lost", and you can't fetch logs for things that are lost.
I've tried to prune these jobs from Nomad, but haven't found the right incantation yet. In the meantime, we can just not try to fetch those logs.
This is not the "real" solution, but should at least allow our pipeline to continue while we sort out what's going on.

Don't try to gather "lost" Nomad allocations

---

.buildkite/pipeline.provision.yml
.buildkite/pipeline.testing.yml
.buildkite/scripts/grapl_testing_stack/dump_artifacts.sh

The `dump-artifacts` command we use invokes Pants, so we can likely
cut down the time that this action takes by using the cache.
(The wrapper script was also simplified.)

Make use of the Toolchain remote cache when gathering artifacts

---

src/rust/Cargo.lock
src/rust/graph-mutation/Cargo.toml
src/rust/graph-mutation/src/graph_mutation.rs
src/rust/graph-query/Cargo.toml
src/rust/graph-query/src/property_query.rs
src/rust/scylla-provisioner/Cargo.toml
src/rust/scylla-provisioner/src/server.rs
src/rust/scylla-provisioner/src/table_names.rs

https://app.zenhub.com/workspaces/grapl-6036cbd36bacff000ef314f2/issues/grapl-security/issue-tracker/1031
Provisioning keyspaces and tables in parallel is slow and error prone. This changes things so that we provision things once and instead our tenancy isolation is done via partition keys, not keyspaces.
This PR also updates Scylla to 0.6, which includes a number of bug fixes, including changes around the reliability of ALTER commands.
Note that the tenant-id no longer needs to be communicated to the service but this PR does not remove it. There will be follow up issues to track this work.
Further, we attempt to only provision once by storing a boolean value and short circuiting if a provision is already successful. Provisioning should already be idempotent so this shouldn't be a …

Scylla optimize provision

---

build-support/protoc_version.sh
pants.toml

Rather than using `grep` on TOML to extract which version of `protoc` is being used (which works, but can be fragile), we will instead parse a gigantic JSON dump of Pants' state and extract the version using `jq`.
This is more robust because it takes into account the layering that Pants uses (i.e., CLI options override `pants.toml` configuration, which in turn overrides hardcoded defaults). This means we don't even have to pin a version in `pants.toml` and the script will still work!
For now, however, I *have* opted to keep the pin in `pants.toml`, purely for visibility and explicitness.

Use `jq` to extract the version of `protoc` that Pants uses

---

src/rust/grapl-web-ui/tests/api/auth/check_login.rs
src/rust/grapl-web-ui/tests/api/auth/sign_in_with_password.rs
src/rust/grapl-web-ui/tests/api/ingress.rs
src/rust/grapl-web-ui/tests/api/plugin.rs
src/rust/grapl-web-ui/tests/api/test_app.rs

We're seeing intermittent 500 errors returned from the Consul sidecar in the grapl-web-ui integration tests.
These often occur after a test has already successfully made requests to grapl-web-ui, suggesting that service has had enough time to come up as healthy.
https://github.com/grapl-security/issue-tracker/issues/1008
This adds retry logic to the grapl-web-ui integration tests. Wen a request returns a 500 error, the request will retry up to ten times, waiting a second between each retry attempt.
CI

Add retries to flaky web integration tests.

---

pulumi/infra/kafka.py

Previously, we universally consumed from the `production` stack, because that was the only one we had. Now, each environment has its own stack, so we'll pull Kafka configuration information from the stack that "matches" the Grapl stack we're running.

Switch which `confluent-cloud` Pulumi stack we consume

---

.gitattributes

Files marked generated are "Excluded from stats, hidden in diffs". 
I was surprised that https://github.com/grapl-security/grapl/pull/2079 showed up as +800 -400 - that's because the Cargo.lock should be marked as generated.

Add Cargo.lock as a linguist-generated=true file

---

.github/CODEOWNERS
nomad/observability.nomad
nomad/rust-integration-tests.nomad
pulumi/infra/observability_env_vars.py
pulumi/rust_integration_tests/__main__.py
src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/Dockerfile
src/rust/grapl-metrics/Cargo.toml
src/rust/grapl-metrics/src/lib.rs
src/rust/grapl-metrics/src/setup_metrics.rs
src/rust/grapl-metrics/tests/metrics_integ_tests.rs

https://github.com/grapl-security/issue-tracker/issues/1048
Adds a library that makes it easy (well, as easy as otel can be) to emit custom application metrics from Rust code to the otel-collector (and, from there, to Lightstep). 
Unfortunately, there's not really a great way to **automated-ly** test that the metrics actually went through. 
However, I've included instructions on how to manually test that they reached the otel-collector.

Add the "grapl-metrics" crate and an integration test

---

src/rust/plugin-registry/src/static_files/hax_docker_analyzer.nomad
src/rust/plugin-registry/src/static_files/hax_docker_generator.nomad

none
running rust-integration-tests on laptop results in it complaining about too little CPU. Turns out we were giving the proxy tasks the default amount of 250 shares of cpu. I've dialed it down to 50. 
unfortunately my laptop is out of space so working on testing it...

Set cpu=50 for proxy tasks in plugins. They are currently 250.

---

src/rust/Dockerfile

See PR. Introduced with https://github.com/grapl-security/grapl/pull/2093 by accident.

Back out an undesirable regression in integration tests being run

---

docker-bake.hcl
src/rust/Dockerfile

TLDR: This enables
```
RUST_INTEGRATION_TEST_FEATURES_OVERRIDE="e2e-tests/integration_tests,uid-allocator/integration_tests" \
make test-integration-rust
```
It enables the behavior I initially wanted (and accidentally committed) that led to https://github.com/grapl-security/grapl/pull/2098
---
I tested it locally without specifying it and with specifying it.

Customize which integ tests build/run with an environment variable

---

.buildkite/pipeline.verify.yml

This endpoint has been failing for a day blocking PRs from landing. Seeing as we really rarely modify the codecov config, I'm "temporarily" (that is to say: i will likely forget to ever turn this off) changing this to soft_fail: true.

Make validate codecov step of CI soft_fail=true

---

src/rust/analyzer-dispatcher/tests/analyzer_dispatcher_integration_tests.rs
src/rust/e2e-tests/tests/sysmon_log_e2e_test.rs
src/rust/generator-dispatcher/tests/generator_dispatcher_integration_tests.rs
src/rust/plugin-work-queue/Cargo.toml
src/rust/plugin-work-queue/src/test_utils.rs

1. We had this ugly panic in our check-PWQ utils that I've replaced with an eyre::Result.
2. analyzer_dispatcher_integration_tests fails sometimes doe to the generator not being ready in time. I fortunately already wrote `assert_eventual_health` for this :)

Change a test-utils panic into a Result; add a wait-for-healthy-generator to analyzer_dispatcher_integration_tests to harden it
